/**
 * Liste der ~300 größten österreichischen Gemeinden mit Website-URLs.
 * Sortiert nach Bundesland, dann nach Einwohnerzahl (absteigend).
 *
 * Quellen:
 * - Statistik Austria Gemeindeverzeichnis
 * - citypopulation.de/de/austria
 * - Gemeinde-Websites verifiziert über gängige URL-Muster
 */

/** Identität + Website. Ortsdaten liefert withStammdaten(). */
export interface GemeindeInfo {
  name: string;
  website: string;
  bundesland: string;
  /** Früherer PLZ-Wert, nur als source_id-Schlüssel (keine Ortsangabe). */
  idKey: string;
}

// ─── WIEN ────────────────────────────────────────────────────────────────────
// Wien wird als Einzelgemeinde geführt (Bezirke sind keine eigenen Gemeinden)
const WIEN: GemeindeInfo[] = [
  { name: 'Wien', website: 'https://www.wien.gv.at', bundesland: 'Wien', idKey: '1010' },
];

// ─── NIEDERÖSTERREICH ────────────────────────────────────────────────────────
const NIEDEROESTERREICH: GemeindeInfo[] = [
  { name: 'St. Pölten', website: 'https://www.st-poelten.at', bundesland: 'Niederösterreich', idKey: '3100' },
  { name: 'Wiener Neustadt', website: 'https://www.wiener-neustadt.at', bundesland: 'Niederösterreich', idKey: '2700' },
  { name: 'Klosterneuburg', website: 'https://www.klosterneuburg.at', bundesland: 'Niederösterreich', idKey: '3400' },
  { name: 'Baden', website: 'https://www.baden.at', bundesland: 'Niederösterreich', idKey: '2500' },
  { name: 'Krems an der Donau', website: 'https://www.krems.at', bundesland: 'Niederösterreich', idKey: '3500' },
  { name: 'Amstetten', website: 'https://www.amstetten.at', bundesland: 'Niederösterreich', idKey: '3300' },
  { name: 'Schwechat', website: 'https://www.schwechat.gv.at', bundesland: 'Niederösterreich', idKey: '2320' },
  { name: 'Mödling', website: 'https://www.moedling.at', bundesland: 'Niederösterreich', idKey: '2340' },
  { name: 'Traiskirchen', website: 'https://www.traiskirchen.gv.at', bundesland: 'Niederösterreich', idKey: '2514' },
  { name: 'Stockerau', website: 'https://www.stockerau.at', bundesland: 'Niederösterreich', idKey: '2000' },
  { name: 'Tulln an der Donau', website: 'https://www.tulln.at', bundesland: 'Niederösterreich', idKey: '3430' },
  { name: 'Perchtoldsdorf', website: 'https://www.perchtoldsdorf.at', bundesland: 'Niederösterreich', idKey: '2380' },
  { name: 'Ternitz', website: 'https://www.ternitz.at', bundesland: 'Niederösterreich', idKey: '2630' },
  { name: 'Korneuburg', website: 'https://www.korneuburg.gv.at', bundesland: 'Niederösterreich', idKey: '2100' },
  { name: 'Neunkirchen', website: 'https://www.neunkirchen.gv.at', bundesland: 'Niederösterreich', idKey: '2620' },
  { name: 'Hollabrunn', website: 'https://www.hollabrunn.gv.at', bundesland: 'Niederösterreich', idKey: '2020' },
  { name: 'Bad Vöslau', website: 'https://www.badvoeslau.at', bundesland: 'Niederösterreich', idKey: '2540' },
  { name: 'Gänserndorf', website: 'https://www.gaenserndorf.at', bundesland: 'Niederösterreich', idKey: '2230' },
  { name: 'Strasshof an der Nordbahn', website: 'https://www.strasshof.at', bundesland: 'Niederösterreich', idKey: '2231' },
  { name: 'Brunn am Gebirge', website: 'https://www.brunn.at', bundesland: 'Niederösterreich', idKey: '2345' },
  { name: 'Gerasdorf bei Wien', website: 'https://www.gerasdorf.at', bundesland: 'Niederösterreich', idKey: '2201' },
  { name: 'Groß-Enzersdorf', website: 'https://www.gross-enzersdorf.gv.at', bundesland: 'Niederösterreich', idKey: '2301' },
  { name: 'Ebreichsdorf', website: 'https://www.ebreichsdorf.at', bundesland: 'Niederösterreich', idKey: '2483' },
  { name: 'Mistelbach', website: 'https://www.mistelbach.at', bundesland: 'Niederösterreich', idKey: '2130' },
  { name: 'Waidhofen an der Ybbs', website: 'https://www.waidhofen.at', bundesland: 'Niederösterreich', idKey: '3340' },
  { name: 'Zwettl', website: 'https://www.zwettl.gv.at', bundesland: 'Niederösterreich', idKey: '3910' },
  { name: 'Purkersdorf', website: 'https://www.purkersdorf.at', bundesland: 'Niederösterreich', idKey: '3002' },
  { name: 'Bruck an der Leitha', website: 'https://www.bruckleitha.at', bundesland: 'Niederösterreich', idKey: '2460' },
  { name: 'Wieselburg', website: 'https://www.wieselburg.gv.at', bundesland: 'Niederösterreich', idKey: '3250' },
  { name: 'Melk', website: 'https://www.stadt-melk.at', bundesland: 'Niederösterreich', idKey: '3390' },
  { name: 'Wolkersdorf im Weinviertel', website: 'https://www.wolkersdorf.at', bundesland: 'Niederösterreich', idKey: '2120' },
  { name: 'Herzogenburg', website: 'https://www.herzogenburg.at', bundesland: 'Niederösterreich', idKey: '3130' },
  { name: 'Scheibbs', website: 'https://www.scheibbs.gv.at', bundesland: 'Niederösterreich', idKey: '3270' },
  { name: 'Gmünd', website: 'https://www.gmuend.at', bundesland: 'Niederösterreich', idKey: '3950' },
  { name: 'Berndorf', website: 'https://www.berndorf.gv.at', bundesland: 'Niederösterreich', idKey: '2560' },
  { name: 'Haag', website: 'https://www.haag.at', bundesland: 'Niederösterreich', idKey: '3350' },
  { name: 'Lilienfeld', website: 'https://www.lilienfeld.at', bundesland: 'Niederösterreich', idKey: '3180' },
  { name: 'Heidenreichstein', website: 'https://www.heidenreichstein.at', bundesland: 'Niederösterreich', idKey: '3860' },
  { name: 'Fischamend', website: 'https://www.fischamend.gv.at', bundesland: 'Niederösterreich', idKey: '2401' },
  { name: 'Deutsch-Wagram', website: 'https://www.deutsch-wagram.at', bundesland: 'Niederösterreich', idKey: '2232' },
  { name: 'Leobersdorf', website: 'https://www.leobersdorf.at', bundesland: 'Niederösterreich', idKey: '2544' },
  { name: 'Wöllersdorf-Steinabrückl', website: 'https://www.woellersdorf-steinabrueckl.at', bundesland: 'Niederösterreich', idKey: '2752' },
  { name: 'Pressbaum', website: 'https://www.pressbaum.at', bundesland: 'Niederösterreich', idKey: '3021' },
  { name: 'Himberg', website: 'https://www.himberg.at', bundesland: 'Niederösterreich', idKey: '2325' },
  { name: 'Pottendorf', website: 'https://www.pottendorf.at', bundesland: 'Niederösterreich', idKey: '2486' },
  { name: 'Zwettl-Niederösterreich', website: 'https://www.zwettl.gv.at', bundesland: 'Niederösterreich', idKey: '3910' },
  { name: 'Guntramsdorf', website: 'https://www.guntramsdorf.at', bundesland: 'Niederösterreich', idKey: '2353' },
  { name: 'Vösendorf', website: 'https://www.voesendorf.gv.at', bundesland: 'Niederösterreich', idKey: '2331' },
  { name: 'Ybbs an der Donau', website: 'https://www.ybbs.at', bundesland: 'Niederösterreich', idKey: '3370' },
  { name: 'Pöchlarn', website: 'https://www.poechlarn.at', bundesland: 'Niederösterreich', idKey: '3380' },
  { name: 'Hainburg an der Donau', website: 'https://www.hainburg-donau.gv.at', bundesland: 'Niederösterreich', idKey: '2410' },
  { name: 'Bisamberg', website: 'https://www.bisamberg.at', bundesland: 'Niederösterreich', idKey: '2102' },
  { name: 'Kottingbrunn', website: 'https://www.kottingbrunn.at', bundesland: 'Niederösterreich', idKey: '2542' },
  { name: 'Groß-Siegharts', website: 'https://www.gross-siegharts.at', bundesland: 'Niederösterreich', idKey: '3812' },
];

// ─── OBERÖSTERREICH ──────────────────────────────────────────────────────────
const OBEROESTERREICH: GemeindeInfo[] = [
  { name: 'Linz', website: 'https://www.linz.at', bundesland: 'Oberösterreich', idKey: '4020' },
  { name: 'Wels', website: 'https://www.wels.at', bundesland: 'Oberösterreich', idKey: '4600' },
  { name: 'Steyr', website: 'https://www.steyr.at', bundesland: 'Oberösterreich', idKey: '4400' },
  { name: 'Leonding', website: 'https://www.leonding.at', bundesland: 'Oberösterreich', idKey: '4060' },
  { name: 'Traun', website: 'https://www.traun.at', bundesland: 'Oberösterreich', idKey: '4050' },
  { name: 'Ansfelden', website: 'https://www.ansfelden.at', bundesland: 'Oberösterreich', idKey: '4052' },
  { name: 'Braunau am Inn', website: 'https://www.braunau.at', bundesland: 'Oberösterreich', idKey: '5280' },
  { name: 'Marchtrenk', website: 'https://www.marchtrenk.at', bundesland: 'Oberösterreich', idKey: '4614' },
  { name: 'Bad Ischl', website: 'https://www.badischl.at', bundesland: 'Oberösterreich', idKey: '4820' },
  { name: 'Gmunden', website: 'https://www.gmunden.at', bundesland: 'Oberösterreich', idKey: '4810' },
  { name: 'Vöcklabruck', website: 'https://www.voecklabruck.at', bundesland: 'Oberösterreich', idKey: '4840' },
  { name: 'Ried im Innkreis', website: 'https://www.ried.at', bundesland: 'Oberösterreich', idKey: '4910' },
  { name: 'Enns', website: 'https://www.enns.at', bundesland: 'Oberösterreich', idKey: '4470' },
  { name: 'Laakirchen', website: 'https://www.laakirchen.at', bundesland: 'Oberösterreich', idKey: '4663' },
  { name: 'Sierning', website: 'https://www.sierning.at', bundesland: 'Oberösterreich', idKey: '4522' },
  { name: 'Altmünster', website: 'https://www.altmuenster.at', bundesland: 'Oberösterreich', idKey: '4813' },
  { name: 'Schärding', website: 'https://www.schaerding.at', bundesland: 'Oberösterreich', idKey: '4780' },
  { name: 'Attnang-Puchheim', website: 'https://www.attnang-puchheim.at', bundesland: 'Oberösterreich', idKey: '4800' },
  { name: 'Pregarten', website: 'https://www.pregarten.at', bundesland: 'Oberösterreich', idKey: '4230' },
  { name: 'Freistadt', website: 'https://www.freistadt.at', bundesland: 'Oberösterreich', idKey: '4240' },
  { name: 'Perg', website: 'https://www.perg.at', bundesland: 'Oberösterreich', idKey: '4320' },
  { name: 'Grieskirchen', website: 'https://www.grieskirchen.at', bundesland: 'Oberösterreich', idKey: '4710' },
  { name: 'Kirchdorf an der Krems', website: 'https://www.kirchdorf.at', bundesland: 'Oberösterreich', idKey: '4560' },
  { name: 'Mattighofen', website: 'https://www.mattighofen.at', bundesland: 'Oberösterreich', idKey: '5230' },
  { name: 'Rohrbach-Berg', website: 'https://www.rohrbach-berg.at', bundesland: 'Oberösterreich', idKey: '4150' },
  { name: 'Eferding', website: 'https://www.eferding.at', bundesland: 'Oberösterreich', idKey: '4070' },
  { name: 'Gallneukirchen', website: 'https://www.gallneukirchen.at', bundesland: 'Oberösterreich', idKey: '4210' },
  { name: 'Thalheim bei Wels', website: 'https://www.thalheim.at', bundesland: 'Oberösterreich', idKey: '4600' },
  { name: 'Bad Hall', website: 'https://www.badhall.at', bundesland: 'Oberösterreich', idKey: '4540' },
  { name: 'Kremsmünster', website: 'https://www.kremsmuenster.at', bundesland: 'Oberösterreich', idKey: '4550' },
  { name: 'Asten', website: 'https://www.asten.at', bundesland: 'Oberösterreich', idKey: '4481' },
  { name: 'Gunskirchen', website: 'https://www.gunskirchen.at', bundesland: 'Oberösterreich', idKey: '4623' },
  { name: 'Regau', website: 'https://www.regau.at', bundesland: 'Oberösterreich', idKey: '4844' },
  { name: 'Ebensee am Traunsee', website: 'https://www.ebensee.at', bundesland: 'Oberösterreich', idKey: '4802' },
  { name: 'Ottensheim', website: 'https://www.ottensheim.at', bundesland: 'Oberösterreich', idKey: '4100' },
  { name: 'Gaspoltshofen', website: 'https://www.gaspoltshofen.at', bundesland: 'Oberösterreich', idKey: '4673' },
  { name: 'Bad Leonfelden', website: 'https://www.bad-leonfelden.at', bundesland: 'Oberösterreich', idKey: '4190' },
  { name: 'Micheldorf in Oberösterreich', website: 'https://www.micheldorf.at', bundesland: 'Oberösterreich', idKey: '4563' },
  { name: 'Hörsching', website: 'https://www.hoersching.at', bundesland: 'Oberösterreich', idKey: '4063' },
  { name: 'Pasching', website: 'https://www.pasching.at', bundesland: 'Oberösterreich', idKey: '4061' },
  { name: 'Neuhofen an der Krems', website: 'https://www.neuhofen.at', bundesland: 'Oberösterreich', idKey: '4501' },
  { name: 'Mondsee', website: 'https://www.mondsee.at', bundesland: 'Oberösterreich', idKey: '5310' },
  { name: 'Frankenmarkt', website: 'https://www.frankenmarkt.at', bundesland: 'Oberösterreich', idKey: '4890' },
  { name: 'Peuerbach', website: 'https://www.peuerbach.at', bundesland: 'Oberösterreich', idKey: '4722' },
];

// ─── STEIERMARK ──────────────────────────────────────────────────────────────
const STEIERMARK: GemeindeInfo[] = [
  { name: 'Graz', website: 'https://www.graz.at', bundesland: 'Steiermark', idKey: '8010' },
  { name: 'Leoben', website: 'https://www.leoben.at', bundesland: 'Steiermark', idKey: '8700' },
  { name: 'Kapfenberg', website: 'https://www.kapfenberg.at', bundesland: 'Steiermark', idKey: '8605' },
  { name: 'Leibnitz', website: 'https://www.leibnitz.at', bundesland: 'Steiermark', idKey: '8430' },
  { name: 'Feldbach', website: 'https://www.feldbach.gv.at', bundesland: 'Steiermark', idKey: '8330' },
  { name: 'Knittelfeld', website: 'https://www.knittelfeld.at', bundesland: 'Steiermark', idKey: '8720' },
  { name: 'Gratwein-Straßengel', website: 'https://www.gratwein-strassengel.gv.at', bundesland: 'Steiermark', idKey: '8111' },
  { name: 'Seiersberg-Pirka', website: 'https://www.seiersberg-pirka.at', bundesland: 'Steiermark', idKey: '8054' },
  { name: 'Weiz', website: 'https://www.weiz.at', bundesland: 'Steiermark', idKey: '8160' },
  { name: 'Deutschlandsberg', website: 'https://www.deutschlandsberg.at', bundesland: 'Steiermark', idKey: '8530' },
  { name: 'Gleisdorf', website: 'https://www.gleisdorf.at', bundesland: 'Steiermark', idKey: '8200' },
  { name: 'Trofaiach', website: 'https://www.trofaiach.at', bundesland: 'Steiermark', idKey: '8793' },
  { name: 'Köflach', website: 'https://www.koeflach.at', bundesland: 'Steiermark', idKey: '8580' },
  { name: 'Voitsberg', website: 'https://www.voitsberg.at', bundesland: 'Steiermark', idKey: '8570' },
  { name: 'Bruck an der Mur', website: 'https://www.bruckmur.at', bundesland: 'Steiermark', idKey: '8600' },
  { name: 'Mürzzuschlag', website: 'https://www.muerzzuschlag.at', bundesland: 'Steiermark', idKey: '8680' },
  { name: 'Judenburg', website: 'https://www.judenburg.at', bundesland: 'Steiermark', idKey: '8750' },
  { name: 'Hartberg', website: 'https://www.hartberg.at', bundesland: 'Steiermark', idKey: '8230' },
  { name: 'Fürstenfeld', website: 'https://www.fuerstenfeld.gv.at', bundesland: 'Steiermark', idKey: '8280' },
  { name: 'Murau', website: 'https://www.murau.gv.at', bundesland: 'Steiermark', idKey: '8850' },
  { name: 'Liezen', website: 'https://www.liezen.at', bundesland: 'Steiermark', idKey: '8940' },
  { name: 'Schladming', website: 'https://www.schladming.at', bundesland: 'Steiermark', idKey: '8970' },
  { name: 'Bärnbach', website: 'https://www.baernbach.at', bundesland: 'Steiermark', idKey: '8572' },
  { name: 'Kindberg', website: 'https://www.kindberg.at', bundesland: 'Steiermark', idKey: '8650' },
  { name: 'Gratkorn', website: 'https://www.gratkorn.gv.at', bundesland: 'Steiermark', idKey: '8101' },
  { name: 'Kalsdorf bei Graz', website: 'https://www.kalsdorf-graz.at', bundesland: 'Steiermark', idKey: '8401' },
  { name: 'Fehring', website: 'https://www.fehring.at', bundesland: 'Steiermark', idKey: '8350' },
  { name: 'Premstätten', website: 'https://www.premstaetten.gv.at', bundesland: 'Steiermark', idKey: '8141' },
  { name: 'Fohnsdorf', website: 'https://www.fohnsdorf.at', bundesland: 'Steiermark', idKey: '8753' },
  { name: 'Zeltweg', website: 'https://www.zeltweg.at', bundesland: 'Steiermark', idKey: '8740' },
  { name: 'Spielberg', website: 'https://www.spielberg.at', bundesland: 'Steiermark', idKey: '8724' },
  { name: 'Rottenmann', website: 'https://www.rottenmann.at', bundesland: 'Steiermark', idKey: '8786' },
  { name: 'Bad Radkersburg', website: 'https://www.bad-radkersburg.gv.at', bundesland: 'Steiermark', idKey: '8490' },
  { name: 'Krieglach', website: 'https://www.krieglach.at', bundesland: 'Steiermark', idKey: '8670' },
  { name: 'Stainz', website: 'https://www.stainz.at', bundesland: 'Steiermark', idKey: '8510' },
  { name: 'Pischelsdorf am Kulm', website: 'https://www.pischelsdorf.at', bundesland: 'Steiermark', idKey: '8212' },
  { name: 'Wagna', website: 'https://www.wagna.at', bundesland: 'Steiermark', idKey: '8435' },
  { name: 'Frohnleiten', website: 'https://www.frohnleiten.com', bundesland: 'Steiermark', idKey: '8130' },
  { name: 'Niklasdorf', website: 'https://www.niklasdorf.at', bundesland: 'Steiermark', idKey: '8712' },
  { name: 'Kumberg', website: 'https://www.kumberg.at', bundesland: 'Steiermark', idKey: '8062' },
  { name: 'Kainbach bei Graz', website: 'https://www.kainbach.at', bundesland: 'Steiermark', idKey: '8010' },
];

// ─── SALZBURG ────────────────────────────────────────────────────────────────
const SALZBURG: GemeindeInfo[] = [
  { name: 'Salzburg', website: 'https://www.stadt-salzburg.at', bundesland: 'Salzburg', idKey: '5020' },
  { name: 'Hallein', website: 'https://www.hallein.com', bundesland: 'Salzburg', idKey: '5400' },
  { name: 'Saalfelden am Steinernen Meer', website: 'https://www.saalfelden.at', bundesland: 'Salzburg', idKey: '5760' },
  { name: 'Wals-Siezenheim', website: 'https://www.wals-siezenheim.at', bundesland: 'Salzburg', idKey: '5071' },
  { name: 'Seekirchen am Wallersee', website: 'https://www.seekirchen.at', bundesland: 'Salzburg', idKey: '5201' },
  { name: 'St. Johann im Pongau', website: 'https://www.stjohann.at', bundesland: 'Salzburg', idKey: '5600' },
  { name: 'Bischofshofen', website: 'https://www.bischofshofen.at', bundesland: 'Salzburg', idKey: '5500' },
  { name: 'Zell am See', website: 'https://www.zellamsee.at', bundesland: 'Salzburg', idKey: '5700' },
  { name: 'Straßwalchen', website: 'https://www.strasswalchen.at', bundesland: 'Salzburg', idKey: '5204' },
  { name: 'Kuchl', website: 'https://www.kuchl.net', bundesland: 'Salzburg', idKey: '5431' },
  { name: 'Grödig', website: 'https://www.groedig.at', bundesland: 'Salzburg', idKey: '5082' },
  { name: 'Bergheim', website: 'https://www.bergheim.at', bundesland: 'Salzburg', idKey: '5101' },
  { name: 'Mittersill', website: 'https://www.mittersill.at', bundesland: 'Salzburg', idKey: '5730' },
  { name: 'Radstadt', website: 'https://www.radstadt.at', bundesland: 'Salzburg', idKey: '5550' },
  { name: 'Neumarkt am Wallersee', website: 'https://www.neumarkt.at', bundesland: 'Salzburg', idKey: '5202' },
  { name: 'Oberndorf bei Salzburg', website: 'https://www.oberndorf.at', bundesland: 'Salzburg', idKey: '5110' },
  { name: 'Tamsweg', website: 'https://www.tamsweg.at', bundesland: 'Salzburg', idKey: '5580' },
];

// ─── TIROL ───────────────────────────────────────────────────────────────────
const TIROL: GemeindeInfo[] = [
  { name: 'Innsbruck', website: 'https://www.innsbruck.gv.at', bundesland: 'Tirol', idKey: '6020' },
  { name: 'Kufstein', website: 'https://www.kufstein.at', bundesland: 'Tirol', idKey: '6330' },
  { name: 'Telfs', website: 'https://www.telfs.at', bundesland: 'Tirol', idKey: '6410' },
  { name: 'Hall in Tirol', website: 'https://www.hall-in-tirol.at', bundesland: 'Tirol', idKey: '6060' },
  { name: 'Schwaz', website: 'https://www.schwaz.at', bundesland: 'Tirol', idKey: '6130' },
  { name: 'Wörgl', website: 'https://www.woergl.at', bundesland: 'Tirol', idKey: '6300' },
  { name: 'Lienz', website: 'https://www.lienz.gv.at', bundesland: 'Tirol', idKey: '9900' },
  { name: 'Imst', website: 'https://www.imst.at', bundesland: 'Tirol', idKey: '6460' },
  { name: 'St. Johann in Tirol', website: 'https://www.stjohann.tirol.gv.at', bundesland: 'Tirol', idKey: '6380' },
  { name: 'Rum', website: 'https://www.rum.gv.at', bundesland: 'Tirol', idKey: '6063' },
  { name: 'Völs', website: 'https://www.voels.at', bundesland: 'Tirol', idKey: '6176' },
  { name: 'Zirl', website: 'https://www.zirl.at', bundesland: 'Tirol', idKey: '6170' },
  { name: 'Kitzbühel', website: 'https://www.kitzbuehel.at', bundesland: 'Tirol', idKey: '6370' },
  { name: 'Absam', website: 'https://www.absam.at', bundesland: 'Tirol', idKey: '6067' },
  { name: 'Wattens', website: 'https://www.wattens.at', bundesland: 'Tirol', idKey: '6112' },
  { name: 'Landeck', website: 'https://www.landeck.tirol.gv.at', bundesland: 'Tirol', idKey: '6500' },
  { name: 'Reutte', website: 'https://www.reutte.at', bundesland: 'Tirol', idKey: '6600' },
  { name: 'Jenbach', website: 'https://www.jenbach.at', bundesland: 'Tirol', idKey: '6200' },
  { name: 'Kematen in Tirol', website: 'https://none', bundesland: 'Tirol', idKey: '6175' },
  { name: 'Axams', website: 'https://www.axams.at', bundesland: 'Tirol', idKey: '6094' },
  { name: 'Kirchbichl', website: 'https://www.kirchbichl.at', bundesland: 'Tirol', idKey: '6322' },
  { name: 'Kundl', website: 'https://www.kundl.tirol.gv.at', bundesland: 'Tirol', idKey: '6250' },
  { name: 'Mayrhofen', website: 'https://www.mayrhofen.at', bundesland: 'Tirol', idKey: '6290' },
  { name: 'Seefeld in Tirol', website: 'https://www.seefeld.at', bundesland: 'Tirol', idKey: '6100' },
  { name: 'Fügen', website: 'https://www.fuegen.at', bundesland: 'Tirol', idKey: '6263' },
  { name: 'Vomp', website: 'https://www.vomp.at', bundesland: 'Tirol', idKey: '6134' },
  { name: 'Mils', website: 'https://www.mils.at', bundesland: 'Tirol', idKey: '6068' },
  { name: 'Matrei am Brenner', website: 'https://www.matrei-brenner.at', bundesland: 'Tirol', idKey: '6143' },
  { name: 'Thaur', website: 'https://www.thaur.at', bundesland: 'Tirol', idKey: '6065' },
  { name: 'Ebbs', website: 'https://www.ebbs.at', bundesland: 'Tirol', idKey: '6341' },
  { name: 'Söll', website: 'https://www.soell.at', bundesland: 'Tirol', idKey: '6306' },
];

// ─── KÄRNTEN ─────────────────────────────────────────────────────────────────
const KAERNTEN: GemeindeInfo[] = [
  { name: 'Klagenfurt am Wörthersee', website: 'https://www.klagenfurt.at', bundesland: 'Kärnten', idKey: '9020' },
  { name: 'Villach', website: 'https://www.villach.at', bundesland: 'Kärnten', idKey: '9500' },
  { name: 'Wolfsberg', website: 'https://www.wolfsberg.at', bundesland: 'Kärnten', idKey: '9400' },
  { name: 'Spittal an der Drau', website: 'https://www.spittal-drau.at', bundesland: 'Kärnten', idKey: '9800' },
  { name: 'Feldkirchen in Kärnten', website: 'https://www.feldkirchen.at', bundesland: 'Kärnten', idKey: '9560' },
  { name: 'St. Veit an der Glan', website: 'https://www.stveit.at', bundesland: 'Kärnten', idKey: '9300' },
  { name: 'Völkermarkt', website: 'https://www.voelkermarkt.at', bundesland: 'Kärnten', idKey: '9100' },
  { name: 'Hermagor-Pressegger See', website: 'https://www.hermagor.at', bundesland: 'Kärnten', idKey: '9620' },
  { name: 'St. Andrä', website: 'https://www.st-andrae.at', bundesland: 'Kärnten', idKey: '9433' },
  { name: 'Ferlach', website: 'https://www.ferlach.at', bundesland: 'Kärnten', idKey: '9170' },
  { name: 'Althofen', website: 'https://www.althofen.at', bundesland: 'Kärnten', idKey: '9330' },
  { name: 'Bleiburg', website: 'https://www.bleiburg.at', bundesland: 'Kärnten', idKey: '9150' },
  { name: 'Radenthein', website: 'https://www.radenthein.at', bundesland: 'Kärnten', idKey: '9545' },
  { name: 'Gmünd in Kärnten', website: 'https://www.gmuend-kaernten.at', bundesland: 'Kärnten', idKey: '9853' },
  { name: 'Friesach', website: 'https://www.friesach.at', bundesland: 'Kärnten', idKey: '9360' },
  { name: 'Bad Kleinkirchheim', website: 'https://www.badkleinkirchheim.at', bundesland: 'Kärnten', idKey: '9546' },
  { name: 'Velden am Wörthersee', website: 'https://www.velden.gv.at', bundesland: 'Kärnten', idKey: '9220' },
  { name: 'Maria Saal', website: 'https://www.maria-saal.gv.at', bundesland: 'Kärnten', idKey: '9063' },
];

// ─── VORARLBERG ──────────────────────────────────────────────────────────────
const VORARLBERG: GemeindeInfo[] = [
  { name: 'Dornbirn', website: 'https://www.dornbirn.at', bundesland: 'Vorarlberg', idKey: '6850' },
  { name: 'Feldkirch', website: 'https://www.feldkirch.at', bundesland: 'Vorarlberg', idKey: '6800' },
  { name: 'Bregenz', website: 'https://www.bregenz.at', bundesland: 'Vorarlberg', idKey: '6900' },
  { name: 'Lustenau', website: 'https://www.lustenau.at', bundesland: 'Vorarlberg', idKey: '6890' },
  { name: 'Hohenems', website: 'https://www.hohenems.at', bundesland: 'Vorarlberg', idKey: '6845' },
  { name: 'Bludenz', website: 'https://www.bludenz.at', bundesland: 'Vorarlberg', idKey: '6700' },
  { name: 'Hard', website: 'https://www.hard.at', bundesland: 'Vorarlberg', idKey: '6971' },
  { name: 'Rankweil', website: 'https://www.rankweil.at', bundesland: 'Vorarlberg', idKey: '6830' },
  { name: 'Götzis', website: 'https://www.goetzis.at', bundesland: 'Vorarlberg', idKey: '6840' },
  { name: 'Lauterach', website: 'https://www.lauterach.at', bundesland: 'Vorarlberg', idKey: '6923' },
  { name: 'Höchst', website: 'https://www.hoechst.at', bundesland: 'Vorarlberg', idKey: '6973' },
  { name: 'Wolfurt', website: 'https://www.wolfurt.at', bundesland: 'Vorarlberg', idKey: '6922' },
  { name: 'Nenzing', website: 'https://www.nenzing.at', bundesland: 'Vorarlberg', idKey: '6710' },
  { name: 'Schwarzach', website: 'https://www.schwarzach.at', bundesland: 'Vorarlberg', idKey: '6858' },
  { name: 'Schruns', website: 'https://www.schruns.at', bundesland: 'Vorarlberg', idKey: '6780' },
];

// ─── BURGENLAND ──────────────────────────────────────────────────────────────
const BURGENLAND: GemeindeInfo[] = [
  { name: 'Eisenstadt', website: 'https://www.eisenstadt.gv.at', bundesland: 'Burgenland', idKey: '7000' },
  { name: 'Oberwart', website: 'https://www.oberwart.at', bundesland: 'Burgenland', idKey: '7400' },
  { name: 'Neusiedl am See', website: 'https://www.neusiedlamsee.at', bundesland: 'Burgenland', idKey: '7100' },
  { name: 'Mattersburg', website: 'https://www.mattersburg.gv.at', bundesland: 'Burgenland', idKey: '7210' },
  { name: 'Pinkafeld', website: 'https://www.pinkafeld.gv.at', bundesland: 'Burgenland', idKey: '7423' },
  { name: 'Oberpullendorf', website: 'https://www.oberpullendorf.gv.at', bundesland: 'Burgenland', idKey: '7350' },
  { name: 'Güssing', website: 'https://www.guessing.at', bundesland: 'Burgenland', idKey: '7540' },
  { name: 'Jennersdorf', website: 'https://www.jennersdorf.gv.at', bundesland: 'Burgenland', idKey: '8380' },
  { name: 'Großpetersdorf', website: 'https://www.grosspetersdorf.at', bundesland: 'Burgenland', idKey: '7503' },
  { name: 'Rust', website: 'https://www.rust.at', bundesland: 'Burgenland', idKey: '7071' },
  { name: 'Frauenkirchen', website: 'https://www.frauenkirchen.at', bundesland: 'Burgenland', idKey: '7132' },
  { name: 'Parndorf', website: 'https://www.parndorf.at', bundesland: 'Burgenland', idKey: '7111' },
  { name: 'Neufeld an der Leitha', website: 'https://www.neufeld-leitha.at', bundesland: 'Burgenland', idKey: '2491' },
  { name: 'Stegersbach', website: 'https://www.stegersbach.at', bundesland: 'Burgenland', idKey: '7551' },
  { name: 'Deutschkreutz', website: 'https://www.deutschkreutz.at', bundesland: 'Burgenland', idKey: '7301' },
  { name: 'Kittsee', website: 'https://www.kittsee.at', bundesland: 'Burgenland', idKey: '2421' },
  { name: 'Gols', website: 'https://www.gols.at', bundesland: 'Burgenland', idKey: '7122' },
  { name: 'Stadtschlaining', website: 'https://www.stadtschlaining.at', bundesland: 'Burgenland', idKey: '7461' },
  { name: 'Purbach am Neusiedler See', website: 'https://www.purbach.at', bundesland: 'Burgenland', idKey: '7083' },
  { name: 'Bruckneudorf', website: 'https://www.bruckneudorf.at', bundesland: 'Burgenland', idKey: '2460' },
  { name: 'Neudörfl', website: 'https://www.neudoerfl.at', bundesland: 'Burgenland', idKey: '7201' },
  { name: 'Bad Sauerbrunn', website: 'https://www.bad-sauerbrunn.at', bundesland: 'Burgenland', idKey: '7202' },
  { name: 'Rechnitz', website: 'https://www.rechnitz.at', bundesland: 'Burgenland', idKey: '7471' },
  { name: 'Siegendorf', website: 'https://www.siegendorf.at', bundesland: 'Burgenland', idKey: '7011' },
  { name: 'Hornstein', website: 'https://www.hornstein.at', bundesland: 'Burgenland', idKey: '7053' },
  { name: 'Bad Tatzmannsdorf', website: 'https://www.bad-tatzmannsdorf.at', bundesland: 'Burgenland', idKey: '7431' },
  { name: 'Illmitz', website: 'https://www.illmitz.at', bundesland: 'Burgenland', idKey: '7142' },
  { name: 'Pöttsching', website: 'https://www.poettsching.at', bundesland: 'Burgenland', idKey: '7033' },
  { name: 'Steinbrunn', website: 'https://www.steinbrunn.at', bundesland: 'Burgenland', idKey: '7035' },
  { name: 'Lockenhaus', website: 'https://www.lockenhaus.at', bundesland: 'Burgenland', idKey: '7442' },
  { name: 'Wallern im Burgenland', website: 'https://none', bundesland: 'Burgenland', idKey: '7151' },
  { name: 'Mörbisch am See', website: 'https://www.moerbisch.at', bundesland: 'Burgenland', idKey: '7072' },
];

// ─── GESAMTLISTE ─────────────────────────────────────────────────────────────
export const GEMEINDEN: GemeindeInfo[] = [
  ...WIEN,
  ...NIEDEROESTERREICH,
  ...OBEROESTERREICH,
  ...STEIERMARK,
  ...SALZBURG,
  ...TIROL,
  ...KAERNTEN,
  ...VORARLBERG,
  ...BURGENLAND,
];
