/**
 * Liste der ~300 größten österreichischen Gemeinden mit Website-URLs.
 * Sortiert nach Bundesland, dann nach Einwohnerzahl (absteigend).
 *
 * Quellen:
 * - Statistik Austria Gemeindeverzeichnis
 * - citypopulation.de/de/austria
 * - Gemeinde-Websites verifiziert über gängige URL-Muster
 */

export interface GemeindeInfo {
  name: string;
  website: string;
  plz: string;
  bezirk: string;
  bundesland: string;
  lat: number;
  lng: number;
}

// ─── WIEN ────────────────────────────────────────────────────────────────────
// Wien wird als Einzelgemeinde geführt (Bezirke sind keine eigenen Gemeinden)
const WIEN: GemeindeInfo[] = [
  { name: 'Wien', website: 'https://www.wien.gv.at', plz: '1010', bezirk: 'Wien', bundesland: 'Wien', lat: 48.2082, lng: 16.3738 },
];

// ─── NIEDERÖSTERREICH ────────────────────────────────────────────────────────
const NIEDEROESTERREICH: GemeindeInfo[] = [
  { name: 'St. Pölten', website: 'https://www.st-poelten.at', plz: '3100', bezirk: 'St. Pölten (Stadt)', bundesland: 'Niederösterreich', lat: 48.2043, lng: 15.6229 },
  { name: 'Wiener Neustadt', website: 'https://www.wiener-neustadt.at', plz: '2700', bezirk: 'Wiener Neustadt (Stadt)', bundesland: 'Niederösterreich', lat: 47.8127, lng: 16.2467 },
  { name: 'Klosterneuburg', website: 'https://www.klosterneuburg.at', plz: '3400', bezirk: 'Tulln', bundesland: 'Niederösterreich', lat: 48.3052, lng: 16.3253 },
  { name: 'Baden', website: 'https://www.baden.at', plz: '2500', bezirk: 'Baden', bundesland: 'Niederösterreich', lat: 48.0069, lng: 16.2326 },
  { name: 'Krems an der Donau', website: 'https://www.krems.at', plz: '3500', bezirk: 'Krems an der Donau (Stadt)', bundesland: 'Niederösterreich', lat: 48.4092, lng: 15.6142 },
  { name: 'Amstetten', website: 'https://www.amstetten.at', plz: '3300', bezirk: 'Amstetten', bundesland: 'Niederösterreich', lat: 48.1228, lng: 14.8747 },
  { name: 'Schwechat', website: 'https://www.schwechat.gv.at', plz: '2320', bezirk: 'Bruck an der Leitha', bundesland: 'Niederösterreich', lat: 48.1381, lng: 16.4708 },
  { name: 'Mödling', website: 'https://www.moedling.at', plz: '2340', bezirk: 'Mödling', bundesland: 'Niederösterreich', lat: 48.0856, lng: 16.2878 },
  { name: 'Traiskirchen', website: 'https://www.traiskirchen.gv.at', plz: '2514', bezirk: 'Baden', bundesland: 'Niederösterreich', lat: 48.0167, lng: 16.2917 },
  { name: 'Stockerau', website: 'https://www.stockerau.at', plz: '2000', bezirk: 'Korneuburg', bundesland: 'Niederösterreich', lat: 48.3831, lng: 16.2119 },
  { name: 'Tulln an der Donau', website: 'https://www.tulln.at', plz: '3430', bezirk: 'Tulln', bundesland: 'Niederösterreich', lat: 48.3269, lng: 16.0569 },
  { name: 'Perchtoldsdorf', website: 'https://www.perchtoldsdorf.at', plz: '2380', bezirk: 'Mödling', bundesland: 'Niederösterreich', lat: 48.1189, lng: 16.2661 },
  { name: 'Ternitz', website: 'https://www.ternitz.at', plz: '2630', bezirk: 'Neunkirchen', bundesland: 'Niederösterreich', lat: 47.7167, lng: 16.0333 },
  { name: 'Korneuburg', website: 'https://www.korneuburg.gv.at', plz: '2100', bezirk: 'Korneuburg', bundesland: 'Niederösterreich', lat: 48.3500, lng: 16.3333 },
  { name: 'Neunkirchen', website: 'https://www.neunkirchen.gv.at', plz: '2620', bezirk: 'Neunkirchen', bundesland: 'Niederösterreich', lat: 47.7261, lng: 16.0811 },
  { name: 'Hollabrunn', website: 'https://www.hollabrunn.gv.at', plz: '2020', bezirk: 'Hollabrunn', bundesland: 'Niederösterreich', lat: 48.5606, lng: 15.9917 },
  { name: 'Bad Vöslau', website: 'https://www.badvoeslau.at', plz: '2540', bezirk: 'Baden', bundesland: 'Niederösterreich', lat: 47.9667, lng: 16.2167 },
  { name: 'Gänserndorf', website: 'https://www.gaenserndorf.at', plz: '2230', bezirk: 'Gänserndorf', bundesland: 'Niederösterreich', lat: 48.3397, lng: 16.7203 },
  { name: 'Strasshof an der Nordbahn', website: 'https://www.strasshof.at', plz: '2231', bezirk: 'Gänserndorf', bundesland: 'Niederösterreich', lat: 48.3203, lng: 16.6339 },
  { name: 'Brunn am Gebirge', website: 'https://www.brunn.at', plz: '2345', bezirk: 'Mödling', bundesland: 'Niederösterreich', lat: 48.1078, lng: 16.2847 },
  { name: 'Gerasdorf bei Wien', website: 'https://www.gerasdorf.at', plz: '2201', bezirk: 'Korneuburg', bundesland: 'Niederösterreich', lat: 48.2953, lng: 16.4672 },
  { name: 'Groß-Enzersdorf', website: 'https://www.gross-enzersdorf.gv.at', plz: '2301', bezirk: 'Gänserndorf', bundesland: 'Niederösterreich', lat: 48.2000, lng: 16.5500 },
  { name: 'Ebreichsdorf', website: 'https://www.ebreichsdorf.at', plz: '2483', bezirk: 'Baden', bundesland: 'Niederösterreich', lat: 47.9592, lng: 16.3939 },
  { name: 'Mistelbach', website: 'https://www.mistelbach.at', plz: '2130', bezirk: 'Mistelbach', bundesland: 'Niederösterreich', lat: 48.5706, lng: 16.5767 },
  { name: 'Waidhofen an der Ybbs', website: 'https://www.waidhofen.at', plz: '3340', bezirk: 'Waidhofen an der Ybbs (Stadt)', bundesland: 'Niederösterreich', lat: 47.9608, lng: 14.7731 },
  { name: 'Zwettl', website: 'https://www.zwettl.gv.at', plz: '3910', bezirk: 'Zwettl', bundesland: 'Niederösterreich', lat: 48.6047, lng: 15.1689 },
  { name: 'Purkersdorf', website: 'https://www.purkersdorf.at', plz: '3002', bezirk: 'St. Pölten-Land', bundesland: 'Niederösterreich', lat: 48.2069, lng: 16.1769 },
  { name: 'Bruck an der Leitha', website: 'https://www.bruckleitha.at', plz: '2460', bezirk: 'Bruck an der Leitha', bundesland: 'Niederösterreich', lat: 48.0256, lng: 16.7789 },
  { name: 'Wieselburg', website: 'https://www.wieselburg.gv.at', plz: '3250', bezirk: 'Scheibbs', bundesland: 'Niederösterreich', lat: 48.1306, lng: 15.1369 },
  { name: 'Melk', website: 'https://www.stadt-melk.at', plz: '3390', bezirk: 'Melk', bundesland: 'Niederösterreich', lat: 48.2275, lng: 15.3322 },
  { name: 'Wolkersdorf im Weinviertel', website: 'https://www.wolkersdorf.at', plz: '2120', bezirk: 'Mistelbach', bundesland: 'Niederösterreich', lat: 48.3833, lng: 16.5167 },
  { name: 'Herzogenburg', website: 'https://www.herzogenburg.at', plz: '3130', bezirk: 'St. Pölten-Land', bundesland: 'Niederösterreich', lat: 48.2856, lng: 15.6931 },
  { name: 'Scheibbs', website: 'https://www.scheibbs.gv.at', plz: '3270', bezirk: 'Scheibbs', bundesland: 'Niederösterreich', lat: 48.0008, lng: 15.1667 },
  { name: 'Gmünd', website: 'https://www.gmuend.at', plz: '3950', bezirk: 'Gmünd', bundesland: 'Niederösterreich', lat: 48.7689, lng: 14.9847 },
  { name: 'Berndorf', website: 'https://www.berndorf.gv.at', plz: '2560', bezirk: 'Baden', bundesland: 'Niederösterreich', lat: 47.9431, lng: 16.1042 },
  { name: 'Haag', website: 'https://www.haag.at', plz: '3350', bezirk: 'Amstetten', bundesland: 'Niederösterreich', lat: 48.1117, lng: 14.5636 },
  { name: 'Lilienfeld', website: 'https://www.lilienfeld.at', plz: '3180', bezirk: 'Lilienfeld', bundesland: 'Niederösterreich', lat: 48.0131, lng: 15.5961 },
  { name: 'Heidenreichstein', website: 'https://www.heidenreichstein.at', plz: '3860', bezirk: 'Gmünd', bundesland: 'Niederösterreich', lat: 48.8622, lng: 15.1200 },
  { name: 'Fischamend', website: 'https://www.fischamend.gv.at', plz: '2401', bezirk: 'Bruck an der Leitha', bundesland: 'Niederösterreich', lat: 48.1167, lng: 16.6000 },
  { name: 'Deutsch-Wagram', website: 'https://www.deutsch-wagram.at', plz: '2232', bezirk: 'Gänserndorf', bundesland: 'Niederösterreich', lat: 48.2994, lng: 16.5594 },
  { name: 'Leobersdorf', website: 'https://www.leobersdorf.at', plz: '2544', bezirk: 'Baden', bundesland: 'Niederösterreich', lat: 47.9267, lng: 16.2167 },
  { name: 'Wöllersdorf-Steinabrückl', website: 'https://www.woellersdorf-steinabrueckl.at', plz: '2752', bezirk: 'Wiener Neustadt-Land', bundesland: 'Niederösterreich', lat: 47.8667, lng: 16.1833 },
  { name: 'Pressbaum', website: 'https://www.pressbaum.at', plz: '3021', bezirk: 'St. Pölten-Land', bundesland: 'Niederösterreich', lat: 48.1833, lng: 16.0833 },
  { name: 'Himberg', website: 'https://www.himberg.at', plz: '2325', bezirk: 'Bruck an der Leitha', bundesland: 'Niederösterreich', lat: 48.0833, lng: 16.4333 },
  { name: 'Pottendorf', website: 'https://www.pottendorf.at', plz: '2486', bezirk: 'Baden', bundesland: 'Niederösterreich', lat: 47.9083, lng: 16.3917 },
  { name: 'Zwettl-Niederösterreich', website: 'https://www.zwettl.gv.at', plz: '3910', bezirk: 'Zwettl', bundesland: 'Niederösterreich', lat: 48.6047, lng: 15.1689 },
  { name: 'Guntramsdorf', website: 'https://www.guntramsdorf.at', plz: '2353', bezirk: 'Mödling', bundesland: 'Niederösterreich', lat: 48.0444, lng: 16.3111 },
  { name: 'Vösendorf', website: 'https://www.voesendorf.gv.at', plz: '2331', bezirk: 'Mödling', bundesland: 'Niederösterreich', lat: 48.1167, lng: 16.3333 },
  { name: 'Ybbs an der Donau', website: 'https://www.ybbs.at', plz: '3370', bezirk: 'Melk', bundesland: 'Niederösterreich', lat: 48.1711, lng: 15.0822 },
  { name: 'Pöchlarn', website: 'https://www.poechlarn.at', plz: '3380', bezirk: 'Melk', bundesland: 'Niederösterreich', lat: 48.2000, lng: 15.2167 },
  { name: 'Hainburg an der Donau', website: 'https://www.hainburg-donau.gv.at', plz: '2410', bezirk: 'Bruck an der Leitha', bundesland: 'Niederösterreich', lat: 48.1486, lng: 16.9444 },
  { name: 'Bisamberg', website: 'https://www.bisamberg.at', plz: '2102', bezirk: 'Korneuburg', bundesland: 'Niederösterreich', lat: 48.3333, lng: 16.3667 },
  { name: 'Kottingbrunn', website: 'https://www.kottingbrunn.at', plz: '2542', bezirk: 'Baden', bundesland: 'Niederösterreich', lat: 47.9500, lng: 16.2167 },
  { name: 'Groß-Siegharts', website: 'https://www.gross-siegharts.at', plz: '3812', bezirk: 'Waidhofen an der Thaya', bundesland: 'Niederösterreich', lat: 48.7903, lng: 15.4033 },
];

// ─── OBERÖSTERREICH ──────────────────────────────────────────────────────────
const OBEROESTERREICH: GemeindeInfo[] = [
  { name: 'Linz', website: 'https://www.linz.at', plz: '4020', bezirk: 'Linz (Stadt)', bundesland: 'Oberösterreich', lat: 48.3064, lng: 14.2858 },
  { name: 'Wels', website: 'https://www.wels.at', plz: '4600', bezirk: 'Wels (Stadt)', bundesland: 'Oberösterreich', lat: 48.1575, lng: 14.0289 },
  { name: 'Steyr', website: 'https://www.steyr.at', plz: '4400', bezirk: 'Steyr (Stadt)', bundesland: 'Oberösterreich', lat: 48.0392, lng: 14.4214 },
  { name: 'Leonding', website: 'https://www.leonding.at', plz: '4060', bezirk: 'Linz-Land', bundesland: 'Oberösterreich', lat: 48.2792, lng: 14.2478 },
  { name: 'Traun', website: 'https://www.traun.at', plz: '4050', bezirk: 'Linz-Land', bundesland: 'Oberösterreich', lat: 48.2211, lng: 14.2356 },
  { name: 'Ansfelden', website: 'https://www.ansfelden.at', plz: '4052', bezirk: 'Linz-Land', bundesland: 'Oberösterreich', lat: 48.2097, lng: 14.2889 },
  { name: 'Braunau am Inn', website: 'https://www.braunau.at', plz: '5280', bezirk: 'Braunau am Inn', bundesland: 'Oberösterreich', lat: 48.2567, lng: 13.0350 },
  { name: 'Marchtrenk', website: 'https://www.marchtrenk.at', plz: '4614', bezirk: 'Wels-Land', bundesland: 'Oberösterreich', lat: 48.1908, lng: 14.1111 },
  { name: 'Bad Ischl', website: 'https://www.badischl.at', plz: '4820', bezirk: 'Gmunden', bundesland: 'Oberösterreich', lat: 47.7119, lng: 13.6194 },
  { name: 'Gmunden', website: 'https://www.gmunden.at', plz: '4810', bezirk: 'Gmunden', bundesland: 'Oberösterreich', lat: 47.9186, lng: 13.7992 },
  { name: 'Vöcklabruck', website: 'https://www.voecklabruck.at', plz: '4840', bezirk: 'Vöcklabruck', bundesland: 'Oberösterreich', lat: 48.0031, lng: 13.6558 },
  { name: 'Ried im Innkreis', website: 'https://www.ried.at', plz: '4910', bezirk: 'Ried im Innkreis', bundesland: 'Oberösterreich', lat: 48.2092, lng: 13.4889 },
  { name: 'Enns', website: 'https://www.enns.at', plz: '4470', bezirk: 'Linz-Land', bundesland: 'Oberösterreich', lat: 48.2122, lng: 14.4742 },
  { name: 'Laakirchen', website: 'https://www.laakirchen.at', plz: '4663', bezirk: 'Gmunden', bundesland: 'Oberösterreich', lat: 47.9806, lng: 13.8250 },
  { name: 'Sierning', website: 'https://www.sierning.at', plz: '4522', bezirk: 'Steyr-Land', bundesland: 'Oberösterreich', lat: 48.0442, lng: 14.3100 },
  { name: 'Altmünster', website: 'https://www.altmuenster.at', plz: '4813', bezirk: 'Gmunden', bundesland: 'Oberösterreich', lat: 47.9000, lng: 13.7633 },
  { name: 'Schärding', website: 'https://www.schaerding.at', plz: '4780', bezirk: 'Schärding', bundesland: 'Oberösterreich', lat: 48.4533, lng: 13.4317 },
  { name: 'Attnang-Puchheim', website: 'https://www.attnang-puchheim.at', plz: '4800', bezirk: 'Vöcklabruck', bundesland: 'Oberösterreich', lat: 48.0117, lng: 13.7200 },
  { name: 'Pregarten', website: 'https://www.pregarten.at', plz: '4230', bezirk: 'Freistadt', bundesland: 'Oberösterreich', lat: 48.3553, lng: 14.5322 },
  { name: 'Freistadt', website: 'https://www.freistadt.at', plz: '4240', bezirk: 'Freistadt', bundesland: 'Oberösterreich', lat: 48.5117, lng: 14.5050 },
  { name: 'Perg', website: 'https://www.perg.at', plz: '4320', bezirk: 'Perg', bundesland: 'Oberösterreich', lat: 48.2439, lng: 14.6361 },
  { name: 'Grieskirchen', website: 'https://www.grieskirchen.at', plz: '4710', bezirk: 'Grieskirchen', bundesland: 'Oberösterreich', lat: 48.2347, lng: 13.8308 },
  { name: 'Kirchdorf an der Krems', website: 'https://www.kirchdorf.at', plz: '4560', bezirk: 'Kirchdorf an der Krems', bundesland: 'Oberösterreich', lat: 47.9064, lng: 14.1244 },
  { name: 'Mattighofen', website: 'https://www.mattighofen.at', plz: '5230', bezirk: 'Braunau am Inn', bundesland: 'Oberösterreich', lat: 48.1058, lng: 13.1478 },
  { name: 'Rohrbach-Berg', website: 'https://www.rohrbach-berg.at', plz: '4150', bezirk: 'Rohrbach', bundesland: 'Oberösterreich', lat: 48.5703, lng: 13.9939 },
  { name: 'Eferding', website: 'https://www.eferding.at', plz: '4070', bezirk: 'Eferding', bundesland: 'Oberösterreich', lat: 48.3089, lng: 13.9708 },
  { name: 'Gallneukirchen', website: 'https://www.gallneukirchen.at', plz: '4210', bezirk: 'Perg', bundesland: 'Oberösterreich', lat: 48.3531, lng: 14.4139 },
  { name: 'Thalheim bei Wels', website: 'https://www.thalheim.at', plz: '4600', bezirk: 'Wels-Land', bundesland: 'Oberösterreich', lat: 48.1500, lng: 14.0333 },
  { name: 'Bad Hall', website: 'https://www.badhall.at', plz: '4540', bezirk: 'Steyr-Land', bundesland: 'Oberösterreich', lat: 48.0375, lng: 14.2083 },
  { name: 'Kremsmünster', website: 'https://www.kremsmuenster.at', plz: '4550', bezirk: 'Kirchdorf an der Krems', bundesland: 'Oberösterreich', lat: 48.0539, lng: 14.1292 },
  { name: 'Asten', website: 'https://www.asten.at', plz: '4481', bezirk: 'Linz-Land', bundesland: 'Oberösterreich', lat: 48.2236, lng: 14.4139 },
  { name: 'Gunskirchen', website: 'https://www.gunskirchen.at', plz: '4623', bezirk: 'Wels-Land', bundesland: 'Oberösterreich', lat: 48.1333, lng: 13.9500 },
  { name: 'Regau', website: 'https://www.regau.at', plz: '4844', bezirk: 'Vöcklabruck', bundesland: 'Oberösterreich', lat: 47.9833, lng: 13.6833 },
  { name: 'Ebensee am Traunsee', website: 'https://www.ebensee.at', plz: '4802', bezirk: 'Gmunden', bundesland: 'Oberösterreich', lat: 47.8069, lng: 13.7792 },
  { name: 'Ottensheim', website: 'https://www.ottensheim.at', plz: '4100', bezirk: 'Urfahr-Umgebung', bundesland: 'Oberösterreich', lat: 48.3333, lng: 14.1833 },
  { name: 'Gaspoltshofen', website: 'https://www.gaspoltshofen.at', plz: '4673', bezirk: 'Grieskirchen', bundesland: 'Oberösterreich', lat: 48.0833, lng: 13.7667 },
  { name: 'Bad Leonfelden', website: 'https://www.bad-leonfelden.at', plz: '4190', bezirk: 'Urfahr-Umgebung', bundesland: 'Oberösterreich', lat: 48.5167, lng: 14.2917 },
  { name: 'Micheldorf in Oberösterreich', website: 'https://www.micheldorf.at', plz: '4563', bezirk: 'Kirchdorf an der Krems', bundesland: 'Oberösterreich', lat: 47.8833, lng: 14.1333 },
  { name: 'Hörsching', website: 'https://www.hoersching.at', plz: '4063', bezirk: 'Linz-Land', bundesland: 'Oberösterreich', lat: 48.2333, lng: 14.1667 },
  { name: 'Pasching', website: 'https://www.pasching.at', plz: '4061', bezirk: 'Linz-Land', bundesland: 'Oberösterreich', lat: 48.2500, lng: 14.2083 },
  { name: 'Neuhofen an der Krems', website: 'https://www.neuhofen.at', plz: '4501', bezirk: 'Linz-Land', bundesland: 'Oberösterreich', lat: 48.1333, lng: 14.2167 },
  { name: 'Mondsee', website: 'https://www.mondsee.at', plz: '5310', bezirk: 'Vöcklabruck', bundesland: 'Oberösterreich', lat: 47.8539, lng: 13.3483 },
  { name: 'Frankenmarkt', website: 'https://www.frankenmarkt.at', plz: '4890', bezirk: 'Vöcklabruck', bundesland: 'Oberösterreich', lat: 47.9833, lng: 13.4167 },
  { name: 'Peuerbach', website: 'https://www.peuerbach.at', plz: '4722', bezirk: 'Grieskirchen', bundesland: 'Oberösterreich', lat: 48.3333, lng: 13.7667 },
];

// ─── STEIERMARK ──────────────────────────────────────────────────────────────
const STEIERMARK: GemeindeInfo[] = [
  { name: 'Graz', website: 'https://www.graz.at', plz: '8010', bezirk: 'Graz (Stadt)', bundesland: 'Steiermark', lat: 47.0707, lng: 15.4395 },
  { name: 'Leoben', website: 'https://www.leoben.at', plz: '8700', bezirk: 'Leoben', bundesland: 'Steiermark', lat: 47.3817, lng: 15.0972 },
  { name: 'Kapfenberg', website: 'https://www.kapfenberg.at', plz: '8605', bezirk: 'Bruck-Mürzzuschlag', bundesland: 'Steiermark', lat: 47.4444, lng: 15.2939 },
  { name: 'Leibnitz', website: 'https://www.leibnitz.at', plz: '8430', bezirk: 'Leibnitz', bundesland: 'Steiermark', lat: 46.7808, lng: 15.5358 },
  { name: 'Feldbach', website: 'https://www.feldbach.gv.at', plz: '8330', bezirk: 'Südoststeiermark', bundesland: 'Steiermark', lat: 46.9528, lng: 15.8886 },
  { name: 'Knittelfeld', website: 'https://www.knittelfeld.at', plz: '8720', bezirk: 'Murtal', bundesland: 'Steiermark', lat: 47.2167, lng: 14.8167 },
  { name: 'Gratwein-Straßengel', website: 'https://www.gratwein-strassengel.gv.at', plz: '8112', bezirk: 'Graz-Umgebung', bundesland: 'Steiermark', lat: 47.1239, lng: 15.3189 },
  { name: 'Seiersberg-Pirka', website: 'https://www.seiersberg-pirka.at', plz: '8054', bezirk: 'Graz-Umgebung', bundesland: 'Steiermark', lat: 47.0250, lng: 15.4083 },
  { name: 'Weiz', website: 'https://www.weiz.at', plz: '8160', bezirk: 'Weiz', bundesland: 'Steiermark', lat: 47.2167, lng: 15.6250 },
  { name: 'Deutschlandsberg', website: 'https://www.deutschlandsberg.at', plz: '8530', bezirk: 'Deutschlandsberg', bundesland: 'Steiermark', lat: 46.8167, lng: 15.2167 },
  { name: 'Gleisdorf', website: 'https://www.gleisdorf.at', plz: '8200', bezirk: 'Weiz', bundesland: 'Steiermark', lat: 47.1019, lng: 15.7108 },
  { name: 'Trofaiach', website: 'https://www.trofaiach.at', plz: '8793', bezirk: 'Leoben', bundesland: 'Steiermark', lat: 47.4261, lng: 15.0097 },
  { name: 'Köflach', website: 'https://www.koeflach.at', plz: '8580', bezirk: 'Voitsberg', bundesland: 'Steiermark', lat: 47.0667, lng: 15.0833 },
  { name: 'Voitsberg', website: 'https://www.voitsberg.at', plz: '8570', bezirk: 'Voitsberg', bundesland: 'Steiermark', lat: 47.0500, lng: 15.1500 },
  { name: 'Bruck an der Mur', website: 'https://www.bruckmur.at', plz: '8600', bezirk: 'Bruck-Mürzzuschlag', bundesland: 'Steiermark', lat: 47.4108, lng: 15.2722 },
  { name: 'Mürzzuschlag', website: 'https://www.muerzzuschlag.at', plz: '8680', bezirk: 'Bruck-Mürzzuschlag', bundesland: 'Steiermark', lat: 47.6069, lng: 15.6731 },
  { name: 'Judenburg', website: 'https://www.judenburg.at', plz: '8750', bezirk: 'Murtal', bundesland: 'Steiermark', lat: 47.1667, lng: 14.6667 },
  { name: 'Hartberg', website: 'https://www.hartberg.at', plz: '8230', bezirk: 'Hartberg-Fürstenfeld', bundesland: 'Steiermark', lat: 47.2822, lng: 15.9664 },
  { name: 'Fürstenfeld', website: 'https://www.fuerstenfeld.gv.at', plz: '8280', bezirk: 'Hartberg-Fürstenfeld', bundesland: 'Steiermark', lat: 47.0500, lng: 16.0833 },
  { name: 'Murau', website: 'https://www.murau.gv.at', plz: '8850', bezirk: 'Murau', bundesland: 'Steiermark', lat: 47.1117, lng: 14.1722 },
  { name: 'Liezen', website: 'https://www.liezen.at', plz: '8940', bezirk: 'Liezen', bundesland: 'Steiermark', lat: 47.5667, lng: 14.2333 },
  { name: 'Schladming', website: 'https://www.schladming.at', plz: '8970', bezirk: 'Liezen', bundesland: 'Steiermark', lat: 47.3939, lng: 13.6897 },
  { name: 'Bärnbach', website: 'https://www.baernbach.at', plz: '8572', bezirk: 'Voitsberg', bundesland: 'Steiermark', lat: 47.0667, lng: 15.1167 },
  { name: 'Kindberg', website: 'https://www.kindberg.at', plz: '8650', bezirk: 'Bruck-Mürzzuschlag', bundesland: 'Steiermark', lat: 47.5000, lng: 15.4500 },
  { name: 'Gratkorn', website: 'https://www.gratkorn.gv.at', plz: '8101', bezirk: 'Graz-Umgebung', bundesland: 'Steiermark', lat: 47.1333, lng: 15.3500 },
  { name: 'Kalsdorf bei Graz', website: 'https://www.kalsdorf-graz.at', plz: '8401', bezirk: 'Graz-Umgebung', bundesland: 'Steiermark', lat: 46.9694, lng: 15.4806 },
  { name: 'Fehring', website: 'https://www.fehring.at', plz: '8350', bezirk: 'Südoststeiermark', bundesland: 'Steiermark', lat: 46.9333, lng: 15.9833 },
  { name: 'Premstätten', website: 'https://www.premstaetten.gv.at', plz: '8141', bezirk: 'Graz-Umgebung', bundesland: 'Steiermark', lat: 46.9833, lng: 15.4000 },
  { name: 'Fohnsdorf', website: 'https://www.fohnsdorf.at', plz: '8753', bezirk: 'Murtal', bundesland: 'Steiermark', lat: 47.2000, lng: 14.6833 },
  { name: 'Zeltweg', website: 'https://www.zeltweg.at', plz: '8740', bezirk: 'Murtal', bundesland: 'Steiermark', lat: 47.1833, lng: 14.7500 },
  { name: 'Spielberg', website: 'https://www.spielberg.at', plz: '8724', bezirk: 'Murtal', bundesland: 'Steiermark', lat: 47.2167, lng: 14.7833 },
  { name: 'Rottenmann', website: 'https://www.rottenmann.at', plz: '8786', bezirk: 'Liezen', bundesland: 'Steiermark', lat: 47.5286, lng: 14.3572 },
  { name: 'Bad Radkersburg', website: 'https://www.bad-radkersburg.gv.at', plz: '8490', bezirk: 'Südoststeiermark', bundesland: 'Steiermark', lat: 46.6883, lng: 15.9886 },
  { name: 'Krieglach', website: 'https://www.krieglach.at', plz: '8670', bezirk: 'Bruck-Mürzzuschlag', bundesland: 'Steiermark', lat: 47.5500, lng: 15.5667 },
  { name: 'Stainz', website: 'https://www.stainz.at', plz: '8510', bezirk: 'Deutschlandsberg', bundesland: 'Steiermark', lat: 46.8939, lng: 15.2628 },
  { name: 'Pischelsdorf am Kulm', website: 'https://www.pischelsdorf.at', plz: '8212', bezirk: 'Weiz', bundesland: 'Steiermark', lat: 47.1750, lng: 15.7750 },
  { name: 'Wagna', website: 'https://www.wagna.at', plz: '8435', bezirk: 'Leibnitz', bundesland: 'Steiermark', lat: 46.7667, lng: 15.5667 },
  { name: 'Frohnleiten', website: 'https://www.frohnleiten.com', plz: '8130', bezirk: 'Graz-Umgebung', bundesland: 'Steiermark', lat: 47.2667, lng: 15.3167 },
  { name: 'Niklasdorf', website: 'https://www.niklasdorf.at', plz: '8712', bezirk: 'Leoben', bundesland: 'Steiermark', lat: 47.3833, lng: 15.1500 },
  { name: 'Kumberg', website: 'https://www.kumberg.at', plz: '8062', bezirk: 'Graz-Umgebung', bundesland: 'Steiermark', lat: 47.1500, lng: 15.5167 },
  { name: 'Kainbach bei Graz', website: 'https://www.kainbach.at', plz: '8010', bezirk: 'Graz-Umgebung', bundesland: 'Steiermark', lat: 47.0833, lng: 15.5167 },
];

// ─── SALZBURG ────────────────────────────────────────────────────────────────
const SALZBURG: GemeindeInfo[] = [
  { name: 'Salzburg', website: 'https://www.stadt-salzburg.at', plz: '5020', bezirk: 'Salzburg (Stadt)', bundesland: 'Salzburg', lat: 47.8095, lng: 13.0550 },
  { name: 'Hallein', website: 'https://www.hallein.com', plz: '5400', bezirk: 'Hallein', bundesland: 'Salzburg', lat: 47.6833, lng: 13.1000 },
  { name: 'Saalfelden am Steinernen Meer', website: 'https://www.saalfelden.at', plz: '5760', bezirk: 'Zell am See', bundesland: 'Salzburg', lat: 47.4264, lng: 12.8481 },
  { name: 'Wals-Siezenheim', website: 'https://www.wals-siezenheim.at', plz: '5071', bezirk: 'Salzburg-Umgebung', bundesland: 'Salzburg', lat: 47.7833, lng: 13.0000 },
  { name: 'Seekirchen am Wallersee', website: 'https://www.seekirchen.at', plz: '5201', bezirk: 'Salzburg-Umgebung', bundesland: 'Salzburg', lat: 47.8944, lng: 13.1367 },
  { name: 'St. Johann im Pongau', website: 'https://www.stjohann.at', plz: '5600', bezirk: 'St. Johann im Pongau', bundesland: 'Salzburg', lat: 47.3500, lng: 13.2000 },
  { name: 'Bischofshofen', website: 'https://www.bischofshofen.at', plz: '5500', bezirk: 'St. Johann im Pongau', bundesland: 'Salzburg', lat: 47.4167, lng: 13.2167 },
  { name: 'Zell am See', website: 'https://www.zellamsee.at', plz: '5700', bezirk: 'Zell am See', bundesland: 'Salzburg', lat: 47.3231, lng: 12.7978 },
  { name: 'Straßwalchen', website: 'https://www.strasswalchen.at', plz: '5204', bezirk: 'Salzburg-Umgebung', bundesland: 'Salzburg', lat: 47.9833, lng: 13.2500 },
  { name: 'Kuchl', website: 'https://www.kuchl.net', plz: '5431', bezirk: 'Hallein', bundesland: 'Salzburg', lat: 47.6333, lng: 13.1500 },
  { name: 'Grödig', website: 'https://www.groedig.at', plz: '5082', bezirk: 'Salzburg-Umgebung', bundesland: 'Salzburg', lat: 47.7500, lng: 13.0333 },
  { name: 'Bergheim', website: 'https://www.bergheim.at', plz: '5101', bezirk: 'Salzburg-Umgebung', bundesland: 'Salzburg', lat: 47.8333, lng: 13.0333 },
  { name: 'Mittersill', website: 'https://www.mittersill.at', plz: '5730', bezirk: 'Zell am See', bundesland: 'Salzburg', lat: 47.2833, lng: 12.4833 },
  { name: 'Radstadt', website: 'https://www.radstadt.at', plz: '5550', bezirk: 'St. Johann im Pongau', bundesland: 'Salzburg', lat: 47.3833, lng: 13.4583 },
  { name: 'Neumarkt am Wallersee', website: 'https://www.neumarkt.at', plz: '5202', bezirk: 'Salzburg-Umgebung', bundesland: 'Salzburg', lat: 47.9500, lng: 13.2333 },
  { name: 'Oberndorf bei Salzburg', website: 'https://www.oberndorf.at', plz: '5110', bezirk: 'Salzburg-Umgebung', bundesland: 'Salzburg', lat: 47.9500, lng: 12.9333 },
  { name: 'Tamsweg', website: 'https://www.tamsweg.at', plz: '5580', bezirk: 'Tamsweg', bundesland: 'Salzburg', lat: 47.1267, lng: 13.8117 },
];

// ─── TIROL ───────────────────────────────────────────────────────────────────
const TIROL: GemeindeInfo[] = [
  { name: 'Innsbruck', website: 'https://www.innsbruck.gv.at', plz: '6020', bezirk: 'Innsbruck (Stadt)', bundesland: 'Tirol', lat: 47.2654, lng: 11.3927 },
  { name: 'Kufstein', website: 'https://www.kufstein.at', plz: '6330', bezirk: 'Kufstein', bundesland: 'Tirol', lat: 47.5833, lng: 12.1667 },
  { name: 'Telfs', website: 'https://www.telfs.at', plz: '6410', bezirk: 'Innsbruck-Land', bundesland: 'Tirol', lat: 47.3097, lng: 11.0708 },
  { name: 'Hall in Tirol', website: 'https://www.hall-in-tirol.at', plz: '6060', bezirk: 'Innsbruck-Land', bundesland: 'Tirol', lat: 47.2833, lng: 11.5083 },
  { name: 'Schwaz', website: 'https://www.schwaz.at', plz: '6130', bezirk: 'Schwaz', bundesland: 'Tirol', lat: 47.3497, lng: 11.7103 },
  { name: 'Wörgl', website: 'https://www.woergl.at', plz: '6300', bezirk: 'Kufstein', bundesland: 'Tirol', lat: 47.4833, lng: 12.0667 },
  { name: 'Lienz', website: 'https://www.lienz.gv.at', plz: '9900', bezirk: 'Lienz', bundesland: 'Tirol', lat: 46.8297, lng: 12.7697 },
  { name: 'Imst', website: 'https://www.imst.at', plz: '6460', bezirk: 'Imst', bundesland: 'Tirol', lat: 47.2450, lng: 10.7397 },
  { name: 'St. Johann in Tirol', website: 'https://www.stjohann.tirol.gv.at', plz: '6380', bezirk: 'Kitzbühel', bundesland: 'Tirol', lat: 47.5242, lng: 12.4244 },
  { name: 'Rum', website: 'https://www.rum.gv.at', plz: '6063', bezirk: 'Innsbruck-Land', bundesland: 'Tirol', lat: 47.2833, lng: 11.4583 },
  { name: 'Völs', website: 'https://www.voels.at', plz: '6176', bezirk: 'Innsbruck-Land', bundesland: 'Tirol', lat: 47.2581, lng: 11.2211 },
  { name: 'Zirl', website: 'https://www.zirl.at', plz: '6170', bezirk: 'Innsbruck-Land', bundesland: 'Tirol', lat: 47.2697, lng: 11.2394 },
  { name: 'Kitzbühel', website: 'https://www.kitzbuehel.at', plz: '6370', bezirk: 'Kitzbühel', bundesland: 'Tirol', lat: 47.4467, lng: 12.3917 },
  { name: 'Absam', website: 'https://www.absam.at', plz: '6067', bezirk: 'Innsbruck-Land', bundesland: 'Tirol', lat: 47.2975, lng: 11.5067 },
  { name: 'Wattens', website: 'https://www.wattens.at', plz: '6112', bezirk: 'Innsbruck-Land', bundesland: 'Tirol', lat: 47.2914, lng: 11.5878 },
  { name: 'Landeck', website: 'https://www.landeck.tirol.gv.at', plz: '6500', bezirk: 'Landeck', bundesland: 'Tirol', lat: 47.1397, lng: 10.5667 },
  { name: 'Reutte', website: 'https://www.reutte.at', plz: '6600', bezirk: 'Reutte', bundesland: 'Tirol', lat: 47.4833, lng: 10.7167 },
  { name: 'Jenbach', website: 'https://www.jenbach.at', plz: '6200', bezirk: 'Schwaz', bundesland: 'Tirol', lat: 47.3917, lng: 11.7750 },
  { name: 'Kematen in Tirol', website: 'https://www.kematen.at', plz: '6175', bezirk: 'Innsbruck-Land', bundesland: 'Tirol', lat: 47.2558, lng: 11.2628 },
  { name: 'Axams', website: 'https://www.axams.at', plz: '6094', bezirk: 'Innsbruck-Land', bundesland: 'Tirol', lat: 47.2306, lng: 11.2783 },
  { name: 'Kirchbichl', website: 'https://www.kirchbichl.at', plz: '6322', bezirk: 'Kufstein', bundesland: 'Tirol', lat: 47.5167, lng: 12.0833 },
  { name: 'Kundl', website: 'https://www.kundl.tirol.gv.at', plz: '6250', bezirk: 'Kufstein', bundesland: 'Tirol', lat: 47.4650, lng: 11.9983 },
  { name: 'Mayrhofen', website: 'https://www.mayrhofen.at', plz: '6290', bezirk: 'Schwaz', bundesland: 'Tirol', lat: 47.1667, lng: 11.8625 },
  { name: 'Seefeld in Tirol', website: 'https://www.seefeld.at', plz: '6100', bezirk: 'Innsbruck-Land', bundesland: 'Tirol', lat: 47.3297, lng: 11.1886 },
  { name: 'Fügen', website: 'https://www.fuegen.at', plz: '6263', bezirk: 'Schwaz', bundesland: 'Tirol', lat: 47.3500, lng: 11.8500 },
  { name: 'Vomp', website: 'https://www.vomp.at', plz: '6134', bezirk: 'Schwaz', bundesland: 'Tirol', lat: 47.3500, lng: 11.7000 },
  { name: 'Mils', website: 'https://www.mils.at', plz: '6068', bezirk: 'Innsbruck-Land', bundesland: 'Tirol', lat: 47.2833, lng: 11.5333 },
  { name: 'Matrei am Brenner', website: 'https://www.matrei-brenner.at', plz: '6143', bezirk: 'Innsbruck-Land', bundesland: 'Tirol', lat: 47.1167, lng: 11.4500 },
  { name: 'Thaur', website: 'https://www.thaur.at', plz: '6065', bezirk: 'Innsbruck-Land', bundesland: 'Tirol', lat: 47.2889, lng: 11.4694 },
  { name: 'Ebbs', website: 'https://www.ebbs.at', plz: '6341', bezirk: 'Kufstein', bundesland: 'Tirol', lat: 47.6333, lng: 12.2167 },
  { name: 'Söll', website: 'https://www.soell.at', plz: '6306', bezirk: 'Kufstein', bundesland: 'Tirol', lat: 47.5069, lng: 12.1917 },
];

// ─── KÄRNTEN ─────────────────────────────────────────────────────────────────
const KAERNTEN: GemeindeInfo[] = [
  { name: 'Klagenfurt am Wörthersee', website: 'https://www.klagenfurt.at', plz: '9020', bezirk: 'Klagenfurt (Stadt)', bundesland: 'Kärnten', lat: 46.6249, lng: 14.3050 },
  { name: 'Villach', website: 'https://www.villach.at', plz: '9500', bezirk: 'Villach (Stadt)', bundesland: 'Kärnten', lat: 46.6111, lng: 13.8558 },
  { name: 'Wolfsberg', website: 'https://www.wolfsberg.at', plz: '9400', bezirk: 'Wolfsberg', bundesland: 'Kärnten', lat: 46.8417, lng: 14.8417 },
  { name: 'Spittal an der Drau', website: 'https://www.spittal-drau.at', plz: '9800', bezirk: 'Spittal an der Drau', bundesland: 'Kärnten', lat: 46.7972, lng: 13.4964 },
  { name: 'Feldkirchen in Kärnten', website: 'https://www.feldkirchen.at', plz: '9560', bezirk: 'Feldkirchen', bundesland: 'Kärnten', lat: 46.7233, lng: 14.0942 },
  { name: 'St. Veit an der Glan', website: 'https://www.stveit.at', plz: '9300', bezirk: 'St. Veit an der Glan', bundesland: 'Kärnten', lat: 46.7667, lng: 14.3583 },
  { name: 'Völkermarkt', website: 'https://www.voelkermarkt.at', plz: '9100', bezirk: 'Völkermarkt', bundesland: 'Kärnten', lat: 46.6603, lng: 14.6356 },
  { name: 'Hermagor-Pressegger See', website: 'https://www.hermagor.at', plz: '9620', bezirk: 'Hermagor', bundesland: 'Kärnten', lat: 46.6278, lng: 13.3703 },
  { name: 'St. Andrä', website: 'https://www.st-andrae.at', plz: '9433', bezirk: 'Wolfsberg', bundesland: 'Kärnten', lat: 46.7667, lng: 14.8167 },
  { name: 'Ferlach', website: 'https://www.ferlach.at', plz: '9170', bezirk: 'Klagenfurt-Land', bundesland: 'Kärnten', lat: 46.5233, lng: 14.3011 },
  { name: 'Althofen', website: 'https://www.althofen.at', plz: '9330', bezirk: 'St. Veit an der Glan', bundesland: 'Kärnten', lat: 46.8728, lng: 14.4736 },
  { name: 'Bleiburg', website: 'https://www.bleiburg.at', plz: '9150', bezirk: 'Völkermarkt', bundesland: 'Kärnten', lat: 46.5903, lng: 14.7969 },
  { name: 'Radenthein', website: 'https://www.radenthein.at', plz: '9545', bezirk: 'Spittal an der Drau', bundesland: 'Kärnten', lat: 46.7978, lng: 13.7178 },
  { name: 'Gmünd in Kärnten', website: 'https://www.gmuend-kaernten.at', plz: '9853', bezirk: 'Spittal an der Drau', bundesland: 'Kärnten', lat: 46.9069, lng: 13.5269 },
  { name: 'Friesach', website: 'https://www.friesach.at', plz: '9360', bezirk: 'St. Veit an der Glan', bundesland: 'Kärnten', lat: 46.9528, lng: 14.4058 },
  { name: 'Bad Kleinkirchheim', website: 'https://www.badkleinkirchheim.at', plz: '9546', bezirk: 'Spittal an der Drau', bundesland: 'Kärnten', lat: 46.8153, lng: 13.7833 },
  { name: 'Velden am Wörthersee', website: 'https://www.velden.gv.at', plz: '9220', bezirk: 'Villach-Land', bundesland: 'Kärnten', lat: 46.6167, lng: 14.0417 },
  { name: 'Maria Saal', website: 'https://www.maria-saal.gv.at', plz: '9063', bezirk: 'Klagenfurt-Land', bundesland: 'Kärnten', lat: 46.6833, lng: 14.3500 },
];

// ─── VORARLBERG ──────────────────────────────────────────────────────────────
const VORARLBERG: GemeindeInfo[] = [
  { name: 'Dornbirn', website: 'https://www.dornbirn.at', plz: '6850', bezirk: 'Dornbirn', bundesland: 'Vorarlberg', lat: 47.4125, lng: 9.7417 },
  { name: 'Feldkirch', website: 'https://www.feldkirch.at', plz: '6800', bezirk: 'Feldkirch', bundesland: 'Vorarlberg', lat: 47.2392, lng: 9.6006 },
  { name: 'Bregenz', website: 'https://www.bregenz.at', plz: '6900', bezirk: 'Bregenz', bundesland: 'Vorarlberg', lat: 47.5031, lng: 9.7471 },
  { name: 'Lustenau', website: 'https://www.lustenau.at', plz: '6890', bezirk: 'Dornbirn', bundesland: 'Vorarlberg', lat: 47.4264, lng: 9.6603 },
  { name: 'Hohenems', website: 'https://www.hohenems.at', plz: '6845', bezirk: 'Dornbirn', bundesland: 'Vorarlberg', lat: 47.3647, lng: 9.6853 },
  { name: 'Bludenz', website: 'https://www.bludenz.at', plz: '6700', bezirk: 'Bludenz', bundesland: 'Vorarlberg', lat: 47.1544, lng: 9.8222 },
  { name: 'Hard', website: 'https://www.hard.at', plz: '6971', bezirk: 'Bregenz', bundesland: 'Vorarlberg', lat: 47.4861, lng: 9.6903 },
  { name: 'Rankweil', website: 'https://www.rankweil.at', plz: '6830', bezirk: 'Feldkirch', bundesland: 'Vorarlberg', lat: 47.2694, lng: 9.6444 },
  { name: 'Götzis', website: 'https://www.goetzis.at', plz: '6840', bezirk: 'Feldkirch', bundesland: 'Vorarlberg', lat: 47.3331, lng: 9.6356 },
  { name: 'Lauterach', website: 'https://www.lauterach.at', plz: '6923', bezirk: 'Bregenz', bundesland: 'Vorarlberg', lat: 47.4781, lng: 9.7292 },
  { name: 'Höchst', website: 'https://www.hoechst.at', plz: '6973', bezirk: 'Bregenz', bundesland: 'Vorarlberg', lat: 47.4558, lng: 9.6375 },
  { name: 'Wolfurt', website: 'https://www.wolfurt.at', plz: '6922', bezirk: 'Bregenz', bundesland: 'Vorarlberg', lat: 47.4622, lng: 9.7500 },
  { name: 'Nenzing', website: 'https://www.nenzing.at', plz: '6710', bezirk: 'Bludenz', bundesland: 'Vorarlberg', lat: 47.1833, lng: 9.7000 },
  { name: 'Schwarzach', website: 'https://www.schwarzach.at', plz: '6858', bezirk: 'Bregenz', bundesland: 'Vorarlberg', lat: 47.4500, lng: 9.7583 },
  { name: 'Schruns', website: 'https://www.schruns.at', plz: '6780', bezirk: 'Bludenz', bundesland: 'Vorarlberg', lat: 47.0800, lng: 9.9200 },
];

// ─── BURGENLAND ──────────────────────────────────────────────────────────────
const BURGENLAND: GemeindeInfo[] = [
  { name: 'Eisenstadt', website: 'https://www.eisenstadt.gv.at', plz: '7000', bezirk: 'Eisenstadt (Stadt)', bundesland: 'Burgenland', lat: 47.8456, lng: 16.5189 },
  { name: 'Oberwart', website: 'https://www.oberwart.at', plz: '7400', bezirk: 'Oberwart', bundesland: 'Burgenland', lat: 47.2903, lng: 16.1986 },
  { name: 'Neusiedl am See', website: 'https://www.neusiedlamsee.at', plz: '7100', bezirk: 'Neusiedl am See', bundesland: 'Burgenland', lat: 47.9489, lng: 16.8436 },
  { name: 'Mattersburg', website: 'https://www.mattersburg.gv.at', plz: '7210', bezirk: 'Mattersburg', bundesland: 'Burgenland', lat: 47.7333, lng: 16.4000 },
  { name: 'Pinkafeld', website: 'https://www.pinkafeld.gv.at', plz: '7423', bezirk: 'Oberwart', bundesland: 'Burgenland', lat: 47.3733, lng: 16.1233 },
  { name: 'Oberpullendorf', website: 'https://www.oberpullendorf.gv.at', plz: '7350', bezirk: 'Oberpullendorf', bundesland: 'Burgenland', lat: 47.4969, lng: 16.5108 },
  { name: 'Güssing', website: 'https://www.guessing.at', plz: '7540', bezirk: 'Güssing', bundesland: 'Burgenland', lat: 47.0572, lng: 16.3217 },
  { name: 'Jennersdorf', website: 'https://www.jennersdorf.gv.at', plz: '8380', bezirk: 'Jennersdorf', bundesland: 'Burgenland', lat: 46.9381, lng: 16.1431 },
  { name: 'Großpetersdorf', website: 'https://www.grosspetersdorf.at', plz: '7503', bezirk: 'Oberwart', bundesland: 'Burgenland', lat: 47.2333, lng: 16.3667 },
  { name: 'Rust', website: 'https://www.rust.at', plz: '7071', bezirk: 'Rust (Stadt)', bundesland: 'Burgenland', lat: 47.8022, lng: 16.6711 },
  { name: 'Frauenkirchen', website: 'https://www.frauenkirchen.at', plz: '7132', bezirk: 'Neusiedl am See', bundesland: 'Burgenland', lat: 47.8389, lng: 16.9211 },
  { name: 'Parndorf', website: 'https://www.parndorf.at', plz: '7111', bezirk: 'Neusiedl am See', bundesland: 'Burgenland', lat: 47.9944, lng: 16.8578 },
  { name: 'Neufeld an der Leitha', website: 'https://www.neufeld-leitha.at', plz: '2491', bezirk: 'Eisenstadt-Umgebung', bundesland: 'Burgenland', lat: 47.8667, lng: 16.3667 },
  { name: 'Stegersbach', website: 'https://www.stegersbach.at', plz: '7551', bezirk: 'Güssing', bundesland: 'Burgenland', lat: 47.1608, lng: 16.1614 },
  { name: 'Deutschkreutz', website: 'https://www.deutschkreutz.at', plz: '7301', bezirk: 'Oberpullendorf', bundesland: 'Burgenland', lat: 47.6000, lng: 16.6333 },
  { name: 'Kittsee', website: 'https://www.kittsee.at', plz: '2421', bezirk: 'Neusiedl am See', bundesland: 'Burgenland', lat: 48.0903, lng: 17.0614 },
  { name: 'Gols', website: 'https://www.gols.at', plz: '7122', bezirk: 'Neusiedl am See', bundesland: 'Burgenland', lat: 47.8939, lng: 16.9058 },
  { name: 'Stadtschlaining', website: 'https://www.stadtschlaining.at', plz: '7461', bezirk: 'Oberwart', bundesland: 'Burgenland', lat: 47.3214, lng: 16.2808 },
  { name: 'Purbach am Neusiedler See', website: 'https://www.purbach.at', plz: '7083', bezirk: 'Eisenstadt-Umgebung', bundesland: 'Burgenland', lat: 47.9131, lng: 16.6936 },
  { name: 'Bruckneudorf', website: 'https://www.bruckneudorf.at', plz: '2460', bezirk: 'Neusiedl am See', bundesland: 'Burgenland', lat: 48.0167, lng: 16.7833 },
  { name: 'Neudörfl', website: 'https://www.neudoerfl.at', plz: '7201', bezirk: 'Mattersburg', bundesland: 'Burgenland', lat: 47.7000, lng: 16.3167 },
  { name: 'Bad Sauerbrunn', website: 'https://www.bad-sauerbrunn.at', plz: '7202', bezirk: 'Mattersburg', bundesland: 'Burgenland', lat: 47.7667, lng: 16.3500 },
  { name: 'Rechnitz', website: 'https://www.rechnitz.at', plz: '7471', bezirk: 'Oberwart', bundesland: 'Burgenland', lat: 47.3056, lng: 16.4389 },
  { name: 'Siegendorf', website: 'https://www.siegendorf.at', plz: '7011', bezirk: 'Eisenstadt-Umgebung', bundesland: 'Burgenland', lat: 47.7833, lng: 16.5333 },
  { name: 'Hornstein', website: 'https://www.hornstein.at', plz: '7053', bezirk: 'Eisenstadt-Umgebung', bundesland: 'Burgenland', lat: 47.8811, lng: 16.4447 },
  { name: 'Bad Tatzmannsdorf', website: 'https://www.bad-tatzmannsdorf.at', plz: '7431', bezirk: 'Oberwart', bundesland: 'Burgenland', lat: 47.3333, lng: 16.2167 },
  { name: 'Illmitz', website: 'https://www.illmitz.at', plz: '7142', bezirk: 'Neusiedl am See', bundesland: 'Burgenland', lat: 47.7681, lng: 16.8028 },
  { name: 'Pöttsching', website: 'https://www.poettsching.at', plz: '7033', bezirk: 'Mattersburg', bundesland: 'Burgenland', lat: 47.7833, lng: 16.3667 },
  { name: 'Steinbrunn', website: 'https://www.steinbrunn.at', plz: '7035', bezirk: 'Eisenstadt-Umgebung', bundesland: 'Burgenland', lat: 47.8167, lng: 16.4167 },
  { name: 'Lockenhaus', website: 'https://www.lockenhaus.at', plz: '7442', bezirk: 'Oberpullendorf', bundesland: 'Burgenland', lat: 47.4083, lng: 16.4250 },
  { name: 'Wallern im Burgenland', website: 'https://www.wallern.at', plz: '7151', bezirk: 'Neusiedl am See', bundesland: 'Burgenland', lat: 47.7333, lng: 16.9333 },
  { name: 'Mörbisch am See', website: 'https://www.moerbisch.at', plz: '7072', bezirk: 'Eisenstadt-Umgebung', bundesland: 'Burgenland', lat: 47.7542, lng: 16.6889 },
];

// ─── GESAMTLISTE ─────────────────────────────────────────────────────────────
export const GEMEINDEN: GemeindeInfo[] = [
  ...WIEN,
  ...NIEDEROESTERREICH,
  ...OBEROESTERREICH,
  ...STEIERMARK,
  ...SALZBURG,
  ...TIROL,
  ...KAERNTEN,
  ...VORARLBERG,
  ...BURGENLAND,
];
