/**
 * Liste der ~300 größten österreichischen Gemeinden mit Website-URLs.
 * Sortiert nach Bundesland, dann nach Einwohnerzahl (absteigend).
 *
 * Quellen:
 * - Statistik Austria Gemeindeverzeichnis
 * - citypopulation.de/de/austria
 * - Gemeinde-Websites verifiziert über gängige URL-Muster
 */

export interface GemeindeInfo {
  name: string;
  website: string;
  plz: string;
  bezirk: string;
  bundesland: string;
  lat: number;
  lng: number;
}

// ─── WIEN ────────────────────────────────────────────────────────────────────
// Wien wird als Einzelgemeinde geführt (Bezirke sind keine eigenen Gemeinden)
const WIEN: GemeindeInfo[] = [
  { name: 'Wien', website: 'https://www.wien.gv.at', plz: '1010', bezirk: 'Wien', bundesland: 'Wien', lat: 48.2082, lng: 16.3738 },
];

// ─── NIEDERÖSTERREICH ────────────────────────────────────────────────────────
const NIEDEROESTERREICH: GemeindeInfo[] = [
  { name: 'St. Pölten', website: 'https://www.st-poelten.at', plz: '3100', bezirk: 'St. Pölten (Stadt)', bundesland: 'Niederösterreich', lat: 48.2043, lng: 15.6229 },
  { name: 'Wiener Neustadt', website: 'https://www.wiener-neustadt.at', plz: '2700', bezirk: 'Wiener Neustadt (Stadt)', bundesland: 'Niederösterreich', lat: 47.8132, lng: 16.2441 },
  { name: 'Klosterneuburg', website: 'https://www.klosterneuburg.at', plz: '3400', bezirk: 'Tulln', bundesland: 'Niederösterreich', lat: 48.305, lng: 16.3238 },
  { name: 'Baden', website: 'https://www.baden.at', plz: '2500', bezirk: 'Baden', bundesland: 'Niederösterreich', lat: 48.0077, lng: 16.2344 },
  { name: 'Krems an der Donau', website: 'https://www.krems.at', plz: '3500', bezirk: 'Krems an der Donau (Stadt)', bundesland: 'Niederösterreich', lat: 48.4108, lng: 15.6004 },
  { name: 'Amstetten', website: 'https://www.amstetten.at', plz: '3300', bezirk: 'Amstetten', bundesland: 'Niederösterreich', lat: 48.1203, lng: 14.8752 },
  { name: 'Schwechat', website: 'https://www.schwechat.gv.at', plz: '2320', bezirk: 'Bruck an der Leitha', bundesland: 'Niederösterreich', lat: 48.1397, lng: 16.478 },
  { name: 'Mödling', website: 'https://www.moedling.at', plz: '2340', bezirk: 'Mödling', bundesland: 'Niederösterreich', lat: 48.0856, lng: 16.2834 },
  { name: 'Traiskirchen', website: 'https://www.traiskirchen.gv.at', plz: '2514', bezirk: 'Baden', bundesland: 'Niederösterreich', lat: 48.0139, lng: 16.2952 },
  { name: 'Stockerau', website: 'https://www.stockerau.at', plz: '2000', bezirk: 'Korneuburg', bundesland: 'Niederösterreich', lat: 48.3846, lng: 16.2076 },
  { name: 'Tulln an der Donau', website: 'https://www.tulln.at', plz: '3430', bezirk: 'Tulln', bundesland: 'Niederösterreich', lat: 48.3312, lng: 16.0518 },
  { name: 'Perchtoldsdorf', website: 'https://www.perchtoldsdorf.at', plz: '2380', bezirk: 'Mödling', bundesland: 'Niederösterreich', lat: 48.1189, lng: 16.2661 },
  { name: 'Ternitz', website: 'https://www.ternitz.at', plz: '2630', bezirk: 'Neunkirchen', bundesland: 'Niederösterreich', lat: 47.7066, lng: 16.0195 },
  { name: 'Korneuburg', website: 'https://www.korneuburg.gv.at', plz: '2100', bezirk: 'Korneuburg', bundesland: 'Niederösterreich', lat: 48.3441, lng: 16.3334 },
  { name: 'Neunkirchen', website: 'https://www.neunkirchen.gv.at', plz: '2620', bezirk: 'Neunkirchen', bundesland: 'Niederösterreich', lat: 47.7221, lng: 16.0816 },
  { name: 'Hollabrunn', website: 'https://www.hollabrunn.gv.at', plz: '2020', bezirk: 'Hollabrunn', bundesland: 'Niederösterreich', lat: 48.5625, lng: 16.0798 },
  { name: 'Bad Vöslau', website: 'https://www.badvoeslau.at', plz: '2540', bezirk: 'Baden', bundesland: 'Niederösterreich', lat: 47.9656, lng: 16.2148 },
  { name: 'Gänserndorf', website: 'https://www.gaenserndorf.at', plz: '2230', bezirk: 'Gänserndorf', bundesland: 'Niederösterreich', lat: 48.3404, lng: 16.7187 },
  { name: 'Strasshof an der Nordbahn', website: 'https://www.strasshof.at', plz: '2231', bezirk: 'Gänserndorf', bundesland: 'Niederösterreich', lat: 48.3189, lng: 16.6429 },
  { name: 'Brunn am Gebirge', website: 'https://www.brunn.at', plz: '2345', bezirk: 'Mödling', bundesland: 'Niederösterreich', lat: 48.1071, lng: 16.2837 },
  { name: 'Gerasdorf bei Wien', website: 'https://www.gerasdorf.at', plz: '2201', bezirk: 'Korneuburg', bundesland: 'Niederösterreich', lat: 48.2953, lng: 16.4672 },
  { name: 'Groß-Enzersdorf', website: 'https://www.gross-enzersdorf.gv.at', plz: '2301', bezirk: 'Gänserndorf', bundesland: 'Niederösterreich', lat: 48.2018, lng: 16.552 },
  { name: 'Ebreichsdorf', website: 'https://www.ebreichsdorf.at', plz: '2483', bezirk: 'Baden', bundesland: 'Niederösterreich', lat: 47.9626, lng: 16.4024 },
  { name: 'Mistelbach', website: 'https://www.mistelbach.at', plz: '2130', bezirk: 'Mistelbach', bundesland: 'Niederösterreich', lat: 48.5695, lng: 16.572 },
  { name: 'Waidhofen an der Ybbs', website: 'https://www.waidhofen.at', plz: '3340', bezirk: 'Waidhofen an der Ybbs (Stadt)', bundesland: 'Niederösterreich', lat: 47.961, lng: 14.7747 },
  { name: 'Zwettl', website: 'https://www.zwettl.gv.at', plz: '3910', bezirk: 'Zwettl', bundesland: 'Niederösterreich', lat: 48.6047, lng: 15.1689 },
  { name: 'Purkersdorf', website: 'https://www.purkersdorf.at', plz: '3002', bezirk: 'St. Pölten-Land', bundesland: 'Niederösterreich', lat: 48.2069, lng: 16.1769 },
  { name: 'Bruck an der Leitha', website: 'https://www.bruckleitha.at', plz: '2460', bezirk: 'Bruck an der Leitha', bundesland: 'Niederösterreich', lat: 48.0256, lng: 16.7789 },
  { name: 'Wieselburg', website: 'https://www.wieselburg.gv.at', plz: '3250', bezirk: 'Scheibbs', bundesland: 'Niederösterreich', lat: 48.1306, lng: 15.1369 },
  { name: 'Melk', website: 'https://www.stadt-melk.at', plz: '3390', bezirk: 'Melk', bundesland: 'Niederösterreich', lat: 48.2272, lng: 15.337 },
  { name: 'Wolkersdorf im Weinviertel', website: 'https://www.wolkersdorf.at', plz: '2120', bezirk: 'Mistelbach', bundesland: 'Niederösterreich', lat: 48.383, lng: 16.5181 },
  { name: 'Herzogenburg', website: 'https://www.herzogenburg.at', plz: '3130', bezirk: 'St. Pölten-Land', bundesland: 'Niederösterreich', lat: 48.2843, lng: 15.6946 },
  { name: 'Scheibbs', website: 'https://www.scheibbs.gv.at', plz: '3270', bezirk: 'Scheibbs', bundesland: 'Niederösterreich', lat: 48.0054, lng: 15.1675 },
  { name: 'Gmünd', website: 'https://www.gmuend.at', plz: '3950', bezirk: 'Gmünd', bundesland: 'Niederösterreich', lat: 48.7729, lng: 14.9862 },
  { name: 'Berndorf', website: 'https://www.berndorf.gv.at', plz: '2560', bezirk: 'Baden', bundesland: 'Niederösterreich', lat: 47.9456, lng: 16.1094 },
  { name: 'Haag', website: 'https://www.haag.at', plz: '3350', bezirk: 'Amstetten', bundesland: 'Niederösterreich', lat: 48.1119, lng: 14.5661 },
  { name: 'Lilienfeld', website: 'https://www.lilienfeld.at', plz: '3180', bezirk: 'Lilienfeld', bundesland: 'Niederösterreich', lat: 48.015, lng: 15.5966 },
  { name: 'Heidenreichstein', website: 'https://www.heidenreichstein.at', plz: '3860', bezirk: 'Gmünd', bundesland: 'Niederösterreich', lat: 48.8658, lng: 15.123 },
  { name: 'Fischamend', website: 'https://www.fischamend.gv.at', plz: '2401', bezirk: 'Bruck an der Leitha', bundesland: 'Niederösterreich', lat: 48.1186, lng: 16.6113 },
  { name: 'Deutsch-Wagram', website: 'https://www.deutsch-wagram.at', plz: '2232', bezirk: 'Gänserndorf', bundesland: 'Niederösterreich', lat: 48.296, lng: 16.5568 },
  { name: 'Leobersdorf', website: 'https://www.leobersdorf.at', plz: '2544', bezirk: 'Baden', bundesland: 'Niederösterreich', lat: 47.9285, lng: 16.2167 },
  { name: 'Wöllersdorf-Steinabrückl', website: 'https://www.woellersdorf-steinabrueckl.at', plz: '2752', bezirk: 'Wiener Neustadt-Land', bundesland: 'Niederösterreich', lat: 47.8653, lng: 16.1719 },
  { name: 'Pressbaum', website: 'https://www.pressbaum.at', plz: '3021', bezirk: 'St. Pölten-Land', bundesland: 'Niederösterreich', lat: 48.1792, lng: 16.0771 },
  { name: 'Himberg', website: 'https://www.himberg.at', plz: '2325', bezirk: 'Bruck an der Leitha', bundesland: 'Niederösterreich', lat: 48.082, lng: 16.4398 },
  { name: 'Pottendorf', website: 'https://www.pottendorf.at', plz: '2486', bezirk: 'Baden', bundesland: 'Niederösterreich', lat: 47.9101, lng: 16.3875 },
  { name: 'Zwettl-Niederösterreich', website: 'https://www.zwettl.gv.at', plz: '3910', bezirk: 'Zwettl', bundesland: 'Niederösterreich', lat: 48.6047, lng: 15.1689 },
  { name: 'Guntramsdorf', website: 'https://www.guntramsdorf.at', plz: '2353', bezirk: 'Mödling', bundesland: 'Niederösterreich', lat: 48.0486, lng: 16.3132 },
  { name: 'Vösendorf', website: 'https://www.voesendorf.gv.at', plz: '2331', bezirk: 'Mödling', bundesland: 'Niederösterreich', lat: 48.1216, lng: 16.3371 },
  { name: 'Ybbs an der Donau', website: 'https://www.ybbs.at', plz: '3370', bezirk: 'Melk', bundesland: 'Niederösterreich', lat: 48.1772, lng: 15.0853 },
  { name: 'Pöchlarn', website: 'https://www.poechlarn.at', plz: '3380', bezirk: 'Melk', bundesland: 'Niederösterreich', lat: 48.212, lng: 15.212 },
  { name: 'Hainburg an der Donau', website: 'https://www.hainburg-donau.gv.at', plz: '2410', bezirk: 'Bruck an der Leitha', bundesland: 'Niederösterreich', lat: 48.1466, lng: 16.9422 },
  { name: 'Bisamberg', website: 'https://www.bisamberg.at', plz: '2102', bezirk: 'Korneuburg', bundesland: 'Niederösterreich', lat: 48.3317, lng: 16.3616 },
  { name: 'Kottingbrunn', website: 'https://www.kottingbrunn.at', plz: '2542', bezirk: 'Baden', bundesland: 'Niederösterreich', lat: 47.9514, lng: 16.2285 },
  { name: 'Groß-Siegharts', website: 'https://www.gross-siegharts.at', plz: '3812', bezirk: 'Waidhofen an der Thaya', bundesland: 'Niederösterreich', lat: 48.7911, lng: 15.4045 },
];

// ─── OBERÖSTERREICH ──────────────────────────────────────────────────────────
const OBEROESTERREICH: GemeindeInfo[] = [
  { name: 'Linz', website: 'https://www.linz.at', plz: '4020', bezirk: 'Linz (Stadt)', bundesland: 'Oberösterreich', lat: 48.3064, lng: 14.2858 },
  { name: 'Wels', website: 'https://www.wels.at', plz: '4600', bezirk: 'Wels (Stadt)', bundesland: 'Oberösterreich', lat: 48.1565, lng: 14.0244 },
  { name: 'Steyr', website: 'https://www.steyr.at', plz: '4400', bezirk: 'Steyr (Stadt)', bundesland: 'Oberösterreich', lat: 48.039, lng: 14.4191 },
  { name: 'Leonding', website: 'https://www.leonding.at', plz: '4060', bezirk: 'Linz-Land', bundesland: 'Oberösterreich', lat: 48.2792, lng: 14.2478 },
  { name: 'Traun', website: 'https://www.traun.at', plz: '4050', bezirk: 'Linz-Land', bundesland: 'Oberösterreich', lat: 48.2211, lng: 14.2356 },
  { name: 'Ansfelden', website: 'https://www.ansfelden.at', plz: '4052', bezirk: 'Linz-Land', bundesland: 'Oberösterreich', lat: 48.2097, lng: 14.2889 },
  { name: 'Braunau am Inn', website: 'https://www.braunau.at', plz: '5280', bezirk: 'Braunau am Inn', bundesland: 'Oberösterreich', lat: 48.2534, lng: 13.0398 },
  { name: 'Marchtrenk', website: 'https://www.marchtrenk.at', plz: '4614', bezirk: 'Wels-Land', bundesland: 'Oberösterreich', lat: 48.1908, lng: 14.1111 },
  { name: 'Bad Ischl', website: 'https://www.badischl.at', plz: '4820', bezirk: 'Gmunden', bundesland: 'Oberösterreich', lat: 47.7115, lng: 13.6239 },
  { name: 'Gmunden', website: 'https://www.gmunden.at', plz: '4810', bezirk: 'Gmunden', bundesland: 'Oberösterreich', lat: 47.9186, lng: 13.7992 },
  { name: 'Vöcklabruck', website: 'https://www.voecklabruck.at', plz: '4840', bezirk: 'Vöcklabruck', bundesland: 'Oberösterreich', lat: 48.0079, lng: 13.646 },
  { name: 'Ried im Innkreis', website: 'https://www.ried.at', plz: '4910', bezirk: 'Ried im Innkreis', bundesland: 'Oberösterreich', lat: 48.2092, lng: 13.4889 },
  { name: 'Enns', website: 'https://www.enns.at', plz: '4470', bezirk: 'Linz-Land', bundesland: 'Oberösterreich', lat: 48.2141, lng: 14.4794 },
  { name: 'Laakirchen', website: 'https://www.laakirchen.at', plz: '4663', bezirk: 'Gmunden', bundesland: 'Oberösterreich', lat: 47.9826, lng: 13.8225 },
  { name: 'Sierning', website: 'https://www.sierning.at', plz: '4522', bezirk: 'Steyr-Land', bundesland: 'Oberösterreich', lat: 48.0442, lng: 14.3100 },
  { name: 'Altmünster', website: 'https://www.altmuenster.at', plz: '4813', bezirk: 'Gmunden', bundesland: 'Oberösterreich', lat: 47.9016, lng: 13.7652 },
  { name: 'Schärding', website: 'https://www.schaerding.at', plz: '4780', bezirk: 'Schärding', bundesland: 'Oberösterreich', lat: 48.457, lng: 13.4318 },
  { name: 'Attnang-Puchheim', website: 'https://www.attnang-puchheim.at', plz: '4800', bezirk: 'Vöcklabruck', bundesland: 'Oberösterreich', lat: 48.0117, lng: 13.7200 },
  { name: 'Pregarten', website: 'https://www.pregarten.at', plz: '4230', bezirk: 'Freistadt', bundesland: 'Oberösterreich', lat: 48.355, lng: 14.5308 },
  { name: 'Freistadt', website: 'https://www.freistadt.at', plz: '4240', bezirk: 'Freistadt', bundesland: 'Oberösterreich', lat: 48.5117, lng: 14.5050 },
  { name: 'Perg', website: 'https://www.perg.at', plz: '4320', bezirk: 'Perg', bundesland: 'Oberösterreich', lat: 48.2501, lng: 14.6338 },
  { name: 'Grieskirchen', website: 'https://www.grieskirchen.at', plz: '4710', bezirk: 'Grieskirchen', bundesland: 'Oberösterreich', lat: 48.235, lng: 13.8262 },
  { name: 'Kirchdorf an der Krems', website: 'https://www.kirchdorf.at', plz: '4560', bezirk: 'Kirchdorf an der Krems', bundesland: 'Oberösterreich', lat: 47.9052, lng: 14.1244 },
  { name: 'Mattighofen', website: 'https://www.mattighofen.at', plz: '5230', bezirk: 'Braunau am Inn', bundesland: 'Oberösterreich', lat: 48.1031, lng: 13.1503 },
  { name: 'Rohrbach-Berg', website: 'https://www.rohrbach-berg.at', plz: '4150', bezirk: 'Rohrbach', bundesland: 'Oberösterreich', lat: 48.5723, lng: 13.9908 },
  { name: 'Eferding', website: 'https://www.eferding.at', plz: '4070', bezirk: 'Eferding', bundesland: 'Oberösterreich', lat: 48.3083, lng: 14.0204 },
  { name: 'Gallneukirchen', website: 'https://www.gallneukirchen.at', plz: '4210', bezirk: 'Perg', bundesland: 'Oberösterreich', lat: 48.3531, lng: 14.4164 },
  { name: 'Thalheim bei Wels', website: 'https://www.thalheim.at', plz: '4600', bezirk: 'Wels-Land', bundesland: 'Oberösterreich', lat: 48.1522, lng: 14.031 },
  { name: 'Bad Hall', website: 'https://www.badhall.at', plz: '4540', bezirk: 'Steyr-Land', bundesland: 'Oberösterreich', lat: 48.0348, lng: 14.2091 },
  { name: 'Kremsmünster', website: 'https://www.kremsmuenster.at', plz: '4550', bezirk: 'Kirchdorf an der Krems', bundesland: 'Oberösterreich', lat: 48.0539, lng: 14.1292 },
  { name: 'Asten', website: 'https://www.asten.at', plz: '4481', bezirk: 'Linz-Land', bundesland: 'Oberösterreich', lat: 48.2202, lng: 14.4215 },
  { name: 'Gunskirchen', website: 'https://www.gunskirchen.at', plz: '4623', bezirk: 'Wels-Land', bundesland: 'Oberösterreich', lat: 48.1335, lng: 13.9427 },
  { name: 'Regau', website: 'https://www.regau.at', plz: '4844', bezirk: 'Vöcklabruck', bundesland: 'Oberösterreich', lat: 47.9919, lng: 13.6881 },
  { name: 'Ebensee am Traunsee', website: 'https://www.ebensee.at', plz: '4802', bezirk: 'Gmunden', bundesland: 'Oberösterreich', lat: 47.8122, lng: 13.7742 },
  { name: 'Ottensheim', website: 'https://www.ottensheim.at', plz: '4100', bezirk: 'Urfahr-Umgebung', bundesland: 'Oberösterreich', lat: 48.3319, lng: 14.1757 },
  { name: 'Gaspoltshofen', website: 'https://www.gaspoltshofen.at', plz: '4673', bezirk: 'Grieskirchen', bundesland: 'Oberösterreich', lat: 48.1439, lng: 13.7351 },
  { name: 'Bad Leonfelden', website: 'https://www.bad-leonfelden.at', plz: '4190', bezirk: 'Urfahr-Umgebung', bundesland: 'Oberösterreich', lat: 48.5227, lng: 14.2931 },
  { name: 'Micheldorf in Oberösterreich', website: 'https://www.micheldorf.at', plz: '4563', bezirk: 'Kirchdorf an der Krems', bundesland: 'Oberösterreich', lat: 47.8774, lng: 14.1376 },
  { name: 'Hörsching', website: 'https://www.hoersching.at', plz: '4063', bezirk: 'Linz-Land', bundesland: 'Oberösterreich', lat: 48.2265, lng: 14.1783 },
  { name: 'Pasching', website: 'https://www.pasching.at', plz: '4061', bezirk: 'Linz-Land', bundesland: 'Oberösterreich', lat: 48.2576, lng: 14.2044 },
  { name: 'Neuhofen an der Krems', website: 'https://www.neuhofen.at', plz: '4501', bezirk: 'Linz-Land', bundesland: 'Oberösterreich', lat: 48.138, lng: 14.2285 },
  { name: 'Mondsee', website: 'https://www.mondsee.at', plz: '5310', bezirk: 'Vöcklabruck', bundesland: 'Oberösterreich', lat: 47.856, lng: 13.3501 },
  { name: 'Frankenmarkt', website: 'https://www.frankenmarkt.at', plz: '4890', bezirk: 'Vöcklabruck', bundesland: 'Oberösterreich', lat: 47.9855, lng: 13.4192 },
  { name: 'Peuerbach', website: 'https://www.peuerbach.at', plz: '4722', bezirk: 'Grieskirchen', bundesland: 'Oberösterreich', lat: 48.3439, lng: 13.771 },
];

// ─── STEIERMARK ──────────────────────────────────────────────────────────────
const STEIERMARK: GemeindeInfo[] = [
  { name: 'Graz', website: 'https://www.graz.at', plz: '8010', bezirk: 'Graz (Stadt)', bundesland: 'Steiermark', lat: 47.0707, lng: 15.4395 },
  { name: 'Leoben', website: 'https://www.leoben.at', plz: '8700', bezirk: 'Leoben', bundesland: 'Steiermark', lat: 47.3805, lng: 15.0948 },
  { name: 'Kapfenberg', website: 'https://www.kapfenberg.at', plz: '8605', bezirk: 'Bruck-Mürzzuschlag', bundesland: 'Steiermark', lat: 47.4405, lng: 15.2902 },
  { name: 'Leibnitz', website: 'https://www.leibnitz.at', plz: '8430', bezirk: 'Leibnitz', bundesland: 'Steiermark', lat: 46.7805, lng: 15.5407 },
  { name: 'Feldbach', website: 'https://www.feldbach.gv.at', plz: '8330', bezirk: 'Südoststeiermark', bundesland: 'Steiermark', lat: 46.9528, lng: 15.8886 },
  { name: 'Knittelfeld', website: 'https://www.knittelfeld.at', plz: '8720', bezirk: 'Murtal', bundesland: 'Steiermark', lat: 47.2147, lng: 14.8297 },
  { name: 'Gratwein-Straßengel', website: 'https://www.gratwein-strassengel.gv.at', plz: '8112', bezirk: 'Graz-Umgebung', bundesland: 'Steiermark', lat: 47.1231, lng: 15.3305 },
  { name: 'Seiersberg-Pirka', website: 'https://www.seiersberg-pirka.at', plz: '8054', bezirk: 'Graz-Umgebung', bundesland: 'Steiermark', lat: 47.0122, lng: 15.3996 },
  { name: 'Weiz', website: 'https://www.weiz.at', plz: '8160', bezirk: 'Weiz', bundesland: 'Steiermark', lat: 47.2174, lng: 15.6222 },
  { name: 'Deutschlandsberg', website: 'https://www.deutschlandsberg.at', plz: '8530', bezirk: 'Deutschlandsberg', bundesland: 'Steiermark', lat: 46.8146, lng: 15.2138 },
  { name: 'Gleisdorf', website: 'https://www.gleisdorf.at', plz: '8200', bezirk: 'Weiz', bundesland: 'Steiermark', lat: 47.1054, lng: 15.7098 },
  { name: 'Trofaiach', website: 'https://www.trofaiach.at', plz: '8793', bezirk: 'Leoben', bundesland: 'Steiermark', lat: 47.4251, lng: 15.0066 },
  { name: 'Köflach', website: 'https://www.koeflach.at', plz: '8580', bezirk: 'Voitsberg', bundesland: 'Steiermark', lat: 47.0645, lng: 15.085 },
  { name: 'Voitsberg', website: 'https://www.voitsberg.at', plz: '8570', bezirk: 'Voitsberg', bundesland: 'Steiermark', lat: 47.0505, lng: 15.1475 },
  { name: 'Bruck an der Mur', website: 'https://www.bruckmur.at', plz: '8600', bezirk: 'Bruck-Mürzzuschlag', bundesland: 'Steiermark', lat: 47.4122, lng: 15.2722 },
  { name: 'Mürzzuschlag', website: 'https://www.muerzzuschlag.at', plz: '8680', bezirk: 'Bruck-Mürzzuschlag', bundesland: 'Steiermark', lat: 47.6054, lng: 15.6724 },
  { name: 'Judenburg', website: 'https://www.judenburg.at', plz: '8750', bezirk: 'Murtal', bundesland: 'Steiermark', lat: 47.1694, lng: 14.6601 },
  { name: 'Hartberg', website: 'https://www.hartberg.at', plz: '8230', bezirk: 'Hartberg-Fürstenfeld', bundesland: 'Steiermark', lat: 47.2809, lng: 15.9692 },
  { name: 'Fürstenfeld', website: 'https://www.fuerstenfeld.gv.at', plz: '8280', bezirk: 'Hartberg-Fürstenfeld', bundesland: 'Steiermark', lat: 47.05, lng: 16.0817 },
  { name: 'Murau', website: 'https://www.murau.gv.at', plz: '8850', bezirk: 'Murau', bundesland: 'Steiermark', lat: 47.1123, lng: 14.1691 },
  { name: 'Liezen', website: 'https://www.liezen.at', plz: '8940', bezirk: 'Liezen', bundesland: 'Steiermark', lat: 47.5677, lng: 14.2421 },
  { name: 'Schladming', website: 'https://www.schladming.at', plz: '8970', bezirk: 'Liezen', bundesland: 'Steiermark', lat: 47.394, lng: 13.6868 },
  { name: 'Bärnbach', website: 'https://www.baernbach.at', plz: '8572', bezirk: 'Voitsberg', bundesland: 'Steiermark', lat: 47.0726, lng: 15.1263 },
  { name: 'Kindberg', website: 'https://www.kindberg.at', plz: '8650', bezirk: 'Bruck-Mürzzuschlag', bundesland: 'Steiermark', lat: 47.505, lng: 15.4499 },
  { name: 'Gratkorn', website: 'https://www.gratkorn.gv.at', plz: '8101', bezirk: 'Graz-Umgebung', bundesland: 'Steiermark', lat: 47.1326, lng: 15.3391 },
  { name: 'Kalsdorf bei Graz', website: 'https://www.kalsdorf-graz.at', plz: '8401', bezirk: 'Graz-Umgebung', bundesland: 'Steiermark', lat: 46.9644, lng: 15.4787 },
  { name: 'Fehring', website: 'https://www.fehring.at', plz: '8350', bezirk: 'Südoststeiermark', bundesland: 'Steiermark', lat: 46.9361, lng: 16.0104 },
  { name: 'Premstätten', website: 'https://www.premstaetten.gv.at', plz: '8141', bezirk: 'Graz-Umgebung', bundesland: 'Steiermark', lat: 47.0201, lng: 15.5629 },
  { name: 'Fohnsdorf', website: 'https://www.fohnsdorf.at', plz: '8753', bezirk: 'Murtal', bundesland: 'Steiermark', lat: 47.2074, lng: 14.6779 },
  { name: 'Zeltweg', website: 'https://www.zeltweg.at', plz: '8740', bezirk: 'Murtal', bundesland: 'Steiermark', lat: 47.1912, lng: 14.7549 },
  { name: 'Spielberg', website: 'https://www.spielberg.at', plz: '8724', bezirk: 'Murtal', bundesland: 'Steiermark', lat: 47.2123, lng: 14.7857 },
  { name: 'Rottenmann', website: 'https://www.rottenmann.at', plz: '8786', bezirk: 'Liezen', bundesland: 'Steiermark', lat: 47.5242, lng: 14.3586 },
  { name: 'Bad Radkersburg', website: 'https://www.bad-radkersburg.gv.at', plz: '8490', bezirk: 'Südoststeiermark', bundesland: 'Steiermark', lat: 46.6883, lng: 15.9886 },
  { name: 'Krieglach', website: 'https://www.krieglach.at', plz: '8670', bezirk: 'Bruck-Mürzzuschlag', bundesland: 'Steiermark', lat: 47.5453, lng: 15.5596 },
  { name: 'Stainz', website: 'https://www.stainz.at', plz: '8510', bezirk: 'Deutschlandsberg', bundesland: 'Steiermark', lat: 46.8936, lng: 15.2644 },
  { name: 'Pischelsdorf am Kulm', website: 'https://www.pischelsdorf.at', plz: '8212', bezirk: 'Weiz', bundesland: 'Steiermark', lat: 47.173, lng: 15.8058 },
  { name: 'Wagna', website: 'https://www.wagna.at', plz: '8435', bezirk: 'Leibnitz', bundesland: 'Steiermark', lat: 46.7663, lng: 15.5572 },
  { name: 'Frohnleiten', website: 'https://www.frohnleiten.com', plz: '8130', bezirk: 'Graz-Umgebung', bundesland: 'Steiermark', lat: 47.2715, lng: 15.326 },
  { name: 'Niklasdorf', website: 'https://www.niklasdorf.at', plz: '8712', bezirk: 'Leoben', bundesland: 'Steiermark', lat: 47.3969, lng: 15.1571 },
  { name: 'Kumberg', website: 'https://www.kumberg.at', plz: '8062', bezirk: 'Graz-Umgebung', bundesland: 'Steiermark', lat: 47.16, lng: 15.5349 },
  { name: 'Kainbach bei Graz', website: 'https://www.kainbach.at', plz: '8010', bezirk: 'Graz-Umgebung', bundesland: 'Steiermark', lat: 47.1, lng: 15.5563 },
];

// ─── SALZBURG ────────────────────────────────────────────────────────────────
const SALZBURG: GemeindeInfo[] = [
  { name: 'Salzburg', website: 'https://www.stadt-salzburg.at', plz: '5020', bezirk: 'Salzburg (Stadt)', bundesland: 'Salzburg', lat: 47.7981, lng: 13.0465 },
  { name: 'Hallein', website: 'https://www.hallein.com', plz: '5400', bezirk: 'Hallein', bundesland: 'Salzburg', lat: 47.6822, lng: 13.0956 },
  { name: 'Saalfelden am Steinernen Meer', website: 'https://www.saalfelden.at', plz: '5760', bezirk: 'Zell am See', bundesland: 'Salzburg', lat: 47.4264, lng: 12.8481 },
  { name: 'Wals-Siezenheim', website: 'https://www.wals-siezenheim.at', plz: '5071', bezirk: 'Salzburg-Umgebung', bundesland: 'Salzburg', lat: 47.7986, lng: 12.9807 },
  { name: 'Seekirchen am Wallersee', website: 'https://www.seekirchen.at', plz: '5201', bezirk: 'Salzburg-Umgebung', bundesland: 'Salzburg', lat: 47.8942, lng: 13.1261 },
  { name: 'St. Johann im Pongau', website: 'https://www.stjohann.at', plz: '5600', bezirk: 'St. Johann im Pongau', bundesland: 'Salzburg', lat: 47.3476, lng: 13.2026 },
  { name: 'Bischofshofen', website: 'https://www.bischofshofen.at', plz: '5500', bezirk: 'St. Johann im Pongau', bundesland: 'Salzburg', lat: 47.4167, lng: 13.2167 },
  { name: 'Zell am See', website: 'https://www.zellamsee.at', plz: '5700', bezirk: 'Zell am See', bundesland: 'Salzburg', lat: 47.324, lng: 12.7963 },
  { name: 'Straßwalchen', website: 'https://www.strasswalchen.at', plz: '5204', bezirk: 'Salzburg-Umgebung', bundesland: 'Salzburg', lat: 47.9802, lng: 13.2555 },
  { name: 'Kuchl', website: 'https://www.kuchl.net', plz: '5431', bezirk: 'Hallein', bundesland: 'Salzburg', lat: 47.6258, lng: 13.1451 },
  { name: 'Grödig', website: 'https://www.groedig.at', plz: '5082', bezirk: 'Salzburg-Umgebung', bundesland: 'Salzburg', lat: 47.7382, lng: 13.0395 },
  { name: 'Bergheim', website: 'https://www.bergheim.at', plz: '5101', bezirk: 'Salzburg-Umgebung', bundesland: 'Salzburg', lat: 47.8409, lng: 13.0222 },
  { name: 'Mittersill', website: 'https://www.mittersill.at', plz: '5730', bezirk: 'Zell am See', bundesland: 'Salzburg', lat: 47.2815, lng: 12.4837 },
  { name: 'Radstadt', website: 'https://www.radstadt.at', plz: '5550', bezirk: 'St. Johann im Pongau', bundesland: 'Salzburg', lat: 47.3847, lng: 13.4628 },
  { name: 'Neumarkt am Wallersee', website: 'https://www.neumarkt.at', plz: '5202', bezirk: 'Salzburg-Umgebung', bundesland: 'Salzburg', lat: 47.945, lng: 13.2253 },
  { name: 'Oberndorf bei Salzburg', website: 'https://www.oberndorf.at', plz: '5110', bezirk: 'Salzburg-Umgebung', bundesland: 'Salzburg', lat: 47.9399, lng: 12.9461 },
  { name: 'Tamsweg', website: 'https://www.tamsweg.at', plz: '5580', bezirk: 'Tamsweg', bundesland: 'Salzburg', lat: 47.1261, lng: 13.8104 },
];

// ─── TIROL ───────────────────────────────────────────────────────────────────
const TIROL: GemeindeInfo[] = [
  { name: 'Innsbruck', website: 'https://www.innsbruck.gv.at', plz: '6020', bezirk: 'Innsbruck (Stadt)', bundesland: 'Tirol', lat: 47.2654, lng: 11.3927 },
  { name: 'Kufstein', website: 'https://www.kufstein.at', plz: '6330', bezirk: 'Kufstein', bundesland: 'Tirol', lat: 47.583, lng: 12.1692 },
  { name: 'Telfs', website: 'https://www.telfs.at', plz: '6410', bezirk: 'Innsbruck-Land', bundesland: 'Tirol', lat: 47.3047, lng: 11.0715 },
  { name: 'Hall in Tirol', website: 'https://www.hall-in-tirol.at', plz: '6060', bezirk: 'Innsbruck-Land', bundesland: 'Tirol', lat: 47.2817, lng: 11.5075 },
  { name: 'Schwaz', website: 'https://www.schwaz.at', plz: '6130', bezirk: 'Schwaz', bundesland: 'Tirol', lat: 47.345, lng: 11.7084 },
  { name: 'Wörgl', website: 'https://www.woergl.at', plz: '6300', bezirk: 'Kufstein', bundesland: 'Tirol', lat: 47.4873, lng: 12.0638 },
  { name: 'Lienz', website: 'https://www.lienz.gv.at', plz: '9900', bezirk: 'Lienz', bundesland: 'Tirol', lat: 46.8299, lng: 12.7681 },
  { name: 'Imst', website: 'https://www.imst.at', plz: '6460', bezirk: 'Imst', bundesland: 'Tirol', lat: 47.2382, lng: 10.7407 },
  { name: 'St. Johann in Tirol', website: 'https://www.stjohann.tirol.gv.at', plz: '6380', bezirk: 'Kitzbühel', bundesland: 'Tirol', lat: 47.5224, lng: 12.4287 },
  { name: 'Rum', website: 'https://www.rum.gv.at', plz: '6063', bezirk: 'Innsbruck-Land', bundesland: 'Tirol', lat: 47.2868, lng: 11.4574 },
  { name: 'Völs', website: 'https://www.voels.at', plz: '6176', bezirk: 'Innsbruck-Land', bundesland: 'Tirol', lat: 47.2523, lng: 11.3279 },
  { name: 'Zirl', website: 'https://www.zirl.at', plz: '6170', bezirk: 'Innsbruck-Land', bundesland: 'Tirol', lat: 47.2734, lng: 11.2422 },
  { name: 'Kitzbühel', website: 'https://www.kitzbuehel.at', plz: '6370', bezirk: 'Kitzbühel', bundesland: 'Tirol', lat: 47.4467, lng: 12.3917 },
  { name: 'Absam', website: 'https://www.absam.at', plz: '6067', bezirk: 'Innsbruck-Land', bundesland: 'Tirol', lat: 47.2965, lng: 11.5051 },
  { name: 'Wattens', website: 'https://www.wattens.at', plz: '6112', bezirk: 'Innsbruck-Land', bundesland: 'Tirol', lat: 47.2936, lng: 11.5907 },
  { name: 'Landeck', website: 'https://www.landeck.tirol.gv.at', plz: '6500', bezirk: 'Landeck', bundesland: 'Tirol', lat: 47.1424, lng: 10.5705 },
  { name: 'Reutte', website: 'https://www.reutte.at', plz: '6600', bezirk: 'Reutte', bundesland: 'Tirol', lat: 47.4891, lng: 10.7188 },
  { name: 'Jenbach', website: 'https://www.jenbach.at', plz: '6200', bezirk: 'Schwaz', bundesland: 'Tirol', lat: 47.3915, lng: 11.7717 },
  { name: 'Kematen in Tirol', website: 'https://www.kematen.at', plz: '6175', bezirk: 'Innsbruck-Land', bundesland: 'Tirol', lat: 47.2543, lng: 11.2729 },
  { name: 'Axams', website: 'https://www.axams.at', plz: '6094', bezirk: 'Innsbruck-Land', bundesland: 'Tirol', lat: 47.2306, lng: 11.2783 },
  { name: 'Kirchbichl', website: 'https://www.kirchbichl.at', plz: '6322', bezirk: 'Kufstein', bundesland: 'Tirol', lat: 47.5112, lng: 12.0859 },
  { name: 'Kundl', website: 'https://www.kundl.tirol.gv.at', plz: '6250', bezirk: 'Kufstein', bundesland: 'Tirol', lat: 47.4691, lng: 11.9846 },
  { name: 'Mayrhofen', website: 'https://www.mayrhofen.at', plz: '6290', bezirk: 'Schwaz', bundesland: 'Tirol', lat: 47.1672, lng: 11.8639 },
  { name: 'Seefeld in Tirol', website: 'https://www.seefeld.at', plz: '6100', bezirk: 'Innsbruck-Land', bundesland: 'Tirol', lat: 47.3289, lng: 11.1867 },
  { name: 'Fügen', website: 'https://www.fuegen.at', plz: '6263', bezirk: 'Schwaz', bundesland: 'Tirol', lat: 47.343, lng: 11.847 },
  { name: 'Vomp', website: 'https://www.vomp.at', plz: '6134', bezirk: 'Schwaz', bundesland: 'Tirol', lat: 47.3423, lng: 11.6833 },
  { name: 'Mils', website: 'https://www.mils.at', plz: '6068', bezirk: 'Innsbruck-Land', bundesland: 'Tirol', lat: 47.2875, lng: 11.5293 },
  { name: 'Matrei am Brenner', website: 'https://www.matrei-brenner.at', plz: '6143', bezirk: 'Innsbruck-Land', bundesland: 'Tirol', lat: 47.1312, lng: 11.4537 },
  { name: 'Thaur', website: 'https://www.thaur.at', plz: '6065', bezirk: 'Innsbruck-Land', bundesland: 'Tirol', lat: 47.2928, lng: 11.4738 },
  { name: 'Ebbs', website: 'https://www.ebbs.at', plz: '6341', bezirk: 'Kufstein', bundesland: 'Tirol', lat: 47.6309, lng: 12.2154 },
  { name: 'Söll', website: 'https://www.soell.at', plz: '6306', bezirk: 'Kufstein', bundesland: 'Tirol', lat: 47.5038, lng: 12.1915 },
];

// ─── KÄRNTEN ─────────────────────────────────────────────────────────────────
const KAERNTEN: GemeindeInfo[] = [
  { name: 'Klagenfurt am Wörthersee', website: 'https://www.klagenfurt.at', plz: '9020', bezirk: 'Klagenfurt (Stadt)', bundesland: 'Kärnten', lat: 46.6239, lng: 14.3076 },
  { name: 'Villach', website: 'https://www.villach.at', plz: '9500', bezirk: 'Villach (Stadt)', bundesland: 'Kärnten', lat: 46.6167, lng: 13.85 },
  { name: 'Wolfsberg', website: 'https://www.wolfsberg.at', plz: '9400', bezirk: 'Wolfsberg', bundesland: 'Kärnten', lat: 46.8391, lng: 14.8452 },
  { name: 'Spittal an der Drau', website: 'https://www.spittal-drau.at', plz: '9800', bezirk: 'Spittal an der Drau', bundesland: 'Kärnten', lat: 46.7982, lng: 13.4963 },
  { name: 'Feldkirchen in Kärnten', website: 'https://www.feldkirchen.at', plz: '9560', bezirk: 'Feldkirchen', bundesland: 'Kärnten', lat: 46.7229, lng: 14.0965 },
  { name: 'St. Veit an der Glan', website: 'https://www.stveit.at', plz: '9300', bezirk: 'St. Veit an der Glan', bundesland: 'Kärnten', lat: 46.7667, lng: 14.3583 },
  { name: 'Völkermarkt', website: 'https://www.voelkermarkt.at', plz: '9100', bezirk: 'Völkermarkt', bundesland: 'Kärnten', lat: 46.6604, lng: 14.6341 },
  { name: 'Hermagor-Pressegger See', website: 'https://www.hermagor.at', plz: '9620', bezirk: 'Hermagor', bundesland: 'Kärnten', lat: 46.6268, lng: 13.3702 },
  { name: 'St. Andrä', website: 'https://www.st-andrae.at', plz: '9433', bezirk: 'Wolfsberg', bundesland: 'Kärnten', lat: 46.8769, lng: 14.1996 },
  { name: 'Ferlach', website: 'https://www.ferlach.at', plz: '9170', bezirk: 'Klagenfurt-Land', bundesland: 'Kärnten', lat: 46.5265, lng: 14.3006 },
  { name: 'Althofen', website: 'https://www.althofen.at', plz: '9330', bezirk: 'St. Veit an der Glan', bundesland: 'Kärnten', lat: 47.1661, lng: 14.2419 },
  { name: 'Bleiburg', website: 'https://www.bleiburg.at', plz: '9150', bezirk: 'Völkermarkt', bundesland: 'Kärnten', lat: 46.5901, lng: 14.799 },
  { name: 'Radenthein', website: 'https://www.radenthein.at', plz: '9545', bezirk: 'Spittal an der Drau', bundesland: 'Kärnten', lat: 46.8007, lng: 13.7107 },
  { name: 'Gmünd in Kärnten', website: 'https://www.gmuend-kaernten.at', plz: '9853', bezirk: 'Spittal an der Drau', bundesland: 'Kärnten', lat: 46.9066, lng: 13.536 },
  { name: 'Friesach', website: 'https://www.friesach.at', plz: '9360', bezirk: 'St. Veit an der Glan', bundesland: 'Kärnten', lat: 46.9528, lng: 14.4058 },
  { name: 'Bad Kleinkirchheim', website: 'https://www.badkleinkirchheim.at', plz: '9546', bezirk: 'Spittal an der Drau', bundesland: 'Kärnten', lat: 46.8144, lng: 13.7984 },
  { name: 'Velden am Wörthersee', website: 'https://www.velden.gv.at', plz: '9220', bezirk: 'Villach-Land', bundesland: 'Kärnten', lat: 46.6152, lng: 14.0451 },
  { name: 'Maria Saal', website: 'https://www.maria-saal.gv.at', plz: '9063', bezirk: 'Klagenfurt-Land', bundesland: 'Kärnten', lat: 46.6808, lng: 14.3491 },
];

// ─── VORARLBERG ──────────────────────────────────────────────────────────────
const VORARLBERG: GemeindeInfo[] = [
  { name: 'Dornbirn', website: 'https://www.dornbirn.at', plz: '6850', bezirk: 'Dornbirn', bundesland: 'Vorarlberg', lat: 47.4136, lng: 9.7424 },
  { name: 'Feldkirch', website: 'https://www.feldkirch.at', plz: '6800', bezirk: 'Feldkirch', bundesland: 'Vorarlberg', lat: 47.2376, lng: 9.5982 },
  { name: 'Bregenz', website: 'https://www.bregenz.at', plz: '6900', bezirk: 'Bregenz', bundesland: 'Vorarlberg', lat: 47.5031, lng: 9.7471 },
  { name: 'Lustenau', website: 'https://www.lustenau.at', plz: '6890', bezirk: 'Dornbirn', bundesland: 'Vorarlberg', lat: 47.4277, lng: 9.6599 },
  { name: 'Hohenems', website: 'https://www.hohenems.at', plz: '6845', bezirk: 'Dornbirn', bundesland: 'Vorarlberg', lat: 47.364, lng: 9.6893 },
  { name: 'Bludenz', website: 'https://www.bludenz.at', plz: '6700', bezirk: 'Bludenz', bundesland: 'Vorarlberg', lat: 47.153, lng: 9.8219 },
  { name: 'Hard', website: 'https://www.hard.at', plz: '6971', bezirk: 'Bregenz', bundesland: 'Vorarlberg', lat: 47.4894, lng: 9.6917 },
  { name: 'Rankweil', website: 'https://www.rankweil.at', plz: '6830', bezirk: 'Feldkirch', bundesland: 'Vorarlberg', lat: 47.2704, lng: 9.6427 },
  { name: 'Götzis', website: 'https://www.goetzis.at', plz: '6840', bezirk: 'Feldkirch', bundesland: 'Vorarlberg', lat: 47.3351, lng: 9.644 },
  { name: 'Lauterach', website: 'https://www.lauterach.at', plz: '6923', bezirk: 'Bregenz', bundesland: 'Vorarlberg', lat: 47.4747, lng: 9.7313 },
  { name: 'Höchst', website: 'https://www.hoechst.at', plz: '6973', bezirk: 'Bregenz', bundesland: 'Vorarlberg', lat: 47.4598, lng: 9.638 },
  { name: 'Wolfurt', website: 'https://www.wolfurt.at', plz: '6922', bezirk: 'Bregenz', bundesland: 'Vorarlberg', lat: 47.4668, lng: 9.7502 },
  { name: 'Nenzing', website: 'https://www.nenzing.at', plz: '6710', bezirk: 'Bludenz', bundesland: 'Vorarlberg', lat: 47.1833, lng: 9.7000 },
  { name: 'Schwarzach', website: 'https://www.schwarzach.at', plz: '6858', bezirk: 'Bregenz', bundesland: 'Vorarlberg', lat: 47.4451, lng: 9.763 },
  { name: 'Schruns', website: 'https://www.schruns.at', plz: '6780', bezirk: 'Bludenz', bundesland: 'Vorarlberg', lat: 47.0800, lng: 9.9200 },
];

// ─── BURGENLAND ──────────────────────────────────────────────────────────────
const BURGENLAND: GemeindeInfo[] = [
  { name: 'Eisenstadt', website: 'https://www.eisenstadt.gv.at', plz: '7000', bezirk: 'Eisenstadt (Stadt)', bundesland: 'Burgenland', lat: 47.8455, lng: 16.5249 },
  { name: 'Oberwart', website: 'https://www.oberwart.at', plz: '7400', bezirk: 'Oberwart', bundesland: 'Burgenland', lat: 47.2862, lng: 16.2124 },
  { name: 'Neusiedl am See', website: 'https://www.neusiedlamsee.at', plz: '7100', bezirk: 'Neusiedl am See', bundesland: 'Burgenland', lat: 47.9489, lng: 16.8436 },
  { name: 'Mattersburg', website: 'https://www.mattersburg.gv.at', plz: '7210', bezirk: 'Mattersburg', bundesland: 'Burgenland', lat: 47.7368, lng: 16.398 },
  { name: 'Pinkafeld', website: 'https://www.pinkafeld.gv.at', plz: '7423', bezirk: 'Oberwart', bundesland: 'Burgenland', lat: 47.3733, lng: 16.1233 },
  { name: 'Oberpullendorf', website: 'https://www.oberpullendorf.gv.at', plz: '7350', bezirk: 'Oberpullendorf', bundesland: 'Burgenland', lat: 47.5013, lng: 16.5055 },
  { name: 'Güssing', website: 'https://www.guessing.at', plz: '7540', bezirk: 'Güssing', bundesland: 'Burgenland', lat: 47.0588, lng: 16.3243 },
  { name: 'Jennersdorf', website: 'https://www.jennersdorf.gv.at', plz: '8380', bezirk: 'Jennersdorf', bundesland: 'Burgenland', lat: 46.9372, lng: 16.1413 },
  { name: 'Großpetersdorf', website: 'https://www.grosspetersdorf.at', plz: '7503', bezirk: 'Oberwart', bundesland: 'Burgenland', lat: 47.2385, lng: 16.3219 },
  { name: 'Rust', website: 'https://www.rust.at', plz: '7071', bezirk: 'Rust (Stadt)', bundesland: 'Burgenland', lat: 47.8003, lng: 16.6749 },
  { name: 'Frauenkirchen', website: 'https://www.frauenkirchen.at', plz: '7132', bezirk: 'Neusiedl am See', bundesland: 'Burgenland', lat: 47.8377, lng: 16.9241 },
  { name: 'Parndorf', website: 'https://www.parndorf.at', plz: '7111', bezirk: 'Neusiedl am See', bundesland: 'Burgenland', lat: 47.9974, lng: 16.8608 },
  { name: 'Neufeld an der Leitha', website: 'https://www.neufeld-leitha.at', plz: '2491', bezirk: 'Eisenstadt-Umgebung', bundesland: 'Burgenland', lat: 47.8678, lng: 16.3764 },
  { name: 'Stegersbach', website: 'https://www.stegersbach.at', plz: '7551', bezirk: 'Güssing', bundesland: 'Burgenland', lat: 47.1593, lng: 16.1683 },
  { name: 'Deutschkreutz', website: 'https://www.deutschkreutz.at', plz: '7301', bezirk: 'Oberpullendorf', bundesland: 'Burgenland', lat: 47.6004, lng: 16.6248 },
  { name: 'Kittsee', website: 'https://www.kittsee.at', plz: '2421', bezirk: 'Neusiedl am See', bundesland: 'Burgenland', lat: 48.0925, lng: 17.0639 },
  { name: 'Gols', website: 'https://www.gols.at', plz: '7122', bezirk: 'Neusiedl am See', bundesland: 'Burgenland', lat: 47.8984, lng: 16.9084 },
  { name: 'Stadtschlaining', website: 'https://www.stadtschlaining.at', plz: '7461', bezirk: 'Oberwart', bundesland: 'Burgenland', lat: 47.3233, lng: 16.2768 },
  { name: 'Purbach am Neusiedler See', website: 'https://www.purbach.at', plz: '7083', bezirk: 'Eisenstadt-Umgebung', bundesland: 'Burgenland', lat: 47.9134, lng: 16.6958 },
  { name: 'Bruckneudorf', website: 'https://www.bruckneudorf.at', plz: '2460', bezirk: 'Neusiedl am See', bundesland: 'Burgenland', lat: 48.0198, lng: 16.7792 },
  { name: 'Neudörfl', website: 'https://www.neudoerfl.at', plz: '7201', bezirk: 'Mattersburg', bundesland: 'Burgenland', lat: 47.7979, lng: 16.2979 },
  { name: 'Bad Sauerbrunn', website: 'https://www.bad-sauerbrunn.at', plz: '7202', bezirk: 'Mattersburg', bundesland: 'Burgenland', lat: 47.7752, lng: 16.3258 },
  { name: 'Rechnitz', website: 'https://www.rechnitz.at', plz: '7471', bezirk: 'Oberwart', bundesland: 'Burgenland', lat: 47.3049, lng: 16.4409 },
  { name: 'Siegendorf', website: 'https://www.siegendorf.at', plz: '7011', bezirk: 'Eisenstadt-Umgebung', bundesland: 'Burgenland', lat: 47.7803, lng: 16.5414 },
  { name: 'Hornstein', website: 'https://www.hornstein.at', plz: '7053', bezirk: 'Eisenstadt-Umgebung', bundesland: 'Burgenland', lat: 47.8791, lng: 16.443 },
  { name: 'Bad Tatzmannsdorf', website: 'https://www.bad-tatzmannsdorf.at', plz: '7431', bezirk: 'Oberwart', bundesland: 'Burgenland', lat: 47.3338, lng: 16.229 },
  { name: 'Illmitz', website: 'https://www.illmitz.at', plz: '7142', bezirk: 'Neusiedl am See', bundesland: 'Burgenland', lat: 47.7611, lng: 16.8008 },
  { name: 'Pöttsching', website: 'https://www.poettsching.at', plz: '7033', bezirk: 'Mattersburg', bundesland: 'Burgenland', lat: 47.8064, lng: 16.37 },
  { name: 'Steinbrunn', website: 'https://www.steinbrunn.at', plz: '7035', bezirk: 'Eisenstadt-Umgebung', bundesland: 'Burgenland', lat: 47.8358, lng: 16.4146 },
  { name: 'Lockenhaus', website: 'https://www.lockenhaus.at', plz: '7442', bezirk: 'Oberpullendorf', bundesland: 'Burgenland', lat: 47.4067, lng: 16.4182 },
  { name: 'Wallern im Burgenland', website: 'https://www.wallern.at', plz: '7151', bezirk: 'Neusiedl am See', bundesland: 'Burgenland', lat: 47.7262, lng: 16.9381 },
  { name: 'Mörbisch am See', website: 'https://www.moerbisch.at', plz: '7072', bezirk: 'Eisenstadt-Umgebung', bundesland: 'Burgenland', lat: 47.7533, lng: 16.6659 },
];

// ─── GESAMTLISTE ─────────────────────────────────────────────────────────────
export const GEMEINDEN: GemeindeInfo[] = [
  ...WIEN,
  ...NIEDEROESTERREICH,
  ...OBEROESTERREICH,
  ...STEIERMARK,
  ...SALZBURG,
  ...TIROL,
  ...KAERNTEN,
  ...VORARLBERG,
  ...BURGENLAND,
];
