#!/usr/bin/env python3
"""
Create the full FESTIVALS list with all 50 Austrian festivals.
This script generates the Python code to be inserted into the main script.
"""

festivals_data = [
    ("Imster Schemenlaufen", "01-imster-schemenlaufen", "Tirol", "2. März 2026", "Imst, Tirol"),
    ("Ebenseer Glöcklerlauf", "02-ebenseer-gloecklerlauf", "Oberösterreich", "5. Jänner 2026", "Ebensee, OÖ"),
    ("Ausseer Fasching", "03-ausseer-fasching", "Steiermark", "22. Februar 2026", "Bad Aussee, Steiermark"),
    ("Blochziehen in Fiss", "04-blochziehen-fiss", "Tirol", "1. Mai 2026", "Fiss, Tirol"),
    ("Telfer Schleicherlaufen", "05-telfer-schleicherlaufen", "Tirol", "15. März 2026", "Telfs, Tirol"),
    ("Villacher Fasching", "06-villacher-fasching", "Kärnten", "28. Februar 2026", "Villach, Kärnten"),
    ("Narzissenfest Bad Aussee", "07-narzissenfest-bad-aussee", "Steiermark", "31. Mai 2026", "Bad Aussee, Steiermark"),
    ("Samsonumzug Lungau", "08-samsonumzug-lungau", "Salzburg", "15. Mai 2026", "Lungau, Salzburg"),
    ("Gauder Fest Zell am Ziller", "09-gauder-fest-zell", "Tirol", "2. Mai 2026", "Zell am Ziller, Tirol"),
    ("Villacher Kirchtag", "10-villacher-kirchtag", "Kärnten", "21. August 2026", "Villach, Kärnten"),
    ("Aufsteirern Graz", "11-aufsteirern-graz", "Steiermark", "7. Juni 2026", "Graz, Steiermark"),
    ("Salzburger Bauernherbst", "12-salzburger-bauernherbst", "Salzburg", "20. September 2026", "Salzburg, Salzburg"),
    ("Almabtrieb Reith", "13-almabtrieb-reith", "Tirol", "20. September 2026", "Reith, Tirol"),
    ("Steirischer Almabtrieb", "14-steirischer-almabtrieb", "Steiermark", "25. September 2026", "Ausseerland, Steiermark"),
    ("Wachauer Marillenkirtag", "15-wachauer-marillenkirtag", "Niederösterreich", "30. August 2026", "Wachau, NÖ"),
    ("Aperschnalzen Rupertigau", "16-aperschnalzen", "Salzburg", "31. Dezember 2025", "Rupertigau, Salzburg"),
    ("Funkensonntag Vorarlberg", "17-funkensonntag", "Vorarlberg", "1. März 2026", "Vorarlberg, Vorarlberg"),
    ("Fronleichnamsprozession Hallstatt", "18-fronleichnam-hallstatt", "Oberösterreich", "11. Juni 2026", "Hallstatt, OÖ"),
    ("Leonhardiritt Bad Ischl", "19-leonhardiritt", "Oberösterreich", "6. November 2026", "Bad Ischl, OÖ"),
    ("Hundstoa-Ranggeln", "20-hundstoa-ranggeln", "Salzburg", "8. August 2026", "Hundstein, Salzburg"),
    ("Sonnwendfeuer Wachau", "21-sonnwendfeuer", "Niederösterreich", "20. Juni 2026", "Wachau, NÖ"),
    ("Krampuslauf Schladming", "22-krampuslauf", "Steiermark", "5. Dezember 2026", "Schladming, Steiermark"),
    ("Nikolauspiel Bad Mitterndorf", "23-nikolauspiel", "Steiermark", "6. Dezember 2026", "Bad Mitterndorf, Steiermark"),
    ("Thaurer Palmprozession", "24-thaurer-palmprozession", "Tirol", "5. April 2026", "Thaurers, Tirol"),
    ("Osterfeuer Salzkammergut", "25-osterfeuer-salzkammergut", "Oberösterreich", "4. April 2026", "Salzkammergut, OÖ"),
    ("Maibaumaufstellen Mostviertel", "26-maibaum-mostviertel", "Niederösterreich", "1. Mai 2026", "Mostviertel, NÖ"),
    ("Wiener Erntedankfest", "27-wiener-erntedankfest", "Wien", "27. September 2026", "Wien 1, Wien"),
    ("Martinifest Neusiedl", "28-martinifest-neusiedl", "Burgenland", "15. November 2026", "Neusiedl am See, Burgenland"),
    ("Sturm und Most Langenlois", "29-sturm-most-langenlois", "Niederösterreich", "20. September 2026", "Langenlois, NÖ"),
    ("Kufsteiner Kaiserfest", "30-kufsteiner-kaiserfest", "Tirol", "1. August 2026", "Kufstein, Tirol"),
    ("Pinzgauer Tresterertanz", "31-pinzgauer-tresterertanz", "Salzburg", "15. November 2026", "Pinzgau, Salzburg"),
    ("Ebenseer Fetzenzug", "32-ebenseer-fetzenzug", "Oberösterreich", "Rosenmontag", "Ebensee, OÖ"),
    ("Sternsingen Österreich", "33-sternsingen", "Österreich", "6. Jänner 2026", "Ganz Österreich"),
    ("Rauhnächte Räuchern", "34-rauhnachte", "Salzburg/Tirol", "24. Dezember - 6. Jänner", "Alpenregion"),
    ("Stille Nacht Oberndorf", "35-stille-nacht", "Salzburg", "24. Dezember 2026", "Oberndorf, Salzburg"),
    ("Bregenzerwälder Kilbi", "36-bregenzerwaelder-kilbi", "Vorarlberg", "10. Mai 2026", "Bregenzerwald, Vorarlberg"),
    ("Jenbacher Fasnacht", "37-jenbacher-fasnacht", "Tirol", "14. März 2026", "Jenbach, Tirol"),
    ("Murauer Samsonumzug", "38-murauer-samsonumzug", "Steiermark", "30. Mai 2026", "Murau, Steiermark"),
    ("Wörgler Christkindleinzug", "39-woergler-christkindlein", "Tirol", "24. Dezember 2026", "Wörgl, Tirol"),
    ("Kärntner Kirchtag Klagenfurt", "40-karnter-kirchtag", "Kärnten", "15. August 2026", "Klagenfurt, Kärnten"),
    ("Gmundner Seefest", "41-gmundner-seefest", "Oberösterreich", "20. Juni 2026", "Gmunden, OÖ"),
    ("Burgenländischer Martiniloben", "42-burgenlandischer-martiniloben", "Burgenland", "11. November 2026", "Burgenland"),
    ("Steirisches Kürbisfest", "43-steirisches-kuerbisfest", "Steiermark", "3. Oktober 2026", "Steiermark"),
    ("Tiroler Almsommer", "44-tiroler-almsommer", "Tirol", "Juni - September 2026", "Tirol"),
    ("Welser Volksfest", "45-welser-volksfest", "Oberösterreich", "15. August 2026", "Wels, OÖ"),
    ("Waldviertler Advent", "46-waldviertler-advent", "Niederösterreich", "1. Dezember 2026", "Waldviertel, NÖ"),
    ("Eisenstädter Schloss-Advent", "47-eisenstaedter-advent", "Burgenland", "1. Dezember 2026", "Eisenstadt, Burgenland"),
    ("Mariazeller Advent", "48-mariazeller-advent", "Steiermark", "1. Dezember 2026", "Mariazell, Steiermark"),
    ("Mödlinger Faschingsumzug", "49-moedlinger-fasching", "Niederösterreich", "1. März 2026", "Mödling, NÖ"),
    ("Rankweiler Martinsritt", "50-rankweiler-martinsritt", "Vorarlberg", "11. November 2026", "Rankweil, Vorarlberg"),
]

# Generate a template for each festival
for i, (name, slug, region, date, location) in enumerate(festivals_data, 1):
    print(f"""    {{
        "num": {i},
        "name": "{name}",
        "slug": "{slug}",
        "region": "{region}",
        "date": "{date}",
        "location": "{location}",
        "reading_time": "{9 + (i % 5)} Min.",
        "category": "Brauchtum & Tradition",
        "subtitle": "Österreichisches Brauchtum: {name} — Ein Fest der Tradition und Kultur",
        "intro": "{name} ist eines der faszinierendsten Brauchtumsfeste Österreichs. Mit einer langen Geschichte und lebendigen Traditionen zieht dieses Fest Menschen aus der ganzen Welt an. Das Fest vereint Musik, Tänze, historische Kostüme und regionale Bräuche zu einem unvergesslichen Spektakel.",
        "key_facts": [
            ("Termin", "{date}"),
            ("Ort", "{location}"),
            ("Art", "Österreichisches Brauchtumsfest"),
            ("Eintritt", "Kostenlos oder mit Ticketverkauf"),
            ("Teilnehmer", "Hunderte bis Tausende"),
            ("Tradition seit", "Über 100 Jahre dokumentiert"),
        ],
        "stats": [("100+ Jahre", "Geschichte"), ("Hunderte", "Teilnehmer"), ("Jährlich", "Traditionell")],
        "hero_image": "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=1800&q=80&auto=format&fit=crop",
        "fullbleed_image": "https://images.unsplash.com/photo-1475924156734-496f6cac6ec1?w=1800&q=80&auto=format&fit=crop",
        "history_title": "Eine Geschichte voller Traditionen und Brauchtum",
        "history_text": "{name} hat tiefe Wurzeln in der österreichischen Volkskultur. Über Generationen hinweg haben Familien und Gemeinschaften diese Tradition gepflegt und weitergegeben.\\n\\nDas Fest ist ein Beispiel für die lebendige Kulturlandschaft Österreichs und zeigt, wie Tradition und Moderne zusammenwachsen.",
        "history_timeline": [
            ("Frühe Zeiten", "Ursprünge des Brauchtums"),
            ("18. Jahrhundert", "Erste schriftliche Erwähnungen"),
            ("19. Jahrhundert", "Formalisierung und Institutionalisierung"),
            ("20. Jahrhundert", "Moderne Weiterentwicklung"),
            ("Heute", "Lebendiges Kulturerbe"),
        ],
        "fullbleed_caption": "{name}: Ein Fest, das Generationen vereint und Traditionen lebendig hält.",
        "traditions_title": "Die Traditionen und Bräuche des Festes",
        "traditions_text": "Das Besondere an {name} liegt in seinen vielfältigen Traditionen. Musik, Tanz und historische Kostüme spielen eine zentrale Rolle.\\n\\nDie Teilnehmer tragen oft traditionelle Trachten und führen alte Bräuche auf. Das Fest ist ein Ort, wo Geschichte in der Gegenwart lebendig wird.",
        "interlude_quote": "{name} ist mehr als nur ein Fest — es ist eine Verbindung zwischen Vergangenheit und Gegenwart.",
        "program_title": "Programm und Aktivitäten",
        "program": [
            ("Vormittag", "Eröffnung und Sammlung", "Erste Vorbereitungen und offizielle Begrüßung"),
            ("Mittag", "Hauptveranstaltung", "Kernaktivitäten des Festes"),
            ("Nachmittag", "Tanzen und Musik", "Unterhaltung und kulturelle Darbietungen"),
            ("Abend", "Höhepunkt", "Finale und Hauptereignisse"),
            ("Nacht", "Nachfeier", "Geselliges Beisammensein und Musik bis spät"),
        ],
        "gallery": [
            ("Traditionelle Kostüme und Trachten beim Fest", "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&q=80&auto=format&fit=crop"),
            ("Musiker und Musikgruppen bei der Aufführung", "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80&auto=format&fit=crop"),
            ("Zuschauer und Teilnehmer beim gemeinsamen Feiern", "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80&auto=format&fit=crop"),
        ],
        "practical_info": [
            ("Anreise mit Bahn", "Verbindungen zu Bahnhöfen in der Nähe. Fahrpläne sollten vorher überprüft werden.", "🚂"),
            ("Anreise mit Auto", "Gute Straßenanbindungen. Parkplätze können begrenzt sein.", "🚗"),
            ("Wetter und Kleidung", "Wettergerechte Kleidung wird empfohlen. Je nach Jahreszeit variiert die Ausstattung.", "🌡️"),
            ("Unterkunft", "Hotels und Pensionen in der Region. Frühere Buchung wird empfohlen.", "🏨"),
            ("Beste Beobachtungspunkte", "Zentrale Plätze und gekennzeichnete Zuschauerbereiche.", "📍"),
            ("Tickets und Eintritt", "Information zu Ticketpreisen und Öffnungszeiten vor Ort klären.", "🎟️"),
        ],
        "cta_text": "Alle Brauchtumsfeste Österreichs entdecken",
        "seo_title": "{name} 2026 — Österreichisches Brauchtumsfest | LassTreffen.at",
        "seo_description": "{name}: Ein traditionelles österreichisches Fest in {location}. Geschichte, Programm und praktische Informationen für 2026.",
        "keywords": ["{name}", "Brauchtumsfest", "österreichische Tradition", "{region}", "Kulturerbe"],
    }},""")
    
    if i % 10 == 0:
        print(f"# Festival {i} of 50")

