#!/usr/bin/env python3
"""
Festival data batch 1: Festivals 4-12
Blochziehen, Schleicherlaufen, Villacher Fasching, Narzissenfest, Samsonumzug, Gauder Fest, Villacher Kirchtag, Aufsteirern, Bauernherbst
"""

FESTIVALS_BATCH1 = [
    {
        "num": 4,
        "name": "Blochziehen in Fiss",
        "slug": "04-blochziehen-fiss",
        "region": "Tirol",
        "bundesland": "Tirol",
        "date": "1. Mai 2026",
        "location": "Fiss, Sölden, Tirol",
        "reading_time": "11 Min.",
        "category": "Brauchtum & Tradition",
        "subtitle": "Ein uralter Fasching-Ritus: Der Kampf um einen gigantischen Baumstamm, alle vier Jahre neu entfacht",
        "intro": "Im Ötztal, auf 1.436 Metern Höhe, findet alle vier Jahre eines der wildesten Brauchtümer Österreichs statt — das Blochziehen von Fiss. Ein Baumstamm von mehreren Metern Länge und einer Tonne Gewicht wird von hunderten von Männern durch das Bergdorf gezogen, während die Frauen die Zugstricke zerschneiden versuchen. Es ist kein sportlicher Wettbewerb, kein inszeniertes Spektakel — es ist eine Auseinandersetzung zwischen Männern und Frauen, zwischen Tradition und Wildheit, zwischen den Generationen. Der Ursprung dieses Brauchtums liegt in der Tiefe des Mittelalters und ist bis heute ungebrochen.",
        "key_facts": [
            ("Nächster Termin", "1. Mai 2026 (alle 4 Jahre)"),
            ("Ort", "Fiss-Ladis, Sölden, Ötztal, Tirol"),
            ("Art", "Männerbrauch mit Baumstamm-Ritual"),
            ("Eintritt", "Kostenlos, besondere Zonen 20-40 EUR"),
            ("Teilnehmer", "300+ Männer, hunderte Frauen"),
            ("Tradition seit", "Mindestens 400 Jahre dokumentiert"),
        ],
        "stats": [("4 Jahre", "Zyklus zwischen den Ereignissen"), ("1 Tonne", "Gewicht des Baumstammes"), ("500+ m", "Zugstrecke durch Fiss")],
        "hero_image": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1800&q=80&auto=format&fit=crop",
        "fullbleed_image": "https://images.unsplash.com/photo-1482192505345-5655af888cc4?w=1800&q=80&auto=format&fit=crop",
        "history_title": "Der Kampf um den Stamm — Ein Ritual aus dem Mittelalter",
        "history_text": "Das Blochziehen ist ein Überbleibsel aus einer Zeit, als Männerbünde und Zunft-Strukturen das Dorfleben dominierten. Der Ursprung liegt vermutlich in mittelalterlichen Holzfällertraditionen, bei denen die schwersten Stämme ins Tal gezogen werden mussten. Mit der Zeit entwickelte sich daraus ein ritualisiertes Spiel zwischen den Geschlechtern.\n\nDie Frauen versuchen, die Zugstricke des Stammes zu zerschneiden — dies ist ein Symbol ihrer Macht, ihre Fähigkeit, die männliche Dominanz zu unterbrechen. Es ist ein spielerischer, aber auch ernsthafter Kampf. Die Tradition wurde über vier Jahrhunderte weitergegeben, und es ist eines der wenigen Brauchtümer, das nicht an Kontinuität verloren hat.",
        "history_timeline": [
            ("1400er", "Erste mündliche Überlieferungen von Baumstamm-Ritualen"),
            ("1600er", "Schriftliche Erwähnungen in Dorf-Chroniken"),
            ("1850", "Formalisierung als alle-vier-Jahre Ereignis"),
            ("1920er", "Vereinigung der Blochzieher in lokalen Bruderschaften"),
            ("2026", "Nächstes großes Blochziehen nach dem 4-Jahres-Rhythmus"),
        ],
        "fullbleed_caption": "Blochziehen Fiss: Der massive Stamm wird von hunderten Händen durch das Bergdorf gezogen.",
        "traditions_title": "Ein Spiel der Geschlechter — Stricke, Äxte und Tradition",
        "traditions_text": "Das Kernstück des Blochziehens ist ein einfaches, aber dramatisches Szenario: Ein Stamm wird mit Seilen bespannt. Gruppen von Männern bilden sich, um den Stamm zu ziehen — von der Bäckerei bis zur Kirche, von der Kirche bis zur Schule. Unterwegs versuchen Frauen mit Äxten und Messern, die Zugstricke zu zerschneiden. Gelingt es ihnen, stoppt der Stamm, und die Männer müssen verhandeln — oft mit Schnapps und Geld — um die Stricke wieder zu bekommen.\n\nDas Ganze ist eine Art spielerisches Theater, das aber auch ernsthafte Züge hat: Es geht um Macht, um Geschlechterrollen, um die Frage, wer in der Gesellschaft das Sagen hat.",
        "interlude_quote": "Das Blochziehen ist kein Spiel — es ist ein Gespräch zwischen den Geschlechtern, geführt in der Sprache der Tradition.",
        "program_title": "Programm & Höhepunkte des Tages",
        "program": [
            ("09:00", "Sammlung der Mannschaften", "Die Blochzieher-Gruppen treffen sich und bereiten ihre Zugstricke vor."),
            ("10:00", "Offizielle Eröffnung", "Mit Böllerschießen und Musik beginnt das Fest."),
            ("11:00", "Erste Zugstrecke", "Der erste Stamm wird gezogen — die Frauen greifen zur Axt."),
            ("14:00", "Hauptveranstaltung auf dem Marktplatz", "Alle drei Strecken sind absolviert, Verhandlungen und Feiern."),
            ("18:00+", "Nachfeier in den Gasthäusern", "Schnapps, Musik und Geschichten klingen bis in die Nacht aus."),
        ],
        "gallery": [
            ("Hunderte von Männern ziehen am Seil — Kraft und Tradition vereint.", "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&q=80&auto=format&fit=crop"),
            ("Frauen mit Äxten versuchen, die Stricke zu zerschneiden — eine Szene voller Spannung.", "https://images.unsplash.com/photo-1482192505345-5655af888cc4?w=800&q=80&auto=format&fit=crop"),
            ("Das Ötztal im Hintergrund: Fiss liegt auf 1.436 m Höhe, umgeben von Bergen.", "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800&q=80&auto=format&fit=crop"),
        ],
        "practical_info": [
            ("Anreise mit der Bahn", "ÖBB Wien-Ötztal ca. 9 Stunden, dann Busse zu Fiss.", "🚂"),
            ("Anreise mit dem Auto", "Von Wien ca. 700 km über die A1, A8 und B186 ins Ötztal.", "🚗"),
            ("Höhenakklimatisierung", "Fiss liegt auf 1.436 m. Acclimatization empfohlen.", "⛰️"),
            ("Unterkunft in Fiss", "Hotels und Gasthöfe im Ötztal sind begrenzt, früh buchen.", "🏨"),
            ("Beste Standpunkte", "Marktplatz und Hauptstraße bieten die beste Sicht.", "📍"),
            ("Wetter im Mai", "Kann zwischen 5-15°C variieren, Regen möglich, Regenjacke ratsam.", "🌡️"),
        ],
        "cta_text": "Alle Bergbrauchtümer und Alpen-Traditionen Österreichs",
        "seo_title": "Blochziehen Fiss 2026 — Das Männer-Ritual des Öztals in Tirol",
        "seo_description": "Blochziehen Fiss: Alle vier Jahre findet dieses einzigartige Brauchtum statt — Männer ziehen einen Stamm durch Fiss, Frauen versuchen, die Stricke zu zerschneiden. 1. Mai 2026 im Ötztal.",
        "keywords": ["Blochziehen Fiss", "Ötztal Tradition", "Tiroler Brauchtum", "Männerbund Ritual", "Alpenkultur"],
    },
    {
        "num": 5,
        "name": "Telfer Schleicherlaufen",
        "slug": "05-telfer-schleicherlaufen",
        "region": "Tirol",
        "bundesland": "Tirol",
        "date": "15. März 2026",
        "location": "Telfs, Zillertal, Tirol",
        "reading_time": "12 Min.",
        "category": "Brauchtum & Tradition",
        "subtitle": "UNESCO-Spektakel: Alle fünf Jahre ziehen maskierte Narren in Kostümen voller Folklore durch das Zillertal",
        "intro": "Das Telfer Schleicherlaufen ist eine der lautesten, farbenfrohesten, und wildesten Faschingstraditionen der Alpen. Alle fünf Jahre (nächstes Mal 2026) ziehen Tausende von Teilnehmern in aufwändigen, von Hand gefertigten Masken und Kostümen durch Telfs — eine Prozession aus Chaos, Musik und bewusster Norm-Brechung. Im Gegensatz zu strukturierteren Faschingsfeierlichkeiten ist das Schleicherlaufen radikaler: Die Masken sind bizarr, manchmal verstörend, die Musik laut und dissonant, der Umzug folgt keinen strikten Regeln. Es ist ein Fest der Freiheit, der Überwindung sozialer Grenzen, und der Rebellion gegen die Ordnung.",
        "key_facts": [
            ("Nächster Termin", "15. März 2026 (alle 5 Jahre)"),
            ("Ort", "Telfs, Zillertal, Tirol"),
            ("Art", "Faschingsumzug mit Masken, UNESCO-Welterbe"),
            ("Eintritt", "Kostenlos, Tribünen 25-50 EUR"),
            ("Teilnehmer", "3.000+ Schleichler, 20.000+ Zuschauer"),
            ("Tradition seit", "Mindestens 300 Jahre dokumentiert"),
        ],
        "stats": [("5 Jahre", "Zyklus zwischen den Ereignissen"), ("3000+", "Schleichler in Masken"), ("20 km", "Umzugsstrecke")],
        "hero_image": "https://images.unsplash.com/photo-1470770903676-69b98201ea1c?w=1800&q=80&auto=format&fit=crop",
        "fullbleed_image": "https://images.unsplash.com/photo-1515488764276-beab7607c1e6?w=1800&q=80&auto=format&fit=crop",
        "history_title": "Fünf Jahrhunderte Masken-Wahnsinn: Das Schleicherlaufen und seine Ursprünge",
        "history_text": "Das Telfer Schleicherlaufen entstand im 16. Jahrhundert, ursprünglich als ein Fest der Zünfte und Handwerker. Die Handwerks-Zünfte von Telfs nutzten den Fasching, um sich vom strengen Stand-System zu befreien — jeder konnte eine Maske tragen und würde nicht erkannt. Dies war eine Form der sozialen Revolution, verpackt in Spaß und Musik.\n\nDie Maske war immer das Zentrale Element: Sie ermöglichte Anonymität und damit Freiheit. Über die Jahrhunderte entwickelten sich die Masken zu kunstvoller ausgestalteten Werken. Im 20. Jahrhundert wurde das Schleicherlaufen fast ausgelöscht, erlebte aber in den 1970ern eine Wiedererweckung. 2010 wurde es in die UNESCO-Liste des immateriellen Kulturerbes aufgenommen.",
        "history_timeline": [
            ("1500er", "Erste Erwähnungen von Masken-Umzügen in Telfs"),
            ("1700er", "Formalisierung durch die Zünfte von Telfs"),
            ("1850er", "Spezialisierung: Flinserl, Roller, Schleichler"),
            ("1975", "Wiedererweckung des Schleicherlaufens nach Unterbrechung"),
            ("2010", "UNESCO-Eintrag für das Schleicherlaufen-Brauchtum"),
        ],
        "fullbleed_caption": "Telfer Schleichler in voller Pracht: Aufwändige Masken, bunte Trachten, unheilvolle Schönheit.",
        "traditions_title": "Die Kunstform der Maske: Wie man Schleichler wird",
        "traditions_text": "Eine Schleichler-Maske ist nicht einfach eine Karnevals-Maske — sie ist ein Kunstwerk, das Wochen oder Monate dauert, um hergestellt zu werden. Viele Masken sind aus Papiermaché, Holz oder Stoff gefertigt. Die Motive sind vielfältig: Es gibt teufliche Figuren, mythologische Wesen, historische Charaktere, Karikaturen von Bürgern und Politikern.\n\nDie Trachten sind ebenfalls aufwändig: Bunte Stoffe, aufgenähte Dekorationen, Federn, Bänder. Zusammen mit der Maske ergibt die Tracht ein kohärentes Aussehen, das den Träger völlig verbirgt. Das Ziel ist die völlige Verwandlung — der Träger wird zur Maske.",
        "interlude_quote": "Beim Telfer Schleicherlaufen nimmt man eine Maske auf, und die ganze Welt verändert sich.",
        "program_title": "Programm & Höhepunkte des Schleicherlaufens",
        "program": [
            ("08:00", "Sammlung der Schleichler", "Tausende Maskenträger versammeln sich in den Vereinshäusern."),
            ("10:00", "Vorbeimarsch und Grußgeben", "Traditionelle Begrüßungsprozessionen auf dem Marktplatz."),
            ("12:00", "Der große Umzug beginnt", "Ein endloser Strom von Masken zieht durch Telfs."),
            ("15:00", "Stationen und Tanzplätze", "An verschiedenen Orten präsentieren sich einzelne Schleichler-Gruppen."),
            ("19:00+", "Nachfeiern und Maskenbälle", "Ganze Nacht Musik, Tanz und Wildheit in den Gasthäusern."),
        ],
        "gallery": [
            ("Eine Nahaufnahme einer Schleichler-Maske: Kunstvolles, verstörendes Kunsthandwerk.", "https://images.unsplash.com/photo-1470770903676-69b98201ea1c?w=800&q=80&auto=format&fit=crop"),
            ("Gruppen von Schleichlern in bunten Trachten beim Umzug.", "https://images.unsplash.com/photo-1515488764276-beab7607c1e6?w=800&q=80&auto=format&fit=crop"),
            ("Das Zillertal im Hintergrund: Grüne Berge und traditionelle Häuser.", "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800&q=80&auto=format&fit=crop"),
        ],
        "practical_info": [
            ("Anreise mit der Bahn", "ÖBB Wien-Telfs ca. 9 Stunden, Zillertal-Bahn direkt zu den Orten.", "🚂"),
            ("Anreise mit dem Auto", "Von Wien ca. 650 km über A1, A8 ins Zillertal.", "🚗"),
            ("März-Wetter", "5-12°C, variable Witterung, Regenschutz sinnvoll.", "🌡️"),
            ("Unterkunft im Zillertal", "Viele Hotels und Gasthöfe, frühzeitige Buchung erforderlich.", "🏨"),
            ("Beobachtungsplätze", "Marktplatz kostenlos, Straßen entlang des Umzugs mit freier Sicht.", "📍"),
            ("Fotografie", "Mit Maske fotografieren ist Tradition, aber Respekt vor Privatsphäre.", "📸"),
        ],
        "cta_text": "Alle UNESCO-Brauchtümer Österreichs entdecken",
        "seo_title": "Telfer Schleicherlaufen 2026 — UNESCO-Faschingsspektakel des Zillertals",
        "seo_description": "Telfer Schleicherlaufen: UNESCO-Brauchtum mit 3.000+ aufwändig maskierten Schleichlern, 15. März 2026 in Telfs. Geschichte, Masken-Kunsthandwerk, Programm.",
        "keywords": ["Schleicherlaufen Telfs", "UNESCO Faschingsbrauch", "Zillertal Tradition", "Tiroler Fasching", "Maskenbrauch"],
    },
    {
        "num": 6,
        "name": "Villacher Fasching",
        "slug": "06-villacher-fasching",
        "region": "Kärnten",
        "bundesland": "Kärnten",
        "date": "28. Februar 2026",
        "location": "Villach, Kärnten",
        "reading_time": "11 Min.",
        "category": "Brauchtum & Tradition",
        "subtitle": "Südösterreichs größtes Faschingsfest: Der Villacher Fasching mit Wahnsinn, Musik und Umzügen ohne Ende",
        "intro": "Der Villacher Fasching ist das größte und wildeste Faschingsfest im südlichen Österreich — groß wie das Imster Schemenlaufen, aber mit einem ganz anderen Charakter. In Villach, der zweitgrößten Stadt Kärntens, verwandelt sich die ganze Stadt in ein Fest der Ekstase, der Musik und der Masken. Der Fasching erstreckt sich über mehrere Tage und Nächte, mit täglichen Umzügen, Maskenbällen, und einer Gesamtatmosphäre der kontrollierten Anarchie. Die Musik ist lauter, die Tänze sind wilder, und die Beteiligung ist massiv — möglicherweise die größte Faschings-Veranstaltung südlich von Tirol.",
        "key_facts": [
            ("Termin", "28. Februar 2026"),
            ("Ort", "Villach, Kärnten, Südösterreich"),
            ("Art", "Großes Faschingsfest mit Umzügen und Maskenbällen"),
            ("Eintritt", "Kostenlos im öffentlichen Raum, Bälle 20-40 EUR"),
            ("Teilnehmer", "100.000+ Besucher, 5.000+ Aktive"),
            ("Tradition seit", "Mindestens 200 Jahre dokumentiert"),
        ],
        "stats": [("100.000+", "Besucher"), ("5000+", "aktive Teilnehmer"), ("4 Tage", "Festivaldauer")],
        "hero_image": "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1800&q=80&auto=format&fit=crop",
        "fullbleed_image": "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=1800&q=80&auto=format&fit=crop",
        "history_title": "Südösterreichs Fasching-Tradition: Ein Fest der Grenzen",
        "history_text": "Villach liegt geografisch an einer Grenze — zwischen der deutschsprachigen und slowenischsprachigen Welt, zwischen Alpen und Mittelmeer-Kultureinflüssen. Diese geografische Lage spiegelt sich im Villacher Fasching: Es ist eine Synthese verschiedener Brauchtümer, eine Mischung aus alpiner Tradition und südlicher Lebensfreude.\n\nDie Tradition reicht mindestens 200 Jahre zurück und war eng mit der österreichisch-ungarischen Monarchie verbunden. Nach dem Zweiten Weltkrieg wurde der Fasching wiederbelebt und ist seitdem zu einer der größten Faschings-Veranstaltungen Österreichs geworden.",
        "history_timeline": [
            ("1800er", "Erste dokumentierte Faschings-Umzüge in Villach"),
            ("1900", "Etablierung als regionaler Höhepunkt"),
            ("1945-1960", "Unterbrechung und Wiederaufbau nach dem Krieg"),
            ("1980er", "Ausbau zu einem der größten Faschingsfeste Österreichs"),
            ("Heute", "Villacher Fasching mit über 100.000 Besuchern"),
        ],
        "fullbleed_caption": "Villacher Fasching: Tausende Besucher säumen die Straßen zum großen Umzug.",
        "traditions_title": "Musik, Tanz und Ekstase: Die Kultur des Villacher Fasching",
        "traditions_text": "Der Villacher Fasching ist weniger auf einzelne Masken-Gruppen strukturiert als vielmehr auf massive Partizipation: Nahezu jeder Besucher trägt eine Maske oder ein Kostüm. Es gibt weniger Vorführungen als vielmehr ein allgemeines Feiern und Tanzen auf den Straßen.\n\nDie Musik ist die Seele des Festes: Überall spielen Blaskapellen, auf den Plätzen gibt es DJ-Stationen und Live-Bands. Die Tänzer — alte und junge, Profis und Amateure — bilden durchgehend Tanzgruppen. Es ist ein Fest, das weniger choreographiert als vielmehr spontan ist.",
        "interlude_quote": "Der Villacher Fasching ist nicht etwas, das man beobachtet — es ist etwas, in das man eintaucht.",
        "program_title": "Programm & Aktivitäten des Fasching-Wochenendes",
        "program": [
            ("Freitag 14:00", "Eröffnung und erste Umzüge", "Der Fasching beginnt mit einer feierlichen Eröffnung auf dem Hauptplatz."),
            ("Samstag 10:00", "Großer Karnevals-Umzug", "Der Hauptumzug mit Musik, Wagen und tausenden Maskenträgern."),
            ("Samstag 18:00", "Maskenbälle in der Stadt", "Hotels und Gasthäuser öffnen spezielle Faschings-Räume."),
            ("Sonntag 14:00", "Kinder-Fasching", "Spezielles Programm für Familien mit Umzügen und Aktivitäten."),
            ("Montag 12:00", "Auszehrung und Finale", "Der Fasching endet mit traditionellen Auszehrungs-Ritualen."),
        ],
        "gallery": [
            ("Maskierte Teilnehmer tanzen auf der Straße — Ekstase und Musik vereint.", "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80&auto=format&fit=crop"),
            ("Die Straßen von Villach sind voll mit Tausenden von Fasching-Feiernden.", "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800&q=80&auto=format&fit=crop"),
            ("Faschings-Wagen mit Blaskapelle passieren den Hauptplatz.", "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80&auto=format&fit=crop"),
        ],
        "practical_info": [
            ("Anreise mit der Bahn", "ÖBB Wien-Villach ca. 6 Stunden direkte Verbindung.", "🚂"),
            ("Anreise mit dem Auto", "Von Wien ca. 380 km über die A2 direkt nach Villach.", "🚗"),
            ("Februar-Wetter", "0-10°C, variabel, Schnee möglich, warme Kleidung erforderlich.", "🌡️"),
            ("Unterkunft in Villach", "Hotels und Gasthöfe sind während des Fasching ausgebucht, frühzeitig buchen.", "🏨"),
            ("Zentrale Plätze", "Hauptplatz und Straßen-Umzugs-Wege bieten beste Sicht.", "📍"),
            ("Masken und Kostüme", "Viele lokale Shops bieten Faschings-Zubehör an, vorher kaufen empfohlen.", "🎭"),
        ],
        "cta_text": "Alle Faschingsfeste Österreichs erleben",
        "seo_title": "Villacher Fasching 2026 — Südösterreichs größtes Faschingsfest in Kärnten",
        "seo_description": "Villacher Fasching 2026: 100.000+ Besucher, 28. Februar in Villach. Umzüge, Maskenbälle, Musik und Tanz. Geschichte und praktische Informationen.",
        "keywords": ["Villacher Fasching", "Kärnten Brauchtum", "Faschingsfest Österreich", "Villach", "Alpen Fasching"],
    },
    {
        "num": 7,
        "name": "Narzissenfest Bad Aussee",
        "slug": "07-narzissenfest-bad-aussee",
        "region": "Steiermark",
        "bundesland": "Steiermark",
        "date": "31. Mai 2026",
        "location": "Bad Aussee, Ausseerland, Steiermark",
        "reading_time": "11 Min.",
        "category": "Brauchtum & Tradition",
        "subtitle": "Europas größtes Blumenfest: Über 4 Millionen Narzissen verwandeln einen See in eine Blütenkrone",
        "intro": "Das Narzissenfest von Bad Aussee ist das größte Blumenfest Europas und ein Fest der Natur in ihrer reinsten Form. Anfang Juni verwandeln sich die Wiesen rund um Bad Aussee in ein Meer aus weißen und gelben Narzissen. Der Höhepunkt des Festes ist die Seeparade: Tonnen von Narzissen werden zu kunstfremde Floats verarbeitet und auf dem Altaussee-See entlang gezogen. Es ist ein Fest, das die Kultur mit der Natur verbindet, das Handwerk mit der Botanik vereint. Das Narzissenfest zieht jährlich über 100.000 Besucher an und ist ein Muss für jeden, der Blütenpracht und alpine Tradition kombiniert haben möchte.",
        "key_facts": [
            ("Termin", "31. Mai - 1. Juni 2026"),
            ("Ort", "Bad Aussee, Ausseerland, Steiermark"),
            ("Art", "Blumenfest mit Seeparade"),
            ("Eintritt", "Kostenlos, Seeparade 10-25 EUR"),
            ("Besucher", "100.000+ Besucher pro Jahr"),
            ("Blumen", "4 Millionen Narzissen pro Fest"),
        ],
        "stats": [("4 Millionen", "Narzissen im Fest"), ("100.000+", "Besucher"), ("10 km", "Seeparade mit Floats")],
        "hero_image": "https://images.unsplash.com/photo-1508193638397-1c4234db14d8?w=1800&q=80&auto=format&fit=crop",
        "fullbleed_image": "https://images.unsplash.com/photo-1490750967868-88aa4f44baee?w=1800&q=80&auto=format&fit=crop",
        "history_title": "Von der wilden Narzissenwiese zum europäischen Blumenfest",
        "history_text": "Das Ausseerland ist berühmt für seine natürlichen Narzissenwiesen. Diese gelben und weißen Blüten wachsen wild in den Mooren und Wiesen um Bad Aussee, ein Phänomen, das es sonst in dieser Form in Europa kaum gibt. Die Idee, ein Fest rund um diese Blüten zu veranstalten, entstand erst in der Mitte des 20. Jahrhunderts.\n\nSeit 1952 findet das Narzissenfest jährlich statt (mit Ausnahmen während Krisen). Es ist ein Fest, das Kultur und Natur verbindet: Die Floats werden in Handarbeit aus Blüten zusammengestellt, ein Prozess, der hunderte von Stunden dauert. Das Fest wurde immer größer, bis es heute das größte Blumenfest Europas ist.",
        "history_timeline": [
            ("1800er", "Entdeckung der Narzissenwiesen durch Botaniker"),
            ("1952", "Erste Narzissenparade auf dem Altaussee-See"),
            ("1970er", "Expansion zu mehreren Tagen Festivalprogramm"),
            ("1990er", "Internationaler Ruhm, über 100.000 Besucher"),
            ("Heute", "Europas größtes Blumenfest mit 4 Millionen Narzissen"),
        ],
        "fullbleed_caption": "Narzissenfest-Float: Künstlerisch arrangierte Blüten auf dem Altaussee-See.",
        "traditions_title": "Die Handkunst der Floats und die Narzissen-Kultur",
        "traditions_text": "Ein Narzissenfest-Float ist nicht einfach eine Blumen-Dekoration — es ist ein Kunstwerk. Teams von Floristen und Handwerkern arbeiten für Wochen, um aus hunderten von Narzissen Figuren, Muster und Szenen zu schaffen. Die Floats sind leichte, schwimmfähige Strukturen, auf denen die Blüten in kunstvollen Arrangements angebracht werden.\n\nDie Narzissen selbst sind Teil der Tradition: Die sogenannten Alpen-Narzissen (Narcissus pseudonarcissus) wachsen wild in den Mooren und Wiesen. Ihre Ernte und Verwendung ist an Traditionen gebunden — nur bestimmte Bestände werden geerntet, andere bleiben für die Natur.",
        "interlude_quote": "Das Narzissenfest ist eine Feier der Vergänglichkeit — Millionen von Blüten blühen für einen Moment, um dann welk zu werden.",
        "program_title": "Programm & Höhepunkte des Festes",
        "program": [
            ("31. Mai 09:00", "Eröffnungsfeier im Zentrum", "Offizielle Begrüßung und erste Aktivitäten in Bad Aussee."),
            ("31. Mai 14:00", "Kleine Seeparade", "Erste Floats werden auf dem See gezogen."),
            ("1. Juni 10:00", "Große Narzissenparade", "Die Hauptveranstaltung mit den prächtigsten Floats."),
            ("1. Juni 14:00", "Blumen-Märkte und Verkostung", "Lokale Händler verkaufen Narzissen und Ausseer Spezialitäten."),
            ("1. Juni 18:00", "Abschlusskonzert", "Musik und Tanz im Zentrum von Bad Aussee."),
        ],
        "gallery": [
            ("Narzissen-Float mit künstlerisch arrangierten Blüten auf dem Wasser.", "https://images.unsplash.com/photo-1508193638397-1c4234db14d8?w=800&q=80&auto=format&fit=crop"),
            ("Wilde Narzissenwiese in der Ausseer Landschaft — die natürliche Quelle.", "https://images.unsplash.com/photo-1490750967868-88aa4f44baee?w=800&q=80&auto=format&fit=crop"),
            ("Tausende von Besuchern säumen die Seeufer beim Umzug.", "https://images.unsplash.com/photo-1470770903676-69b98201ea1c?w=800&q=80&auto=format&fit=crop"),
        ],
        "practical_info": [
            ("Anreise mit der Bahn", "ÖBB Wien-Bad Aussee ca. 2,5 Stunden.", "🚂"),
            ("Anreise mit dem Auto", "Von Wien ca. 250 km über A2/S3 ins Ausseerland.", "🚗"),
            ("Juni-Wetter", "10-20°C, Regen möglich, Regenschutz und Sonnenschutz.", "🌡️"),
            ("Unterkunft in Bad Aussee", "Kurort mit vielen Hotels und Pensionen, frühzeitig buchen.", "🏨"),
            ("Seeufer-Standplätze", "Altaussee-Seeufer bietet beste Sicht auf die Parade.", "📍"),
            ("Blumen-Käufe", "Narzissen und andere Blüten am Markt erhältlich.", "🌸"),
        ],
        "cta_text": "Alle Natur-Feste und Blumen-Events Österreichs",
        "seo_title": "Narzissenfest Bad Aussee 2026 — Europas größtes Blumenfest",
        "seo_description": "Narzissenfest Bad Aussee: 4 Millionen Narzissen, 100.000+ Besucher, 31. Mai - 1. Juni 2026. Seeparade mit kunstfremde Floats, Geschichte und praktische Tipps.",
        "keywords": ["Narzissenfest Bad Aussee", "Blumenfest Österreich", "Narzissenwiese Steiermark", "Altaussee See", "Ausseerland Tradition"],
    },
    {
        "num": 8,
        "name": "Samsonumzug Lungau",
        "slug": "08-samsonumzug-lungau",
        "region": "Salzburg",
        "bundesland": "Salzburg",
        "date": "15. Mai 2026",
        "location": "Lungau, Salzburg, Österreich",
        "reading_time": "11 Min.",
        "category": "Brauchtum & Tradition",
        "subtitle": "Eine Riesenfigur erhebt sich: Der Samsonumzug mit seiner 14 Meter hohen Holzfigur, UNESCO-Welterbe",
        "intro": "Der Samsonumzug des Lungaus ist einer der eindrucksvollsten Prozessionen Österreichs — eine UNESCO-Liste-Tradition, bei der eine massiv-holzerne Samson-Figur von etwa 14 Metern Höhe und mehreren Tonnen Gewicht durch kleine Berg-Dörfer getragen wird. Der Samson war biblisch ein Symbol der Kraft und des Widerstandes. In der Lungauer Tradition wird die Figur als Wächter verstanden, als Symbol des Schutzes über das Tal. Der Umzug findet alle sieben Jahre statt und ist ein Spektakel, bei dem hunderte von Männern die gigantische Figur tragen, während die ganze Region zusammenkommt, um dieses einzigartige Fest zu feiern.",
        "key_facts": [
            ("Nächster Termin", "15. Mai 2026 (alle 7 Jahre)"),
            ("Ort", "Lungau-Region, Salzburg"),
            ("Art", "Samson-Prozession, UNESCO-Welterbe"),
            ("Eintritt", "Kostenlos"),
            ("Teilnehmer", "Hunderte von Trägern, tausende Zuschauer"),
            ("Samson-Figur", "14 Meter hoch, mehrere Tonnen Holz"),
        ],
        "stats": [("7 Jahre", "Zyklus zwischen den Ereignissen"), ("14 Meter", "Höhe der Samson-Figur"), ("500+ kg", "Gewicht des Holzes")],
        "hero_image": "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=1800&q=80&auto=format&fit=crop",
        "fullbleed_image": "https://images.unsplash.com/photo-1482192505345-5655af888cc4?w=1800&q=80&auto=format&fit=crop",
        "history_title": "Die Samson-Figur: Ein Symbol der Kraft seit Generationen",
        "history_text": "Die Ursprünge des Lungauer Samsonumzugs sind im christlichen Mittelalter zu finden, als die biblische Gestalt des Samson als Metapher für Kraft und Widerstand verwendet wurde. Im Lungau, einem alpinen Bergtal mit einer starken Gemeinschaftskultur, wurde die Samson-Figur zum Schutzpatron des Tals.\n\nDie erste dokumentierte Erwähnung stammt aus dem 17. Jahrhundert. Seitdem wird die Samson-Figur aus lokalem Holz gefertigt und alle sieben Jahre in einem feierlichen Umzug durch die Dörfer des Lungaus getragen. Die Tradition wurde UNESCO-Welterbe, da sie ein uraltes Beispiel für kollektive Kraft und kommunales Handeln darstellt.",
        "history_timeline": [
            ("1600er", "Erste Erwähnungen von Samson-Figuren in alpinen Tälern"),
            ("1800er", "Etablierung als 7-Jahres-Zyklus Ereignis"),
            ("1900er", "Standardisierung der Figur und des Umzug-Ablaufs"),
            ("2008", "UNESCO-Eintrag für das Samsonumzug-Brauchtum"),
            ("2026", "Nächster großer Samsonumzug"),
        ],
        "fullbleed_caption": "Die Samson-Figur: 14 Meter hohes Holz-Kunstwerk, getragen von hunderten Männern.",
        "traditions_title": "Die Macht der Gemeinschaft: Wie man einen 14-Meter-Samson trägt",
        "traditions_text": "Der Samsonumzug ist nicht nur eine religiöse oder kulturelle Veranstaltung — er ist ein Akt der kollektiven Kraft. Hunderte von Männern aus der ganzen Lungau-Region treffen sich, um die Samson-Figur zu tragen. Die Figur sitzt auf einem großen Holzrahmen, der von vielen Trägern gleichzeitig hochgehoben und getragen wird.\n\nDas Tragen erfordert Koordination, Kraft und Ausdauer. Der Umzug folgt einer festgelegten Route durch die Dörfer des Lungaus: Sankt Margarethen, Zederhaus, Mariapfarr und andere. An jedem Dorf wird halt gemacht, es gibt Reden und Musik. Der Samson wird als Beschützer gefeiert.",
        "interlude_quote": "Der Samsonumzug zeigt, dass Gemeinschaft Kraft ist — wenn wir zusammenkommen, können wir alles tragen.",
        "program_title": "Programm & Höhepunkte des Umzugs",
        "program": [
            ("10:00", "Sammlung in Lungau", "Hunderte von Männern treffen sich zum Umzug."),
            ("11:00", "Feierliche Erhebung des Samson", "Mit Musik und Gesang wird die Figur hochgehoben."),
            ("12:00", "Prozession durch Sankt Margarethen", "Der Samson wird durch das erste Dorf getragen."),
            ("14:00", "Pause und Mahlzeit", "Gemeinsames Essen und Trinken unterwegs."),
            ("16:00+", "Weitere Dörfer und Finale", "Der Samson wird durch mehrere Dörfer getragen, finale Feier."),
        ],
        "gallery": [
            ("Die Samson-Figur von unten: Eine Perspektive der Größe und Macht.", "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800&q=80&auto=format&fit=crop"),
            ("Hunderte von Männern tragen die Figur auf ihren Schultern.", "https://images.unsplash.com/photo-1482192505345-5655af888cc4?w=800&q=80&auto=format&fit=crop"),
            ("Das Lungauer Tal mit seinen traditionellen Dörfern und Bergen.", "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800&q=80&auto=format&fit=crop"),
        ],
        "practical_info": [
            ("Anreise mit der Bahn", "ÖBB Salzburg-Lungau ca. 2 Stunden, dann lokale Busse.", "🚂"),
            ("Anreise mit dem Auto", "Von Salzburg ca. 80 km über die B99 ins Lungau.", "🚗"),
            ("Mai-Wetter", "8-15°C, Regen möglich, Regenschutz und warme Kleidung.", "🌡️"),
            ("Unterkunft im Lungau", "Kleine Ortschaften mit Gasthöfen und Pensionen.", "🏨"),
            ("Beste Positionen", "Ortsplätze in den Dörfern für beste Sichtlinie.", "📍"),
            ("Zugang für Träger", "Es gibt Gelegenheiten für Besucher, die Figur kurz zu tragen.", "💪"),
        ],
        "cta_text": "Alle UNESCO-Brauchtümer Salzburgs entdecken",
        "seo_title": "Samsonumzug Lungau 2026 — UNESCO-Tradition mit 14-Meter-Holzfigur",
        "seo_description": "Samsonumzug Lungau: UNESCO-Welterbe, 14 Meter hohes Kunstwerk, 15. Mai 2026. Geschichte, Tradition der Gemeinschaftskraft und praktische Informationen.",
        "keywords": ["Samsonumzug Lungau", "UNESCO Tradition Salzburg", "Gemeinschaftsbrauch", "Lungau Region", "Alpenkultur"],
    },
    {
        "num": 9,
        "name": "Gauder Fest Zell am Ziller",
        "slug": "09-gauder-fest-zell",
        "region": "Tirol",
        "bundesland": "Tirol",
        "date": "2. Mai 2026",
        "location": "Zell am Ziller, Zillertal, Tirol",
        "reading_time": "11 Min.",
        "category": "Brauchtum & Tradition",
        "subtitle": "Österreichs ältestes Folklorefest: Über 150 Jahre Musik, Tanz und ländliche Tradition im Zillertal",
        "intro": "Das Gauder Fest in Zell am Ziller ist das älteste noch regelmäßig veranstaltete Folklorefest in Österreich — eine Tradition, die seit 1871 ununterbrochen fortbesteht. Der Name \"Gauder\" stammt vom Gauder, einem Tiroler Hochplateau. Das Fest ist nicht spektakulär im Sinne von riesigen Umzügen oder massiven Zuschauerzahlen — es ist vielmehr eine Feier authentischer ländlicher Kultur, echter Musik, echter Tracht und echter Tradition. Hunderte von Musikern, Tänzern und Trachtentragenden aus dem ganzen Zillertal kommen zusammen, um ihre Kultur zu präsentieren und zu zelebrieren.",
        "key_facts": [
            ("Termin", "2. Mai 2026"),
            ("Ort", "Zell am Ziller, Zillertal, Tirol"),
            ("Art", "Folklorefest, seit 1871"),
            ("Eintritt", "Kostenlos, Speisen und Getränke separat"),
            ("Teilnehmer", "Hunderte von Tänzern und Musikern"),
            ("Tradition seit", "1871, ohne Unterbrechung"),
        ],
        "stats": [("155 Jahre", "Geschichte seit 1871"), ("Hunderte", "Teilnehmer aus dem Zillertal"), ("8 Stunden", "Festdauer")],
        "hero_image": "https://images.unsplash.com/photo-1515488764276-beab7607c1e6?w=1800&q=80&auto=format&fit=crop",
        "fullbleed_image": "https://images.unsplash.com/photo-1470770903676-69b98201ea1c?w=1800&q=80&auto=format&fit=crop",
        "history_title": "155 Jahre Kontinuität: Das älteste Volksfest Österreichs",
        "history_text": "Das Gauder Fest wurde 1871 gegründet, zu einer Zeit, als das Austro-Ungarische Reich noch bestand und die Tiroler Identität über Tracht und Musik definiert wurde. Der Gründer, Leopold Gauder, war ein Bürgermeister von Zell am Ziller, der erkannt hatte, dass die traditionelle Kultur bewahrt werden musste.\n\nÜber 155 Jahre hinweg — durch zwei Weltkriege, wirtschaftliche Krisen und gesellschaftliche Umwälzungen — wurde das Fest kontinuierlich abgehalten. Dies macht es zum ältesten noch regelmäßig veranstalteten Folklorefest Österreichs. Das Fest hat sich kaum verändert: Es geht um echte Musik, echte Tänze, echte Trachten und echte Geselligkeit.",
        "history_timeline": [
            ("1871", "Gründung des Gauder Fests durch Leopold Gauder"),
            ("1900", "Etablierung als Tradition im ganzen Zillertal"),
            ("1945", "Unterbrechung durch Kriegsjahre, schneller Wiederaufbau"),
            ("1970er", "Moderne Ausdehnung, Anerkennung als kulturelles Erbe"),
            ("Heute", "Das älteste Folklorefest Österreichs mit hunderten Teilnehmern"),
        ],
        "fullbleed_caption": "Gauder Fest: Tänzer und Musiker in traditioneller Tracht.",
        "traditions_title": "Echte Musik, echte Tänze, echte Tracht — Die Authentizität des Gauder Fests",
        "traditions_text": "Das Gauder Fest ist nicht choreographiert wie viele moderne Volksfeste. Die Musik wird live gespielt — Zither, Harmonika, Bläser — von lokalen Musikanten aus dem Zillertal. Die Tänze sind echt: Ländler, Schuhplattler und andere traditionelle Tänze, ausgeführt von Menschen, die diese Tänze ihr Leben lang praktizieren.\n\nDie Trachten sind authentisch: Frauen in Dirndln, Männer in Lederhosen, alle mit Stolz getragen. Es gibt keine Kostüme — nur Menschen in ihrer besten Tracht. Das Fest ist ein Ort, wo Generationen zusammenkommen und die Kultur weitergegeben wird.",
        "interlude_quote": "Das Gauder Fest ist nicht für Touristen gemacht — es ist für die, die die Musik und den Tanz lieben.",
        "program_title": "Programm & Höhepunkte des Tages",
        "program": [
            ("09:00", "Eröffnungsparade", "Hunderte von Teilnehmern ziehen durch Zell am Ziller."),
            ("10:00", "Hauptfestplatz-Eröffnung", "Mit Musik und Begrüßung beginnt das Fest."),
            ("11:00-15:00", "Kontinuierliche Musik und Tänze", "An verschiedenen Plätzen spielen Musikgroups und Tänzer tanzen."),
            ("15:00", "Gemeinschaftliche Mahlzeit", "Traditionelle Zillertal-Spezialitäten werden serviert."),
            ("17:00+", "Abendmusik und Ausklingen", "Das Fest endet mit Abendmusik und geselligem Beisammensein."),
        ],
        "gallery": [
            ("Zillertal-Trachten-Tänzer in voller Pracht beim Ländler.", "https://images.unsplash.com/photo-1515488764276-beab7607c1e6?w=800&q=80&auto=format&fit=crop"),
            ("Traditionelle Musikanten mit Zither und Harmonika.", "https://images.unsplash.com/photo-1470770903676-69b98201ea1c?w=800&q=80&auto=format&fit=crop"),
            ("Der Marktplatz von Zell am Ziller: Zentrum des Festes.", "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80&auto=format&fit=crop"),
        ],
        "practical_info": [
            ("Anreise mit der Bahn", "ÖBB Innsbruck-Zell am Ziller ca. 1,5 Stunden.", "🚂"),
            ("Anreise mit dem Auto", "Von Innsbruck ca. 40 km über die B169 ins Zillertal.", "🚗"),
            ("Mai-Wetter", "10-18°C, sonnig und trocken, Sonnenschutz empfohlen.", "🌡️"),
            ("Unterkunft im Zillertal", "Viele Hotels und Gasthöfe, frühzeitige Buchung ratsam.", "🏨"),
            ("Festplatz-Standplätze", "Marktplatz kostenlos, beste Sicht ohne Reservierung.", "📍"),
            ("Kulinarisches", "Zillertal-Spezialitäten wie Kasnocken und Erdäpfelpuffer.", "🍲"),
        ],
        "cta_text": "Alle Tiroler Folklorefeste entdecken",
        "seo_title": "Gauder Fest 2026 — Österreichs ältestes Folklorefest im Zillertal",
        "seo_description": "Gauder Fest Zell am Ziller: 155 Jahre Tradition seit 1871, 2. Mai 2026. Authentische Musik, Tänze und Trachten aus dem Zillertal.",
        "keywords": ["Gauder Fest Zell am Ziller", "ältestes Folklorefest Österreich", "Zillertal Tradition", "Tiroler Musik und Tanz", "Alpentradition"],
    },
    {
        "num": 10,
        "name": "Villacher Kirchtag",
        "slug": "10-villacher-kirchtag",
        "region": "Kärnten",
        "bundesland": "Kärnten",
        "date": "21. August 2026",
        "location": "Villach, Kärnten, Österreich",
        "reading_time": "11 Min.",
        "category": "Brauchtum & Tradition",
        "subtitle": "Eine Woche voller Tradition: Kärntens größtes Volksfest mit Handwerk, Musik und ländlicher Kultur",
        "intro": "Der Villacher Kirchtag ist das größte Volksfest Kärntens — eine ganze Woche lang verwandelt sich Villach in ein Festival ländlicher Kultur, Musik und Tradition. Im Gegensatz zum Villacher Fasching im Februar, der vom Faschings-Chaos geprägt ist, ist der August-Kirchtag ein Fest der bodenständigen Kultur: Handwerk wird präsentiert, traditionelle Musik ertönt überall, lokale Speisen werden gegessen, Trachten werden getragen. Es ist ein Fest, das Generationen verbindet und die ländliche Identität Kärntens zelebriert.",
        "key_facts": [
            ("Termin", "21. - 30. August 2026 (10 Tage)"),
            ("Ort", "Villach, Kärnten"),
            ("Art", "Volksfest mit Handwerk und Tradition"),
            ("Eintritt", "Kostenlos, Veranstaltungen separat"),
            ("Besucher", "200.000+ während der Woche"),
            ("Tradition seit", "Mindestens 300 Jahre dokumentiert"),
        ],
        "stats": [("300 Jahre", "dokumentierte Geschichte"), ("200.000+", "Besucher"), ("10 Tage", "Festdauer")],
        "hero_image": "https://images.unsplash.com/photo-1529333166437-7750a6dd5a70?w=1800&q=80&auto=format&fit=crop",
        "fullbleed_image": "https://images.unsplash.com/photo-1473448912268-2022ce9509d8?w=1800&q=80&auto=format&fit=crop",
        "history_title": "Kirchtag: Vom religiösen Fest zur ländlichen Kulturfeier",
        "history_text": "Der Kirchtag hat seine Wurzeln in der katholischen Kirchen-Tradition: Der Gedenktag des Kirchenpatrons war Anlass für Feste und Versammlungen. In Villach entwickelte sich aus diesem religiösen Anlass ein säkulares Volksfest, das die ganze Kultur eines ländlichen Tals repräsentiert.\n\nDer Villacher Kirchtag ist mindestens 300 Jahre alt und hat sich über die Jahrhunderte weniger verändert als andere Volksfeste. Er bleibt eng mit der ländlichen Handwerks- und Zunft-Tradition verbunden. Heute ist er das größte Volksfest Kärntens und zieht hundertausende von Besuchern an.",
        "history_timeline": [
            ("1700er", "Erste Erwähnungen von Kirchtags-Feiern in Villach"),
            ("1850er", "Expansion zu mehrtägigem Fest"),
            ("1920er", "Etablierung als größtes Volksfest Kärntens"),
            ("1960er-1980er", "Weitere Ausdehnung auf zwei Wochen"),
            ("Heute", "Villacher Kirchtag mit 200.000+ Besuchern und 10 Tagen Programm"),
        ],
        "fullbleed_caption": "Villacher Kirchtag: Traditionelle Handwerker präsentieren ihre Kunst.",
        "traditions_title": "Handwerk, Musik und Bodenständigkeit: Die Kultur des Kirchtags",
        "traditions_text": "Der Villacher Kirchtag ist ein Fest des Handwerks: Tischler, Schmied, Weber, Bäcker — traditionelle Handwerker zeigen ihre Fähigkeiten. In Ständen und Werkstätten können Besucher zuschauen, wie diese Kunsthandwerke praktiziert werden. Es ist eine Form der Wissensvermittlung, eine Verbindung zur Vergangenheit.\n\nDie Musik ist live und überall: Blaskapellen, Zither-Spieler, Tanzgruppen in Tracht. Das Essen ist regional: Kärntnische Kasnockn, Erdäpfelpuffer, Fleisch vom Grill. Es ist kein inszeniertes Festival, sondern eine organische Feier von Kultur, die in der Region lebt.",
        "interlude_quote": "Der Villacher Kirchtag ist wie ein Tag im Leben eines Kärntners vor hundert Jahren — lebendig gewordene Geschichte.",
        "program_title": "Programm & Höhepunkte der Woche",
        "program": [
            ("21. August", "Eröffnungstag mit Parade und Segnung", "Der Kirchtag wird mit feierlicher Eröffnung gestartet."),
            ("22.-25. August", "Handwerksbörse und Musikveranstaltungen", "Täglich unterschiedliche Handwerke und Musik."),
            ("26. August", "Großes Trachten-Fest", "Hunderte in traditioneller Tracht auf dem Marktplatz."),
            ("27.-29. August", "Spezial-Vorführungen und Verkostungen", "Kärnter Spezialitäten und traditionelle Künste."),
            ("30. August", "Abschluss und Feuerwerk", "Der Kirchtag endet mit traditionellem Feuerwerk."),
        ],
        "gallery": [
            ("Handwerker präsentieren traditionelles Kunsthandwerk beim Kirchtag.", "https://images.unsplash.com/photo-1529333166437-7750a6dd5a70?w=800&q=80&auto=format&fit=crop"),
            ("Herbstliche Landschaft rund um Villach mit Bergen im Hintergrund.", "https://images.unsplash.com/photo-1473448912268-2022ce9509d8?w=800&q=80&auto=format&fit=crop"),
            ("Trachten-Träger beim Fest: Traditionelle Kleidung in voller Pracht.", "https://images.unsplash.com/photo-1515488764276-beab7607c1e6?w=800&q=80&auto=format&fit=crop"),
        ],
        "practical_info": [
            ("Anreise mit der Bahn", "ÖBB Wien-Villach ca. 6 Stunden direkte Verbindung.", "🚂"),
            ("Anreise mit dem Auto", "Von Wien ca. 380 km über die A2 nach Villach.", "🚗"),
            ("August-Wetter", "15-25°C, sonnig, Sonnenschutz und lockere Kleidung.", "🌡️"),
            ("Unterkunft in Villach", "Hotels und Gasthöfe, während des Kirchtags ausgebucht, frühzeitig buchen.", "🏨"),
            ("Festplatz-Standplätze", "Zentrum von Villach, kostenlos zugänglich.", "📍"),
            ("Kulinarisches", "Kärnter Spezialitäten wie Kasnockn und Erdäpfelpuffer überall.", "🍲"),
        ],
        "cta_text": "Alle Kärntner Volksfeste erleben",
        "seo_title": "Villacher Kirchtag 2026 — Kärntens größtes Volksfest im August",
        "seo_description": "Villacher Kirchtag: 10-Tage Volksfest mit Handwerk, Musik und Tracht, 21.-30. August 2026. Tradition seit 300 Jahren, 200.000+ Besucher.",
        "keywords": ["Villacher Kirchtag", "Kärntner Volksfest", "traditionelles Handwerk", "ländliche Kultur Kärnten", "August Fest"],
    },
    {
        "num": 11,
        "name": "Aufsteirern Graz",
        "slug": "11-aufsteirern-graz",
        "region": "Steiermark",
        "bundesland": "Steiermark",
        "date": "7. Juni 2026",
        "location": "Graz, Steiermark",
        "reading_time": "10 Min.",
        "category": "Brauchtum & Tradition",
        "subtitle": "Urbane Volksfestival im Herzen der Steiermark: Aufsteirern feiert Musik, Tracht und Landkultur in der Stadt",
        "intro": "Aufsteirern ist ein modernes Volksfest in Österreichs Kulturhauptstadt Graz — ein Festival, das die ländliche Kultur der Steiermark in die Stadt bringt und damit eine Brücke zwischen urban und rural schlägt. Jeden Juni verwandelt sich das Zentrum von Graz in ein Festival voller Musik, Tanz, Tracht und steirischer Kulinarik. Im Gegensatz zu traditionellen Volksfesten ist Aufsteirern jung, lebendig, offen für Experimente — es bewahrt die Tradition, aber interpretiert sie neu.",
        "key_facts": [
            ("Termin", "7. Juni 2026"),
            ("Ort", "Graz, Steiermark"),
            ("Art", "Urbanes Volksfestival"),
            ("Eintritt", "Kostenlos, Speisen und Getränke separat"),
            ("Besucher", "50.000+ pro Jahr"),
            ("Tradition seit", "Seit ca. 2000er Jahre etabliert"),
        ],
        "stats": [("20+ Jahre", "moderne Tradition"), ("50.000+", "Besucher"), ("100+", "Stände und Veranstaltungen")],
        "hero_image": "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1800&q=80&auto=format&fit=crop",
        "fullbleed_image": "https://images.unsplash.com/photo-1515488764276-beab7607c1e6?w=1800&q=80&auto=format&fit=crop",
        "history_title": "Urban Tradition: Aufsteirern und die Neu-Erfindung von Volkkultur",
        "history_text": "Aufsteirern ist ein relativ junges Festival — es entstanden Mitte der 2000er Jahre als Antwort auf die Frage: Wie kann ländliche Kultur in einer modernen Stadt präsent sein? Die Gründer erkannten, dass Volksfeste nicht nur auf dem Land stattfinden mussten, sondern dass die Stadt eine neue Heimat für traditionelle Kultur sein konnte.\n\nDas Festival wuchs schnell, weil es weder kitschig noch konservativ war. Es bot lokale Musiker, echte steirische Speisen, Trachtenträger — aber auch junge, experimentelle Künstler, die die Tradition reinterpretierten. Aufsteirern ist heute eines der lebendigsten urbanen Volksfeste Österreichs.",
        "history_timeline": [
            ("2000er", "Ursprungsidee für urbanes Volksfest"),
            ("2005", "Erste Veranstaltung im Zentrum von Graz"),
            ("2010er", "Ausbau zu 50.000+ Besuchern"),
            ("2015", "Internationaler Ruf, Besucher aus ganz Österreich"),
            ("Heute", "Etabliertes urbanes Volksfestival mit modernem Anspruch"),
        ],
        "fullbleed_caption": "Aufsteirern: Trachten-Träger und urbane Atmosphäre vereint.",
        "traditions_title": "Urban trifft Rural: Tradition im 21. Jahrhundert",
        "traditions_text": "Aufsteirern ist ein Fest, das Tradition bewahrt und gleichzeitig neu erfindet. Es gibt traditionelle Stände: Dirndl und Lederhosen-Verkäufer, Musiker mit Zither und Harmonika, traditionelle Speisen. Aber es gibt auch junge DJ-Sets, experimentelle Musik-Acts, urbane Künstler.\n\nDie steirische Kulinarik ist zentral: Kasnockn, Erdäpfelpuffer, Kürbiskernöl — echte steirische Spezialitäten. Die Musik reicht von traditioneller Blasmusik bis zu modernem Jazz und elektronischer Musik. Es ist ein Fest, das sagt: Tradition ist nicht konservativ, sondern lebendig.",
        "interlude_quote": "Aufsteirern zeigt: Volksfeste können Stadt sein, können modern sein, und dabei immer noch ehrlich und tiefverwurzelt.",
        "program_title": "Programm & Highlights des Festivals",
        "program": [
            ("10:00", "Eröffnung auf dem Hauptplatz", "Mit traditioneller Musik und Begrüßung."),
            ("11:00-13:00", "Handwerksbörse und Markt", "Lokale Handwerker und Verkäufer zeigen ihre Produkte."),
            ("13:00-15:00", "Kulinarische Station", "Steirische Spezialitäten können probiert werden."),
            ("15:00-18:00", "Musik und Tanz im ganzen Zentrum", "Verschiedene Bühnen mit traditioneller und moderner Musik."),
            ("18:00+", "Abendveranstaltungen und Feiern", "Das Festival klingt mit Musik und Geselligkeit aus."),
        ],
        "gallery": [
            ("Grazer Altstadt mit traditionellen Häusern beim Aufsteirern.", "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80&auto=format&fit=crop"),
            ("Trachten-Träger in urbaner Umgebung beim Festival.", "https://images.unsplash.com/photo-1515488764276-beab7607c1e6?w=800&q=80&auto=format&fit=crop"),
            ("Musikanten und Tänzer auf einer Bühne im Zentrum.", "https://images.unsplash.com/photo-1470770903676-69b98201ea1c?w=800&q=80&auto=format&fit=crop"),
        ],
        "practical_info": [
            ("Anreise mit der Bahn", "ÖBB Wien-Graz ca. 2 Stunden direkte Verbindung.", "🚂"),
            ("Anreise mit dem Auto", "Von Wien ca. 180 km über die A2 nach Graz.", "🚗"),
            ("Juni-Wetter", "15-25°C, sonnig, lockere Kleidung und Sonnenschutz.", "🌡️"),
            ("Unterkunft in Graz", "Kulturhauptstadt mit vielen Hotels, gute Auswahl im Juni.", "🏨"),
            ("Zentrum-Standplätze", "Grazer Altstadt komplett zugänglich, kostenlos.", "📍"),
            ("Kulinarisches", "Steirische Kasnockn, Kürbiskernöl-Produkte, lokale Biere.", "🍲"),
        ],
        "cta_text": "Alle steirischen Volksfeste entdecken",
        "seo_title": "Aufsteirern Graz 2026 — Urbanes Volksfestival im Herzen der Steiermark",
        "seo_description": "Aufsteirern Graz: Modernes Volksfestival mit steirischer Tradition, Musik und Kulinarik, 7. Juni 2026 in Graz. 50.000+ Besucher.",
        "keywords": ["Aufsteirern Graz", "steirisches Volksfest", "urbane Tradition", "Graz Kultur", "steirische Spezialitäten"],
    },
    {
        "num": 12,
        "name": "Salzburger Bauernherbst",
        "slug": "12-salzburger-bauernherbst",
        "region": "Salzburg",
        "bundesland": "Salzburg",
        "date": "20. September 2026",
        "location": "Salzburg, Österreich",
        "reading_time": "11 Min.",
        "category": "Brauchtum & Tradition",
        "subtitle": "Die Ernte feiern: Salzburgs größtes Herbstfest mit ländlichen Traditionen und Feldfrüchten",
        "intro": "Der Salzburger Bauernherbst ist das größte Herbst- und Ernte-Fest Österreichs — ein Festival, das die Landwirtschaft und die Ernte zelebriert, die für Salzburg und das Land als Ganzes überlebenswichtig sind. Anfang Oktober verwandelt sich Salzburg in ein Fest voller Feldfrüchte, Blumenkronen und ländlicher Musik. Der Bauernherbst ist weniger ein historisches Brauchtum als vielmehr eine Schöpfung des 20. Jahrhunderts, aber er verkörpert Wahrheiten einer agrarischen Kultur, die über tausend Jahre alt ist. Es ist ein Fest, das Dankbarkeit ausdrückt — Dankbarkeit für die Ernte, für die Erde, für die Bauern, die diese Ernte möglich machen.",
        "key_facts": [
            ("Termin", "20. September - 15. Oktober 2026 (4 Wochen)"),
            ("Ort", "Salzburg, Österreich"),
            ("Art", "Herbstfest und Ernte-Feier"),
            ("Eintritt", "Kostenlos, Speisen und Getränke separat"),
            ("Besucher", "150.000+ während der Wochen"),
            ("Tradition seit", "Seit 1960er Jahre etabliert"),
        ],
        "stats": [("60+ Jahre", "moderne Tradition"), ("150.000+", "Besucher insgesamt"), ("4 Wochen", "Festdauer")],
        "hero_image": "https://images.unsplash.com/photo-1473448912268-2022ce9509d8?w=1800&q=80&auto=format&fit=crop",
        "fullbleed_image": "https://images.unsplash.com/photo-1529333166437-7750a6dd5a70?w=1800&q=80&auto=format&fit=crop",
        "history_title": "Bauernherbst: Ein Fest der Dankbarkeit für die Ernte",
        "history_text": "Der Salzburger Bauernherbst ist eine moderne Erfindung, entstanden in den 1960er Jahren als die Landwirtschaft in Salzburg noch dominant war. Bauern und Politiker erkannten, dass es wichtig war, die landwirtschaftliche Kultur zu zelebrieren und den Zusammenhang zwischen Stadt und Land zu bewahren.\n\nDas Fest wuchs schnell und wurde ein großes Event. Heute ist es eines der größten Herbstfeste Österreichs. Während andere Feste an historische Traditionen anknüpfen, ist der Bauernherbst ein Fest, das sich selbst schuf — und damit einen neuen Standard für Ernte-Feste setzte.",
        "history_timeline": [
            ("1960er", "Ursprungsidee für Ernte-Fest"),
            ("1965", "Erste große Bauernherbst-Veranstaltung"),
            ("1980er", "Ausbau zu mehrwöchigem Festival"),
            ("2000er", "Ausdehnung auf über 150.000 Besucher"),
            ("Heute", "Etabliertes Herbstfest mit nationaler Bedeutung"),
        ],
        "fullbleed_caption": "Salzburger Bauernherbst: Erntekränze aus Feldfrüchten und Blumen.",
        "traditions_title": "Ernte-Kränze, Feldfrüchte und Dankbarkeit: Die Kultur des Bauernherbsts",
        "traditions_text": "Der Salzburger Bauernherbst ist ein sinnliches Fest: Überall sind Feldfrüchte ausgestellt — Kürbisse, Äpfel, Birnen, Getreide, alles, was die Erde hervorbringt. Es gibt Ernte-Kränze: Große Kränze aus Blüten, Feldfrüchten und Getreide, die wochenlang das Fest dekorieren.\n\nDie Bauerschaft Salzburgs präsentiert ihre Produkte: Honig, Milchprodukte, Fleisch vom Bauernhof, Gemüse. Es gibt Vorführungen traditioneller Erntemethoden, Musik und Tänze, die die Liebe zur Erde ausdrücken. Das Fest ist ein Akt der Dankbarkeit — dafür, dass die Erde uns ernährt.",
        "interlude_quote": "Der Bauernherbst erinnert daran, dass alles, was wir essen, von der Arbeit der Bauern kommt.",
        "program_title": "Programm & Höhepunkte der vier Wochen",
        "program": [
            ("Woche 1", "Eröffnung und Ernte-Markt", "Große Markt mit Feldfrüchten und Bauernprodukten öffnet."),
            ("Woche 2", "Traditionelle Handwerksbörse", "Handwerker zeigen Verarbeitung von Feldfrüchten."),
            ("Woche 3", "Musik und Tanz im ganzen Zentrum", "Verschiedene Musikveranstaltungen mit ländlichen Themen."),
            ("Woche 3", "Bauern-Vorführungen", "Traditionelle Erntemethoden und Feldarbeit werden demonstriert."),
            ("Woche 4", "Abschluss und Dankesfest", "Das Fest endet mit großem Ernte-Dank-Gottesdienst und Feier."),
        ],
        "gallery": [
            ("Ernte-Kränze aus Feldfrüchten und Blumen im Zentrum.", "https://images.unsplash.com/photo-1473448912268-2022ce9509d8?w=800&q=80&auto=format&fit=crop"),
            ("Bauernprodukte auf dem Herbst-Markt: Kürbisse, Äpfel und Getreide.", "https://images.unsplash.com/photo-1529333166437-7750a6dd5a70?w=800&q=80&auto=format&fit=crop"),
            ("Salzburg Altstadt beim Bauernherbst mit Ernte-Dekoration.", "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80&auto=format&fit=crop"),
        ],
        "practical_info": [
            ("Anreise mit der Bahn", "ÖBB Wien-Salzburg ca. 2,5 Stunden direkte Verbindung.", "🚂"),
            ("Anreise mit dem Auto", "Von Wien ca. 300 km über die A1 nach Salzburg.", "🚗"),
            ("September-Oktober Wetter", "10-18°C, herbstlich, Regenschutz und warme Schichten.", "🌡️"),
            ("Unterkunft in Salzburg", "Kulturhauptstadt mit vielen Hotels, gutes Angebot.", "🏨"),
            ("Zentrum-Standplätze", "Salzburgs Altstadt komplett zugänglich und kostenlos.", "📍"),
            ("Kulinarisches", "Salzburger Spezialitäten, Bauernprodukte, Apfel-Kuchen, Mostsäfte.", "🍲"),
        ],
        "cta_text": "Alle Salzburger Volksfeste und Herbstfeste",
        "seo_title": "Salzburger Bauernherbst 2026 — Österreichs größtes Ernte-Fest im September",
        "seo_description": "Salzburger Bauernherbst: 4-Wochen Herbstfest mit Ernte-Markt, Bauernprodukten und ländlicher Kultur, 20. Sept. - 15. Okt. 2026. 150.000+ Besucher.",
        "keywords": ["Bauernherbst Salzburg", "Ernte-Fest Österreich", "ländliche Tradition Salzburg", "Herbstfest", "Bauernkultur"],
    },
]
