FESTIVALS_BATCH4 = [
    {
        "num": 31,
        "name": "Pinzgauer Tresterertanz",
        "slug": "31-pinzgauer-tresterertanz",
        "region": "Pinzgau",
        "bundesland": "Salzburg",
        "date": "Faschingdienstag (variabel)",
        "location": "Wald im Pinzgau, Salzburg",
        "reading_time": "10 Min.",
        "category": "Brauchtum & Tradition",
        "subtitle": "Mysterienvolle Maskenreigen in den schneebedeckten Alpen",
        "intro": "Der Pinzgauer Tresterertanz ist eine der ältesten und geheimnissvollsten Faschingsbräuche Salzburgs. Mit wilden Sprüngen, durchdringenden Rufen und phantastischen Holzmasken verwandeln sich die Tänzer in übernatürliche Wesen. Dieser uralte Brauch reicht in vorchristliche Zeiten zurück und symbolisiert den Kampf zwischen Winter und Frühling. Die Tresterrer – junge Männer in aufwändigen Kostümen aus Stroh, Fell und Lappen – ziehen durch die Bergdörfer und vertreiben damit symbolisch die bösen Geister des Winters. Heute ist dieser ursprüngliche und fesselnde Brauch ein Fenster in die alpine Volkstradition Österreichs.",
        "key_facts": [
            ("Ursprung", "Vorchristliche Wintervertreibungsrituale"),
            ("Besonderheit", "Handgefertigte Holzmasken mit übernatürlichen Zügen"),
            ("Teilnehmer", "Überwiegend junge Männer in traditionellen Gruppen"),
            ("Dauer", "Faschingszeit mit Höhepunkt am Faschingdienstag"),
            ("UNESCO-Status", "Immateriales Kulturerbe Österreichs"),
            ("Kostüme", "Stroh, Schaffelle, bunte Lappen, Glocken und Hörnern"),
        ],
        "stats": [
            ("400+", "Jahre dokumentierte Tradition"),
            ("5–8", "Tresterrer pro Gruppe"),
            ("2.000+", "Zuschauer in den Bergdörfern"),
        ],
        "hero_image": "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1800",
        "fullbleed_image": "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=1800",
        "history_title": "Wurzeln im Alpinen Brauchtum",
        "history_text": "Der Pinzgauer Tresterertanz entstand aus den Wintervertreibungsritualen der voralpinen Bevölkerung. Mit der Christianisierung wurden diese heidnischen Praktiken in den Fasching integriert, doch ihre mystische Essenz blieb erhalten. Die Masken sind kunstvoll aus Linden- oder Zirbenholz geschnitzt und zeigen dämonische, tierische oder übernatürliche Züge.\n\nDie Tradition war lange Zeit ausschließlich männlich und blieb in den abgelegenen Pinzgauer Bergdörfern lebendig. Während des 20. Jahrhunderts geriet der Brauch mehrfach in Vergessenheit, wurde aber durch engagierte Kulturträger bewahrt und wiederbelebt. Heute ist der Tresterertanz ein Symbol für die Bewahrung alpiner Traditionen und wurde 2010 in die UNESCO-Liste des immateriellen Kulturerbes Österreichs aufgenommen.",
        "history_timeline": [
            ("Prähistorie", "Wintervertreibungsrituale in den Alpen"),
            ("13.–15. Jahrhundert", "Erste schriftliche Erwähnungen in Salzburger Chroniken"),
            ("18.–19. Jahrhundert", "Blütezeit des Brauches in den Pinzgauer Bergdörfern"),
            ("2010", "Anerkennung als immaterielles Kulturerbe der UNESCO"),
            ("Heute", "Wiederbelebung durch Kulturvereine und Faschingsgesellschaften"),
        ],
        "fullbleed_caption": "Tresterrer in handgefertigten Masken und Strohumhängen bei der Wintervertreibung",
        "traditions_title": "Die Kunst der Maskenbefestigung",
        "traditions_text": "Die Herstellung einer authentischen Trestermaske ist ein zeitaufwändiger Prozess, der spezielles Wissen und handwerkliches Geschick erfordert. Erfahrene Schnitzer verwenden Linden- oder Zirbenholz und schaffen Gesichtsformen, die übernatürlich wirken – mit ausgeprägten Hörnern, verzerrten Mündern und wilden Augen. Jede Maske ist ein Unikat und erzählt eine Geschichte der alpinen Folklore.\n\nDas Kostüm selbst besteht aus mehreren Schichten: Ein bunter Sackleinen-Rock (das berühmte ‚Stroh'), darüber Schaffelle und Lappen in Braun und Grau, sowie Glocken, die beim Tanzen wild klingeln. Die Tänzer tragen oft große Hörner oder groteske Aufsätze, um ihre übernatürliche Natur zu unterstreichen. Der ganze Aufwand symbolisiert die Transformation vom Menschen zum wilden Waldgeist.",
        "interlude_quote": "‚Die Tresterrer tanzen den Winter fort und öffnen die Tore für den Frühling – ein Ritual so alt wie die Berge selbst.'",
        "program_title": "Programm & Höhepunkte",
        "program": [
            ("06:00 Uhr", "Erwachen der Tresterrer", "Geheime Zusammenkünfte in Stuben"),
            ("10:00 Uhr", "Erster Umzug durchs Dorf", "Tresterrer tanzen und springen durch Wald"),
            ("14:00 Uhr", "Wilde Tänze am Marktplatz", "Laut, rhythmisch, voller Energie"),
            ("18:00 Uhr", "Faschingsbälle und Tavernenbesuche", "Tresterrer revanchieren sich und tanzen"),
            ("22:00 Uhr", "Nächtliche Finale und Verabschiedung", "Letzte Rituale des Winters"),
        ],
        "gallery": [
            ("Detail einer handgeschnitzten Holzmaske", "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800"),
            ("Gruppe von Tresterrern im Schnee", "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800"),
            ("Farbenspiel der Kostüme und Glocken", "https://images.unsplash.com/photo-1475924156734-496f6cac6ec1?w=800"),
        ],
        "practical_info": [
            ("Beste Beobachtungsorte", "Wald im Pinzgau, Rauris, Dienten – frühzeitig anfahren", "🚗"),
            ("Kleidung", "Warm einpacken: -5°C bis +5°C, gute Schneeschuhe", "🧥"),
            ("Fotografie", "Erlaubt, aber respektvolle Distanz wahren", "📸"),
            ("Traditionelle Speisen", "Faschingskrapfen, Bauernkrapfen, Punsch & Glühwein", "🍴"),
            ("Kulturelle Tiefe", "Örtliche Museen zeigen alte Masken und Kostüme", "🏛️"),
            ("Anreise", "Von Salzburg ca. 90 Minuten mit Auto durchs Pinzgau", "🛣️"),
        ],
        "cta_text": "Erleben Sie die Magie der alpinen Wintervertreibung bei den Pinzgauer Tresterrern!",
        "seo_title": "Pinzgauer Tresterertanz – Mysterienvolle Faschingstradition — LassTreffen.at",
        "seo_description": "Der Pinzgauer Tresterertanz: Handgefertigte Holzmasken, wilde Tänze und vorchristliche Wintervertreibungsrituale in den Salzburger Alpen. UNESCO-Kulturerbe.",
        "keywords": ["Tresterertanz", "Salzburger Fasching", "Alpine Tradition", "Wintervertreibung", "UNESCO-Kulturerbe", "Pinzgauer Brauchtum"],
    },
    {
        "num": 32,
        "name": "Ebenseer Fetzenzug",
        "slug": "32-ebenseer-fetzenzug",
        "region": "Salzkammergut",
        "bundesland": "Oberösterreich",
        "date": "Faschingdienstag (variabel)",
        "location": "Ebensee, Oberösterreich",
        "reading_time": "10 Min.",
        "category": "Brauchtum & Tradition",
        "subtitle": "Das Fest der zerlumpten Geister und Wilde-Jagd-Prozessionen",
        "intro": "Der Ebenseer Fetzenzug ist eines der wildesten Faschingsfeste Österreichs. Tausende Menschen in bunten Lumpen, zerrissenen Kostümen und grotesken Masken tanzen und hüpfen in ausgelassener Fröhlichkeit durch die Straßen des Salzkammerguts. Der Name ‚Fetzen' deutet auf die Tradition der Lappenkostüme hin – Gewänder aus bunten Tüchern und Stofffetzen. Dieser farbenfrohe und unbändige Brauch verbindet heidnische Frühjahrsrituale mit christlichem Fasching zu einer wahrhaft explosiven Mischung aus Chaos und Kreativität.",
        "key_facts": [
            ("Teilnehmerzahl", "10.000–15.000 kostümierte Fetzenträger"),
            ("Hauptmerkmal", "Bunt zusammengesetzte Fetzen-Kostüme und Larven"),
            ("Charakter", "Unbändig, chaotisch, ausgelassen und kreativ"),
            ("Tradition seit", "Etwa 500 Jahre dokumentiert"),
            ("Spitzname", "Das ‚wilde' Salzburger Fest"),
            ("Parade-Route", "Durch die gesamte Altstadt von Ebensee"),
        ],
        "stats": [
            ("500+", "Jahre Tradition"),
            ("10.000+", "Maskierte Fetzenträger"),
            ("50.000+", "Zuschauer aus ganz Österreich"),
        ],
        "hero_image": "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=1800",
        "fullbleed_image": "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1800",
        "history_title": "Vom Heidnischen Frühjahrskult zur Faschingsexplosion",
        "history_text": "Der Ebenseer Fetzenzug wurzelt in vorchristlichen Frühjahrsritualen, bei denen die Winter-Geister vertrieben wurden. Mit Fetzen, Lumpen und wilde Farben symbolisierten die Menschen den chaotischen Übergang von Kälte zu Wärme. Als das Christentum kam, wurde dieser wilde Brauch einfach in den Fasching integriert – die Kirche konnte die Kraft dieser Tradition nicht unterdrücken, also assimilierte sie sie.\n\nDie schriftlichen Aufzeichnungen zum Fetzenzug reichen bis ins 16. Jahrhundert zurück, doch die Volksmemorie deutet auf viel ältere Ursprünge hin. Im 18. und 19. Jahrhundert wurde der Brauch immer elaborierter und farbenfreudiger. Nach dem Zweiten Weltkrieg erlebte der Fetzenzug eine Renaissance als Symbol österreichischer Volkstraditionen. Heute ist er einer der authentischsten und wildesten Faschingsbräuche Österreichs.",
        "history_timeline": [
            ("Prähistorie", "Heidnische Frühjahrsvertreibungsfeste"),
            ("15.–16. Jahrhundert", "Erste schriftliche Erwähnungen in Salzburger Chroniken"),
            ("18.–19. Jahrhundert", "Elaboration der Fetzen-Kostüme und Karnevalsfiguren"),
            ("1945–1980", "Wiederbelebung nach dem Krieg als Kulturerbe"),
            ("Heute", "Weltbekanntes Faschingsfest mit internationalem Ruf"),
        ],
        "fullbleed_caption": "Tausende Fetzenträger in bunten Lumpen und grotesken Larven füllen die Straßen Ebensees",
        "traditions_title": "Die Kunst des Fetzenlappens",
        "traditions_text": "Ein echter Fetzenzug-Kostüm zu schneidern ist ein künstlerisches Unterfangen. Traditionelle Fetzenträger verbinden bunte Stoffe, alte Laken, Zeitungspapier und sogar Blätter zu wildgewordenen Gewändern. Es gibt keine zwei identischen Kostüme – jeder Träger ist eine einzigartige Kreation. Die Larven (Masken) sind oft grotesk verzerrt, mit wildem Haar aus Stroh, übergroßen Nasen oder verrückten Augenbrauen.\n\nDie Kostüme müssen nicht teuer sein, sondern kreativ. Alte Kleider werden zerschnitten, Stoffe werden geflickt, bunte Bänder und Applikationen werden hinzugefügt. Der Spirit ist Anti-Establishment und Anti-Konformismus – je wilder, desto besser. Einige Fetzenträger tragen traditionelle alpine Volkstrachten in verrückten Kombinationen, andere improvisieren vollständig neue Designs. Die Tänzer selbst sind oft genauso kreativ wie ihre Kostüme.",
        "interlude_quote": "‚Im Fetzenzug ist jeder König und Narr zugleich – eine Nacht lang ist die soziale Ordnung umgekehrt.'",
        "program_title": "Programm & Höhepunkte",
        "program": [
            ("09:00 Uhr", "Ankunft und Kostümierung", "Tausende treffen sich in Stuben und privaten Sammelstellen"),
            ("11:00 Uhr", "Großer Faschingsumzug startet", "Konfetti, Serpentinen, Musik und wildes Tanzen"),
            ("14:00 Uhr", "Höhepunkt auf dem Marktplatz", "Tänze, Witze, Überraschungsperformances"),
            ("18:00 Uhr", "Faschingsbälle in Gasthöfen", "Traditionelle Faschingsmusik und Reden"),
            ("22:00 Uhr", "Nächtliche Straßenpartys", "Letzte Ausschweifungen vor Aschermittwoch"),
        ],
        "gallery": [
            ("Bunte Fetzen und Lumpen in Bewegung", "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800"),
            ("Kreative Larven und grotesque Masken", "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800"),
            ("Marktplatz voll mit farbenfreudigen Fetzenträgern", "https://images.unsplash.com/photo-1433086966358-54859d0ed716?w=800"),
        ],
        "practical_info": [
            ("Kostümtipp", "Alle Stoffe, Lumpen und Fetzen sind willkommen – kreativ sein!", "🎨"),
            ("Anfahrt", "Mit Bahn vom Hauptbahnhof Salzburg ca. 60 Minuten", "🚂"),
            ("Sicherheit", "Festes Schuhwerk empfohlen, enge Taschen für Wertsachen", "👟"),
            ("Verpflegung", "Faschingskrapfen, Punsch und Bier überall in der Stadt", "🍺"),
            ("Fotografie", "Erlaubt – viele Fetzenträger posieren gerne", "📸"),
            ("Besonderheit", "Keine kommerziellen Kostüme nötig – DIY ist authentisch", "✨"),
        ],
        "cta_text": "Schnappen Sie sich Ihre wildesten Lumpen und feiern Sie den Ebenseer Fetzenzug!",
        "seo_title": "Ebenseer Fetzenzug – Österreichs wildestes Faschingsfest — LassTreffen.at",
        "seo_description": "Ebenseer Fetzenzug: Tausende maskierte Fetzenträger, bunte Lumpen, grotesque Larven und chaotische Faschingsfreude im Salzkammergut.",
        "keywords": ["Fetzenzug", "Ebensee", "Fasching", "Faschingsfest", "Oberösterreich", "Volkstradition"],
    },
    {
        "num": 33,
        "name": "Sternsingen",
        "slug": "33-sternsingen",
        "region": "Bundesweit",
        "bundesland": "Österreich",
        "date": "6. Januar (Dreikönigstag)",
        "location": "Überall in Österreich",
        "reading_time": "10 Min.",
        "category": "Brauchtum & Tradition",
        "subtitle": "Die Heiligen Drei Könige gehen von Haus zu Haus",
        "intro": "Am 6. Januar, dem Dreikönigstag, ziehen Kinder verkleidet als die Heiligen Drei Könige – Caspar, Melchior und Balthasar – von Haus zu Haus, singen Weihnachtslieder und sammeln Spenden für caritative Zwecke. Mit goldenen Kronen, bunten Umhängen und leuchtenden Sternen begleiten sie die Botschaft der Heiligen aus dem Orient in jedes Heim. Diese liebgewordene Tradition verbindet religiöse Tiefe mit kindlicher Unschuld und hat Österreich seit Jahrhunderten geprägt. Das Sternsingen ist nicht nur Weihnachtsfestival, sondern gelebte Solidarität und Gemeinschaftssinn.",
        "key_facts": [
            ("Ursprung", "Gedenken an die Wallfahrt der Heiligen Drei Könige"),
            ("Teilnehmer", "Millionen von Kindern, Pfarreien und Vereinen österreichweit"),
            ("Sammelmittel", "Finanzierung sozialer Projekte weltweit"),
            ("Symbole", "Goldene Kronen, farbige Umhänge, glücksbringender Stern"),
            ("Melodien", "Traditionelle Weihnachtslieder, oft lokal adaptiert"),
            ("Bedeutung", "UNESCO-Kulturerbe – immaterielles Kulturerbe der Menschheit"),
        ],
        "stats": [
            ("2.000+", "Jahre christliche Tradition"),
            ("1 Million+", "Kinder beteiligen sich jährlich in Österreich"),
            ("€50 Million+", "Gesammelt für Solidaritätsprojekte weltweit"),
        ],
        "hero_image": "https://images.unsplash.com/photo-1470770903676-69b98201ea1c?w=1800",
        "fullbleed_image": "https://images.unsplash.com/photo-1529333166437-7750a6dd5a70?w=1800",
        "history_title": "Von der Biblischen Weisheit zur Österreichischen Tradition",
        "history_text": "Das Sternsingen wurzelt in der christlichen Tradition der Heiligen Drei Könige, die dem Stern von Bethlehem folgten, um das Jesuskind zu besuchen. Diese biblische Geschichte wurde über Jahrhunderte in ganz Europa begangen, doch Österreich machte das Sternsingen zu etwas Besonderem: Eine partizipative Tradition, bei der Kinder die Könige verkörpern und selbst zu Überbringern der Weihnachtsbotschaft werden.\n\nIm Mittelalter war das Sternsingen ein Privileg der reichen Familien und der Kirche. Ab dem 16. Jahrhundert wurde es demokratisiert und Kinder aus allen Schichten durften teilnehmen. Im 19. Jahrhundert entstand die Verbindung zu karitativen Sammlungen – das Sternsingen wurde zum Werkzeug der Nächstenliebe. Nach dem Zweiten Weltkrieg wurde die Tradition wiederbelebt und ausgebaut. Heute ist das österreichische Sternsingen ein Modell für weltweit ähnliche Initiativen und seit 2009 offizielles UNESCO-Kulturerbe.",
        "history_timeline": [
            ("1.–4. Jahrhundert", "Biblische Überlieferung der Heiligen Drei Könige"),
            ("Mittelalter", "Kirchliche Sternsinger-Prozessionen in Europa"),
            ("16.–17. Jahrhundert", "Demokratisierung des Sternsingens in Österreich"),
            ("19. Jahrhundert", "Verbindung zu karitativen Sammlungen"),
            ("2009", "UNESCO-Anerkennung als immaterielles Kulturerbe"),
        ],
        "fullbleed_caption": "Kinder in goldenen Kronen und bunten Umhängen singen von Haus zu Haus",
        "traditions_title": "Die Kostüme und Symbole der Könige",
        "traditions_text": "Der Aufzug eines Sternsängers ist ein kunstvolles Ensemble aus religiösem Symbolismus und Kinderjoy. Die drei Könige tragen goldene Kronen, die oft aus Pappe, Stoff und Glitter hergestellt sind. Jeder König hat einen farbigen Umhang – traditionell Rot für Caspar, Grün für Melchior und Violett/Blau für Balthasar – dieser farbenfrohen Symbolik entsprechend seinen jeweiligen Gaben (Gold, Weihrauch, Myrrhe).\n\nDer zentrale Star – der Stern von Bethlehem – wird von einem Kind oder einer Gruppe getragen. Er ist oft groß, leuchtend und wird mit Kerzen oder elektrischen Lichtern illuminiert. Die Sternsingkinder tragen Liedhefte und führen oft ein Sammelbuch mit, in das jeder Hausbesitzer ein kleines Kreuz macht (‚20 + C + M + B + 22' für das Jahr). Diese Markierung segnet das Haus für das kommende Jahr. Die Kombination aus religiöser Tiefe und alltäglichem Gemeinschaftssinn macht das Sternsingen zu einer der schönsten österreichischen Traditionen.",
        "interlude_quote": "‚Folgt dem Stern – die Botschaft der Hoffnung geht von Haus zu Haus.'",
        "program_title": "Programm & Höhepunkte",
        "program": [
            ("Nach Weihnacht", "Vorbereitung und Probe der Sternsänger", "Pfarreien und Schulen proben Lieder"),
            ("5. Januar", "Eröffnungsgottesdienste und Segnungen", "Pfarrer segnen die Sternsänger"),
            ("6. Januar früh", "Start des Hausbesuchs-Marathons", "Pfarreien organisieren Routen"),
            ("6. Januar tagsüber", "Flächendeckendes Singen in allen Ortschaften", "Von früh bis Einbruch der Dunkelheit"),
            ("6. Januar Abend", "Dank-Veranstaltungen und Feiern", "Zusammenkunft und Dankesfeste"),
        ],
        "gallery": [
            ("Kinder in königlichen Kostümen mit leuchtenden Sternen", "https://images.unsplash.com/photo-1473448912268-2022ce9509d8?w=800"),
            ("Sternsänger beim Singen vor einem Haus", "https://images.unsplash.com/photo-1508193638397-1c4234db14d8?w=800"),
            ("Detailaufnahme einer goldenen Krone und eines glänzenden Sternes", "https://images.unsplash.com/photo-1482192505345-5655af888cc4?w=800"),
        ],
        "practical_info": [
            ("Anmeldung", "Über die Pfarrgemeinde oder örtliche Caritas-Organisationen", "📋"),
            ("Alter", "Typisch 6–14 Jahre, aber offene Teilnahme", "👧"),
            ("Kosten", "Kostüme werden meist von der Pfarrei bereitgestellt", "💰"),
            ("Sammelmittel", "Spenden gehen an Solidarität & Entwicklungsprojekte", "🤝"),
            ("Musikalische Vorbereitung", "4–6 Wochen Probenzeit vorher", "🎵"),
            ("Sicherheit", "Erwachsene begleiten die Gruppen, Versicherung vorhanden", "✅"),
        ],
        "cta_text": "Werden Sie zum Sternsänger oder unterstützen Sie diese wunderbare Tradition!",
        "seo_title": "Sternsingen am 6. Januar – Österreichs Weihnachtszauber — LassTreffen.at",
        "seo_description": "Sternsingen: Millionen Kinder singen als Heilige Drei Könige von Haus zu Haus. UNESCO-Kulturerbe und österreichische Weihnachtstradition.",
        "keywords": ["Sternsingen", "Dreikönigstag", "6. Januar", "Heilige Drei Könige", "Österreichische Tradition", "Weihnachten"],
    },
    {
        "num": 34,
        "name": "Rauhnächte & Räuchern",
        "slug": "34-rauhnachte-rauchern",
        "region": "Alpenraum",
        "bundesland": "Österreich",
        "date": "25. Dezember – 6. Januar",
        "location": "Alpine Regionen, besonders Tirol, Salzburg, Steiermark",
        "reading_time": "10 Min.",
        "category": "Brauchtum & Tradition",
        "subtitle": "Die heiligen Nächte der Reinigung und Segnung",
        "intro": "Die Rauhnächte – jene zwölf mystischen Nächte zwischen Weihnacht und Dreikönig – sind in den Alpen eine Zeit der Schwelle, der Kontemplation und der rituelledaten Reinigung. Mit Weihrauch, Kräutern und Räuchermischungen werden Häuser, Ställe und Felder gesegnet und gereinigt. Diese archaische Tradition verbindet heidnische Wintermagie mit christlicher Spiritualität und prägt das innerste Selbstverständnis alpiner Gemeinschaften. Die Rauhnächte sind kein lautes Fest, sondern eine stille, intime Zeit des Übergangs – Raum für Reflexion, Bußfertigkeit und kosmische Erneuerung.",
        "key_facts": [
            ("Zeitraum", "12 heilige Nächte: 25.12.–6.1."),
            ("Zentral", "Räuchermischungen aus Weihrauch, Kräutern und Harzen"),
            ("Rituale", "Haus-, Stall- und Feldräucherung, Segnung mit Gebet"),
            ("Spirituelle Funktion", "Böse Geister vertreiben, Segen für das neue Jahr erbeten"),
            ("Ursprünge", "Vorchristliche Wintermagie und germanische Bräuche"),
            ("Regionale Präsenz", "Tirol, Salzburg, Steiermark, Vorarlberg"),
        ],
        "stats": [
            ("2.000+", "Jahre dokumentierter Geschichte"),
            ("70–80%", "Alpine Familien praktizieren Rauhnächte-Räuchern"),
            ("12", "Heilige Nächte mit je eigener Bedeutung"),
        ],
        "hero_image": "https://images.unsplash.com/photo-1512389142860-9c449e58a814?w=1800",
        "fullbleed_image": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1800",
        "history_title": "Zwischen Heidentum und Christentum: Die Magie der Rauhnächte",
        "history_text": "Die Rauhnächte haben ihre tiefsten Wurzeln in den Wintermagie-Ritualen vorchristlicher germanischer und keltischer Völker. In der Vorstellung dieser Kulturen war die Winterzeit – besonders die längste Nacht – eine Zeit, in der die Grenzen zwischen den Welten durchlässig wurden. Götter, Geister und übernatürliche Kräfte wanderten frei umher. Durch Räuchern mit heiligen Kräutern versuchte man, diese Geister zu besänftigen und den Segen der kommenden Jahreszeit zu sichern.\n\nMit der Christianisierung wurde diese heidnische Magie nicht verdrängt, sondern reinterpretiert. Die zwölf Rauhnächte wurden mit den zwölf Tagen zwischen Weihnacht und Dreikönig verbunden – beide Systeme passten zeitlich perfekt zusammen. Pfarrer integrierten Räuchern in kirchliche Praktiken: Geweihter Weihrauch wurde mit traditionellen alpinen Kräutern vermischt. Diese Synthese ist bis heute lebendig und wird in vielen Bergdörfern mit großer Hingabe gepflegt.",
        "history_timeline": [
            ("Prähistorie", "Germanische und keltische Wintermagie und Rituale"),
            ("Mittelalter", "Synkretismus: Heidnische Räuchung wird in Kirchen praktiziert"),
            ("16.–18. Jahrhundert", "Blütezeit des Rauhnächte-Brauches in den Alpen"),
            ("19.–20. Jahrhundert", "Teilweise Verdrängung durch Säkularisierung, dann Wiederbelebung"),
            ("Heute", "Renaissance der Rauhnächte als spirituelle Erneuerungspraxis"),
        ],
        "fullbleed_caption": "Räuchernde Hausfassaden in der Alpendämmerung der Rauhnächte",
        "traditions_title": "Das Ritual des Räucherns",
        "traditions_text": "Das Rauhnächte-Räuchern ist ein feierliches, fast meditatives Ritual. In der Dämmerung oder nach Sonnenuntergang nehmen Familienmitglieder – oft die ältesten Frauen oder der Hausherr – eine Räucherschale oder ein spezielles Räucherfass (‚Räucherkübel') zur Hand. Darin brennt eine Mischung aus Weihrauch, Wacholder, Kräutern wie Oreganum, Thymian, Rosmarin sowie Harzen. Der duftende Rauch wird zuerst durchs Wohnhaus, dann durch Stallungen und schließlich um die Felder geweht.\n\nBeim Räuchern werden Gebete und Segensformeln gesprochen – manche in Hochdeutsch, manche in Dialekt, manche sind sehr alt und stammen aus kirchlichen Segnungen. Die Intention ist immer dieselbe: Böse Geister und Krankheiten werden vertrieben, der Segen für Haus, Vieh und Ernte wird erbeten, und Schutz für die kommenden Monate wird gewährt. Manche Familien erstellen Rauhnächte-Kalender, in denen jede der zwölf Nächte eine andere Bedeutung hat.",
        "interlude_quote": "‚Der Rauch steigt auf wie ein Gebet – die Grenzen zwischen den Welten öffnen sich, und wir erbitten Segen für das kommende Jahr.'",
        "program_title": "Programm & Höhepunkte",
        "program": [
            ("25. Dezember Abend", "Beginn der Rauhnächte", "Erste Räucherung nach Weihnacht"),
            ("26.–31. Dezember", "Nächtliche Hausräucherungen", "Täglich etwa 1–2 Stunden nach Sonnenuntergang"),
            ("31. Dezember", "Große Jahreswende-Räucherung", "Intensives Räuchern, Jahreszahlen-Räuchung"),
            ("1.–5. Januar", "Räucherungen zur Neujahrs-Erneuerung", "Feldräucherungen und Stallsegnungen"),
            ("6. Januar", "Abschließende Rauhnächte-Segnung", "Kräuterbuschen werden geweihrt und verbrannt"),
        ],
        "gallery": [
            ("Räucherschale mit glühendem Rauch in Alpenhäusern", "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800"),
            ("Nächtliches Räuchern vor einer traditionellen Almhütte", "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800"),
            ("Getrocknete Kräuter und Räuchermischungen auf Tisch arrangiert", "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800"),
        ],
        "practical_info": [
            ("Räuchermischung kaufen", "Apotheken, Kräuterläden und Museen in alpinen Regionen", "🏪"),
            ("Sicherheit", "Räucherschale sichere Unterlagen verwenden, Belüftung beachten", "⚠️"),
            ("Beste Orte", "Tirol, Salzburg, Steiermark haben lebendige Traditionen", "🏔️"),
            ("Geistliche Begleitung", "Pfarreien bieten Rauhnächte-Rituale an", "⛪"),
            ("Bedeutung der 12 Nächte", "Jede Nacht korrespondiert mit einem Monat des Jahres", "📅"),
            ("Familie-Räuchern", "Traditionell eine Familienangelegenheit, tiefe Verbundenheit", "👨‍👩‍👧"),
        ],
        "cta_text": "Entdecken Sie die spirituelle Tiefe der Rauhnächte und segnen Sie Ihr Heim!",
        "seo_title": "Rauhnächte & Räuchern – Alpine Wintermagie und Segnung — LassTreffen.at",
        "seo_description": "Rauhnächte (25.12.–6.1.): Spirituelle Räucherriten mit Weihrauch und Kräutern in alpinen Alpen. Heidnische Magie trifft christliche Tradition.",
        "keywords": ["Rauhnächte", "Räuchern", "Alpine Tradition", "Wintermagie", "Segnung", "Tirol", "Salzburg"],
    },
    {
        "num": 35,
        "name": "Stille Nacht Oberndorf",
        "slug": "35-stille-nacht-oberndorf",
        "region": "Pinzgau",
        "bundesland": "Salzburg",
        "date": "24. Dezember (Heiligabend)",
        "location": "Oberndorf bei Salzburg, Salzburg",
        "reading_time": "10 Min.",
        "category": "Brauchtum & Tradition",
        "subtitle": "Wo das berühmteste Weihnachtslied der Welt geboren wurde",
        "intro": "In der kleinen Kirche St. Nikola in Oberndorf bei Salzburg wurde 1818 das berühmteste Weihnachtslied aller Zeiten komponiert: ‚Stille Nacht, heilige Nacht'. Der Vikar Joseph Mohr schrieb die Worte, der Lehrer Franz Xaver Gruber die Melodie. Seitdem ist ‚Stille Nacht' nicht nur ein Lied, sondern ein weltweites Symbol der Weihnacht und des Friedens. Am Heiligabend versammeln sich Tausende in Oberndorf zu einer stillen, nachdenklichen Andacht – eine Feier der Schlichtheit, des Glaubens und der universellen Botschaft des Liedes.",
        "key_facts": [
            ("Erstaufführung", "24. Dezember 1818 in der Pfarrkirche St. Nikola"),
            ("Komponist", "Joseph Mohr (Text), Franz Xaver Gruber (Musik)"),
            ("Weltweit", "In über 300 Sprachen und Dialekte übersetzt"),
            ("Schöpfungsort", "Das kleine Pfarrhaus und die alte Kirche"),
            ("Nationale Hymne", "Inoffizielle Hymne Österreichs zur Weihnachtszeit"),
            ("Jährliche Gedenkfeier", "Heiligabend-Messe mit Lichter und Kerzen"),
        ],
        "stats": [
            ("200+", "Jahre seit der Komposition"),
            ("300+", "Sprachversionen und Dialektvarianten"),
            ("2.000+", "Kirchenbesucher am Heiligabend"),
        ],
        "hero_image": "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1800",
        "fullbleed_image": "https://images.unsplash.com/photo-1470770903676-69b98201ea1c?w=1800",
        "history_title": "Von der Improvisation zum Weltlied",
        "history_text": "Die Geschichte von ‚Stille Nacht' ist eine Geschichte der Gnade und des musikalischen Wunders. Im Dezember 1818 stand Pfarrer Joseph Mohr vor einem unerwarteten Problem: Die Orgel in der St. Nikola-Kirche war beschädigt und konnte nicht gespielt werden. Für die Heiligabend-Messe brauchte er etwas Neues. In dieser Not schrieb er das Gedicht ‚Stille Nacht' – einfache, liebevolle Verse über die Geburt Jesu in bescheidenen Verhältnissen.\n\nMohr gab das Gedicht seinem Freund, dem Lehrer Franz Xaver Gruber, mit der Bitte, eine Melodie zu komponieren. Gruber schrieb in nur wenigen Stunden eine sanfte, unvergessliche Melodie. Am Heiligabend wurde das Lied zum ersten Mal gesungen – mit Gitarre statt Orgel. Das Publikum war überrascht und bewegt. Das Lied verbreitete sich organisch über Jahrhunderte: durch Wandersänger, Chöre und später über massenhafte Medien. Heute ist ‚Stille Nacht' eines der bekanntesten Werke überhaupt.",
        "history_timeline": [
            ("Dezember 1818", "Joseph Mohr schreibt das Gedicht"),
            ("24. Dezember 1818", "Franz Xaver Gruber komponiert die Melodie"),
            ("24. Dezember 1818 Abend", "Uraufführung in St. Nikola, Oberndorf"),
            ("19. Jahrhundert", "Rasante internationale Verbreitung"),
            ("20.–21. Jahrhundert", "Weltweite Anerkennung als Symbol des Friedens"),
        ],
        "fullbleed_caption": "Die Pfarrkirche St. Nikola in Oberndorf, Geburtsort des weltberühmten Liedes",
        "traditions_title": "Das Lied und seine Bedeutung",
        "traditions_text": "‚Stille Nacht' ist nicht nur musikalisch schön, sondern theologisch tiefgründig. Das Lied zelebriert die Geburt Jesu in Armut, Stille und Liebe – nicht in Prunk oder Macht. Diese Botschaft sprach Menschen aller Kulturen an: Die Heiligkeit liegt nicht im Äußeren, sondern im Inneren; der größte Segen kommt in Einfachheit. Die Melodie ist pentatonisch, einfach zu singen und zu merken – weshalb sie sich so leicht über Kulturgrenzen hinweg verbreitete.\n\nDas Lied wurde ins Polnische, Japanische, Mandarin, Arabisch und Hunderte anderer Sprachen übersetzt. Während des Ersten Weltkriegs sangen Soldaten beider Seiten das Lied zusammen als Symbol des Friedens. Später wurde es zur Hymne der Weihnacht in Konzerten, Kirchen und Haushalten weltweit. In Oberndorf ist jede Aufführung von ‚Stille Nacht' eine Ehrfurcht vor dieser universellen Botschaft.",
        "interlude_quote": "‚In aller Stille wurde die größte Liebesbotschaft der Menschheit geboren – nicht im Krach, sondern in der sanften Nacht.'",
        "program_title": "Programm & Höhepunkte",
        "program": [
            ("15:00 Uhr", "Öffnung der Stille-Nacht-Gedenkkapelle", "Zeitgenössische Kapelle mit Ikonografie"),
            ("16:00 Uhr", "Kinderchöre singen Weihnachtslieder", "Vorbereitung für Kinder"),
            ("22:00 Uhr", "Heiligabend-Messe beginnt", "Traditionale Weihnachtsmesse mit Kerzenschein"),
            ("22:15 Uhr", "Aufführung von ‚Stille Nacht'", "Orgel-, Chor- und Orchester-Ensemble"),
            ("22:30 Uhr", "Gemeinsames Singen und stille Andacht", "Die gesamte Gemeinde singt mit"),
        ],
        "gallery": [
            ("Innerer Altar der St. Nikola-Kirche mit Kerzenschein", "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800"),
            ("Kerzen und Friedenssymbole in der Kapelle", "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800"),
            ("Orgel und Chor bereit zur Heiligabend-Aufführung", "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800"),
        ],
        "practical_info": [
            ("Anreise", "Von Salzburg 20 Minuten mit Auto oder Bahn", "🚗"),
            ("Platzbuchung", "Früh anfahren oder vorher reservieren – sehr beliebt", "🎫"),
            ("Sprachen", "Messe auf Deutsch, Lied in vielen Sprachen", "🌍"),
            ("Warme Kleidung", "Kirche kann kühl sein, Decke empfohlen", "🧥"),
            ("Stille Andacht", "Bitte Respekt vor der Besinnung – kein Fotografieren", "📵"),
            ("Museum", "Geburtshaus von Joseph Mohr ist in der Nähe zugänglich", "🏛️"),
        ],
        "cta_text": "Erleben Sie das größte Weihnachtslied der Welt an seinem Geburtsort!",
        "seo_title": "Stille Nacht Oberndorf – Das berühmteste Weihnachtslied — LassTreffen.at",
        "seo_description": "Stille Nacht in Oberndorf: Heiligabend in der Pfarrkirche St. Nikola, wo das Weltlied 1818 geboren wurde. Stille, Andacht, Frieden.",
        "keywords": ["Stille Nacht", "Oberndorf", "Weihnachtslied", "Salzburg", "Heiligabend", "Joseph Mohr"],
    },
    {
        "num": 36,
        "name": "Bregenzerwälder Kilbi",
        "slug": "36-bregenzerwaelder-kilbi",
        "region": "Bregenzerwald",
        "bundesland": "Vorarlberg",
        "date": "Herbst (variabel, meist September–Oktober)",
        "location": "Verschiedene Dörfer im Bregenzerwald, Vorarlberg",
        "reading_time": "10 Min.",
        "category": "Brauchtum & Tradition",
        "subtitle": "Erntefest und Kirchweihfeier in der Bergwelt Vorarlbergs",
        "intro": "Die Bregenzerwälder Kilbi ist ein Erntefest mit tiefen kirchlichen Wurzeln, das in den malerischen Bergdörfern des Bregenzerwaldes seit Jahrhunderten gefeiert wird. ‚Kilbi' stammt vom Wort ‚Kirchweih' – die Feier der Weihe einer Kirche. Doch die moderne Kilbi verbindet Kirchliches mit Weltlichem: Erntesegens-Gottesdienste, traditionelle Trachten, regionale Speisen und volkstümliche Musik schaffen eine Festlichkeit, die Glaube und Gemeinschaft feiert. Mit ihrem Fokus auf alpines Handwerk, traditionelle Kostüme und kulinarische Köstlichkeiten ist die Kilbi ein Fenster in die zeitlose Bergkultur Vorarlbergs.",
        "key_facts": [
            ("Ursprung", "Kirchweih-Feste mit Erntedank-Verbindung"),
            ("Tradition", "Über 300 Jahre dokumentiert"),
            ("Zentral", "Kirchengottesdienst, Trachtenumzüge, regionale Küche"),
            ("Regionale Bedeutung", "Ein Identitätssymbol des Bregenzerwaldes"),
            ("Zeitpunkt", "Nach der Heuernte, meist September–Oktober"),
            ("Gastlichkeit", "Dörfer laden mit lokalen Speisen und Musik ein"),
        ],
        "stats": [
            ("300+", "Jahre Tradition"),
            ("10–15", "Bregenzerwälder Dörfer mit Kilbi-Festen"),
            ("5.000+", "Besucher in den Hauptdörfern"),
        ],
        "hero_image": "https://images.unsplash.com/photo-1433086966358-54859d0ed716?w=1800",
        "fullbleed_image": "https://images.unsplash.com/photo-1470770903676-69b98201ea1c?w=1800",
        "history_title": "Von der Kirchweih zum Volks- und Ernte-Fest",
        "history_text": "Die Kilbi-Tradition des Bregenzerwaldes entstand aus dem Festtag der Kirchweih – der jährlichen Feier der Weihe einer Kirche. Im Mittelalter und der Frühen Neuzeit waren Kirchweih-Feste wichtige Gemeinschaftsereignisse, an denen sich das ganze Dorf versammelte, um die lokale Pfarrkirche zu ehren. Mit der Zeit vermischten sich kirchliche und weltliche Elemente: Die Feier wurde mit der Erntezeit verbunden, mit Dankgebeten für die erfolgreiche Heuernte und die nächste Saison.\n\nDer Bregenzerwald, durch seine geografische Isolation und die starke Dorfkultur, bewahrte diese Tradition besonders lebendig. Jedes Dorf hat seinen eigenen Kilbi-Festtag, oft mit lokalen Besonderheiten. Im 19. Jahrhundert wurden die Kilbi-Feste immer elaborierter, mit Trachten, Musikkapellen und festlichen Mahlzeiten. Heute sind die Bregenzerwälder Kilbis Beispiele gut erhaltener alpiner Volkstradition.",
        "history_timeline": [
            ("Mittelalter", "Kirchweih-Feste entstehen in europäischen Gemeinden"),
            ("16.–18. Jahrhundert", "Vermischung mit Erntefesten und Erntedank"),
            ("19. Jahrhundert", "Elaboration mit Trachten und Musikkapellen"),
            ("20.–21. Jahrhundert", "Bewahrung und folkloristische Pflege"),
            ("Heute", "Kulturelles Flaggschiff des Bregenzerwaldes"),
        ],
        "fullbleed_caption": "Trachtengruppen und Kirchenprozessionen in den Bergdörfern des Bregenzerwaldes",
        "traditions_title": "Tracht, Kirche und Tafel",
        "traditions_text": "Eine Bregenzerwälder Kilbi ist ein Zusammenspiel von Kirche, Tracht und Kulinarik. Am Morgen startet mit einem Gottesdienst – der Erntesegens-Messe, in der die erfolgreiche Heuernte gedankt wird. Die Kirche ist mit Blumen, Getreide und Feldfrüchten geschmückt. Nach dem Gottesdienst folgt ein Trachtenumzug durchs Dorf: Frauen in bunten Vorarlberger Trachten mit Häubchen und Spitzenschürzen, Männer in lederner Bregenzerwald-Tracht, Kinder in Miniatur-Kostümen.\n\nDie Tafel ist ebenfalls zentral: Traditionelle Vorarlberger Speisen dominieren – Käsespätzle, Erdäpfelpuffer, Blunzn, Kasnockn, dazu Bier und Saft. Musikkapellen spielen volkstümliche Melodien und Jodler. Der Fokus liegt auf Regionalität und Handwerk: Oft werden lokale Produkte ausgestellt und verkauft – Käse, Milchprodukte, Holzkunst, Webtextilien. Diese Kombination macht die Kilbi zu einem Fest der Identität und der Landwirtschaft.",
        "interlude_quote": "‚Die Kilbi ist das Fest der Berge, der Heuarbeit und der Dorfgemeinschaft – wo die Ernte zu Dank wird.'",
        "program_title": "Programm & Höhepunkte",
        "program": [
            ("09:00 Uhr", "Feierlicher Gottesdienst mit Erntesegen", "Kirche voll, Blumenschmuck, Erntegaben"),
            ("11:00 Uhr", "Trachtenumzug durchs Dorf", "Mit Musikkapelle und festlichem Glockengeleut"),
            ("12:00 Uhr", "Festessen beginnt", "Traditionelle Vorarlberger Speisen"),
            ("14:00 Uhr", "Handwerksmärkte und regionale Produkte", "Käse, Holzkunst, Textilien"),
            ("18:00 Uhr", "Tanz und Musikabend", "Kapelle, Jodler, bis spät in Nacht"),
        ],
        "gallery": [
            ("Frauen in bunten Vorarlberger Trachten mit Häubchen", "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800"),
            ("Schmaler Bergweg mit Kirche und Bergblick", "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800"),
            ("Käsespätzle und traditionelle Vorarlberger Speisen", "https://images.unsplash.com/photo-1433086966358-54859d0ed716?w=800"),
        ],
        "practical_info": [
            ("Beste Zeit", "September–Oktober, nach der Heuernte", "🌾"),
            ("Anfahrt", "Mit Auto oder Bahn nach Bregenzerwald (90 Min ab Feldkirch)", "🚂"),
            ("Verschiedene Dörfer", "Jedes Dorf hat seinen eigenen Kilbi-Tag – vorher informieren", "📅"),
            ("Tracht-Besucher", "Willkommen in Tracht oder Alltagskleidung", "👕"),
            ("Verpflegung", "Traditionelle Gasthöfe und Festzelte", "🍽️"),
            ("Handwerk", "Lokale Kunsthandwerker stellen aus – Souvenirs möglich", "🎨"),
        ],
        "cta_text": "Besuchen Sie eine echte Bregenzerwälder Kilbi und erleben Sie alpine Erntefestkultur!",
        "seo_title": "Bregenzerwälder Kilbi – Erntefest in Vorarlbergs Bergdörfern — LassTreffen.at",
        "seo_description": "Bregenzerwälder Kilbi: Kirchweihfest mit Erntesegens-Messe, Trachtenumzügen und regionale Käsespätzle in malerischen Bergdörfern.",
        "keywords": ["Kilbi", "Bregenzerwald", "Vorarlberg", "Erntefest", "Kirchweih", "Alpine Tradition"],
    },
    {
        "num": 37,
        "name": "Jenbacher Fasnacht",
        "slug": "37-jenbacher-fasnacht",
        "region": "Zillertal",
        "bundesland": "Tirol",
        "date": "Faschingdienstag (variabel)",
        "location": "Jenbach, Tirol",
        "reading_time": "10 Min.",
        "category": "Brauchtum & Tradition",
        "subtitle": "Wilde Maskentänze und kuriose Karnevalscharaktere",
        "intro": "Die Jenbacher Fasnacht ist ein wilder, farbenproheter Faschingsbund, der im Zillertal Tirols zu Hause ist. Mit kuriosen Charakteren wie ‚Hexen', ‚Grafenern', ‚Wassermännern' und fantastischen selbstgebastelten Masken tanzen und springen die Fasnächtler durch die Bergstadt. Die Kostüme sind handgefertigt, oft voll improviser Kreativität, und repräsentieren Volksfiguren aus Magie, Natur und alpinem Aberglauben. Diese authentische und nicht-kommerzielle Fasnacht bewahrt das wilde, chaotische Geist der vorchristlichen Frühlingsfeste und transformiert Jenbach für einen Tag in einen Reich der Gesten und Sonderbarkeiten.",
        "key_facts": [
            ("Hauptfiguren", "Hexen, Grafener, Wassermänner, Waldwesen"),
            ("Charakteristik", "Wilde, improvisierte, selbstgefertigte Masken"),
            ("Tradition", "200+ Jahre dokumentiert"),
            ("Geist", "Anti-kommerziell, kreativ, heidnisch-magisch"),
            ("Zielort", "Jenbach im Zillertal – echte Tiroler Fasnacht"),
            ("Besonderheit", "Jede Maske ein Unikat, persönliche Geschichte"),
        ],
        "stats": [
            ("200+", "Jahre Tradition"),
            ("2.000–3.000", "Kostümierte Fasnächtler"),
            ("10.000+", "Zuschauer aus dem Zillertal und drüber hinaus"),
        ],
        "hero_image": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1800",
        "fullbleed_image": "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1800",
        "history_title": "Von Hexenverfolgung zu Faschingszauber",
        "history_text": "Die Jenbacher Fasnacht hat ihre Wurzeln in dunkleren Zeiten: In der Frühen Neuzeit war das Zillertal Schauplatz von Hexenverfolgungen, besonders heftig unter Fürstbischof Preuenhuber im 17. Jahrhundert. Hunderte von Menschen – überwiegend Frauen – wurden der Hexerei beschuldigt und hingerichtet. Diese Trauma prägte die lokale Kulturseele tiefgreifend.\n\nDie Fasnacht wurde paradoxerweise zu einem Ventil für diese Trauma: Junge Männer verkleideten sich als ‚Hexen', ‚Waldwesen' und andere Gestalten aus lokaler Magie und Aberglaube. Dies war eine Art kathartisches Rollenspiel, das gleichzeitig die Magie und den Aberglauben persiflierte. Statt Angst vor diesen Figuren zu haben, wurden sie lächerlich gemacht und getanzt. Diese psychologisch tiefgreifende Transformation hat sich bis heute bewahrt – die Jenbacher Fasnacht ist nicht nur ein Fest, sondern ein kulturelles Bewältigungsritual.",
        "history_timeline": [
            ("17. Jahrhundert", "Hexenverfolgungen im Zillertal unter Bischöfen"),
            ("17.–18. Jahrhundert", "Fasnacht als kathartisches Ventil entsteht"),
            ("19. Jahrhundert", "Elaboration der Masken und Charaktere"),
            ("20. Jahrhundert", "Blüte und Gefährdung durch Moderne"),
            ("Heute", "Renaissance der Jenbacher Fasnacht als Kulturerbe"),
        ],
        "fullbleed_caption": "Maskierte Fasnächtler in wilden Kostümen tanzen durch Jenbachs Straßen",
        "traditions_title": "Die Charaktere der Jenbacher Fasnacht",
        "traditions_text": "Die Jenbacher Fasnacht hat ihre eigenen ikonischen Karaktere, die sich über Jahrhunderte entwickelt haben. Die ‚Hexen' sind eine Hauptfigur – maskiert mit langen Nasen, Hüten und bunten Lumpen, dramatisch-komisch und mit sexuellen Untertönen. ‚Grafener' sind mysteriöse waldwesen mit Hornen und Fellen. ‚Wassermänner' repräsentieren die Flussgeister des Zillertals – nass, wild, unberechenbar.\n\nJede Maske wird von Hand hergestellt, often aus Holz, Pappe, Stoffen und natürlichen Materialien. Es gibt keine industriell gefertigten Masken – das wäre undenkbar. Der kreative Prozess ist Teil des Rituals: Familien, Freundeskreise und Vereinigungen treffen sich über Wochen vorher, um ihre Masken zu bauen und ihre Kostüme zu designen. Die Jenbacher Fasnacht ist daher nicht nur ein Fest, sondern ein gesamter künstlerischer Prozess.",
        "interlude_quote": "‚In Jenbach werden die Dämonen des Waldes und der Nacht getanzt, gelacht und vertrieben – ein Fest so alt wie die Berge.'",
        "program_title": "Programm & Höhepunkte",
        "program": [
            ("09:00 Uhr", "Sammlung der Maskenträger in Stuben", "Vorbereitung und Versammlung"),
            ("11:00 Uhr", "Großer Umzug startet", "Mit lauter Musik, Glocken und Lärm"),
            ("13:00 Uhr", "Erste Pausen für Getränke und Snacks", "Gasthöfe überall offen"),
            ("15:00 Uhr", "Marktplatz-Tänze und Spektakel", "Wilde, improvisierte Performances"),
            ("18:00 Uhr", "Abend-Partys und nächtliches Feiern", "Musik, Tanz bis Mitternacht"),
        ],
        "gallery": [
            ("Wilde, groteske Masken und Holzschnitzkunst", "https://images.unsplash.com/photo-1482192505345-5655af888cc4?w=800"),
            ("Fasnächtler in Waldwesen-Kostümen mit Hörner", "https://images.unsplash.com/photo-1512389142860-9c449e58a814?w=800"),
            ("Gasthöfe voll mit feiernden Fasnächtlern", "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800"),
        ],
        "practical_info": [
            ("Kostüm", "Selbstgefertigt empfohlen – DIY ist authentisch", "🎨"),
            ("Anfahrt", "Mit Bahn direkt nach Jenbach im Zillertal", "🚂"),
            ("Sicherheit", "Vorsicht im Gedränge, gute Schuhe", "👟"),
            ("Verpflegung", "Faschingskrapfen, Punsch und Bier in Gasthöfen", "🍺"),
            ("Fotografie", "Willkommen – viele Fasnächtler posieren gerne", "📸"),
            ("Übernachtung", "Gasthöfe und Pensionen im Zillertal buchen", "🏨"),
        ],
        "cta_text": "Erleben Sie die wilde Magie der Jenbacher Fasnacht im Zillertal!",
        "seo_title": "Jenbacher Fasnacht – Wilde Maskentänze im Zillertal — LassTreffen.at",
        "seo_description": "Jenbacher Fasnacht: Handgefertigte Masken, Hexen, Waldwesen und chaotische Faschingsfreude in den Tiroler Bergen.",
        "keywords": ["Jenbacher Fasnacht", "Zillertal", "Tirol", "Faschingsfest", "Hexen-Masken", "Alpine Tradition"],
    },
    {
        "num": 38,
        "name": "Murauer Samsonumzug",
        "slug": "38-murauer-samsonumzug",
        "region": "Murtal",
        "bundesland": "Steiermark",
        "date": "Fronleichnamsfest (variabel, Juni)",
        "location": "Murau, Steiermark",
        "reading_time": "10 Min.",
        "category": "Brauchtum & Tradition",
        "subtitle": "Der Giant Samson trägt die Kraft des Frühsommers",
        "intro": "Der Murauer Samsonumzug ist ein einzigartiges Sommerfest, bei dem ein riesenhafter Holzfigur namens ‚Samson' durch die Straßen getragen wird. Diese bis zu 4 Meter hohe Figur, kunstvoll geschnitzt und bunt bemalt, verkörpert die biblische Stärke Samsons und symbolisiert gleichzeitig die Kraft der Natur im Frühsommer. Der Umzug findet zu Fronleichnam statt – einer Zeit, wenn die Erde in voller Blüte steht. Mit Musik, Trachtengitarre und grünen Zweigen wird die Figur in einer festlichen Prozession durch Murau getragen, während das ganze Dorf jubelt und tanzt.",
        "key_facts": [
            ("Zentral", "Riesenfigur Samson (3–4 Meter hoch)"),
            ("Material", "Holz, kunstvoll geschnitzt und handbemalt"),
            ("Ursprung", "Biblische Samson-Geschichte mit alpiner Waldtradition"),
            ("Zeitpunkt", "Fronleichnamsfest im Juni"),
            ("Kostüme", "Träger in Traditionstracht und grünen Blätterkostümen"),
            ("Musik", "Trachtengitarre, Bläser und volkstümliche Melodien"),
        ],
        "stats": [
            ("400+", "Jahre dokumentierte Geschichte"),
            ("4", "Meter Höhe der Samson-Figur"),
            ("8–10", "Starke Männer tragen die Figur"),
        ],
        "hero_image": "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1800",
        "fullbleed_image": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1800",
        "history_title": "Von biblischer Kraft zur alpinen Waldmagie",
        "history_text": "Der Murauer Samsonumzug verbindet zwei Welten: Die biblische Geschichte des starken Samson und die vorchristlichen Waldmagie-Traditionen der alpinen Gegenden. Die Samson-Figur war ursprünglich eine religiöse Figur – ein Symbol für Kraft und Segen – die bei Fronleichnam-Prozessionen getragen wurde. Mit der Zeit vermischte sich dies mit alpinen Fruchtbarkeitsbräuchen, bei denen grüne Zweige und Waldwesen in Prozessionen verehrt wurden.\n\nDie Murauer Samson-Tradition ist wahrscheinlich Jahrhunderte alt, mit erste schriftliche Hinweise aus dem 17. Jahrhundert. Die Figur wurde immer größer und spektakulärer – eine Art Wettbewerb zwischen Dorfgemeinschaften. Im 19. Jahrhundert erreichte der Brauch seine kulinarische Form. Nach dem Zweiten Weltkrieg geriet er in Vergessenheit, wurde aber in den 1980ern durch Kulturfreunde wiederbelebt. Heute ist der Murauer Samson-Umzug ein Symbol für die Kraft der alpine Tradition.",
        "history_timeline": [
            ("17. Jahrhundert", "Erste Erwähnungen in Murauer Kirchenbüchern"),
            ("18.–19. Jahrhundert", "Elaboration und Größe-Wettbewerbe"),
            ("20. Jahrhundert früh", "Blüte des Brauches, dann Vergessenheit"),
            ("1980er", "Wiederbelebung durch Kulturvereine"),
            ("Heute", "Wichtigster Feiertag in Murau"),
        ],
        "fullbleed_caption": "Die riesige Samson-Holzfigur wird von acht starken Männern in Tracht getragen",
        "traditions_title": "Die Kunst der Samson-Figur",
        "traditions_text": "Die Samson-Figur ist ein Meisterwerk der Schnitzkunst. Erfahrene Holzschnitzer – oft Familienbetriebe, die diese Kunst über Generationen weitergegeben haben – erschaffen die Figur mit handwerklicher Präzision. Samson wird typischerweise als bemuskulter biblischer Held dargestellt, oft mit langen Haaren und in klassischen Gewändern. Die Figur wird bunt bemalt – mit Gold, Rot, Blau und anderen leuchtenden Farben.\n\nDie Konstruktion ist ingenieurskundig: Eine innere Holzstruktur trägt das Gewicht und erlaubt es acht Männern, die Figur zu tragen. Grüne Zweige – Symbol der Frühling und Waldkraft – werden um die Figur gewickelt. Der Umzug selbst ist eine Choreographie: Mit langsamen, rhythmischen Schritten wird Samson durch die Straßen getragen, während das Publikum jubelt. Es ist nicht nur religiös-mythologisch, sondern auch körperlich und sensorisch.",
        "interlude_quote": "‚Samson trägt die Kraft der Berge und die Segen der Erde – ein Riese, der den Sommer ankündigt.'",
        "program_title": "Programm & Höhepunkte",
        "program": [
            ("08:00 Uhr", "Vorbereitung der Samson-Figur", "Letzte Details, Blätterschmuck"),
            ("10:00 Uhr", "Gottesdienst in der Pfarrkirche", "Fronleichnam-Messe"),
            ("11:00 Uhr", "Samson wird angehoben", "Acht starke Männer tragen ihn hoch"),
            ("11:30 Uhr", "Prozession durch Murau startet", "Mit Musik, Trachtengitarre und Tänzern"),
            ("14:00 Uhr", "Festmahl und Freude auf dem Marktplatz", "Musikalische Darbietungen und Tanz"),
        ],
        "gallery": [
            ("Die riesige, bunt bemalte Samson-Figur von Nahem", "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800"),
            ("Acht Träger in Tracht mit Samson auf Schultern", "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800"),
            ("Prozession mit grünen Zweigen und Trachtenmenschen", "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800"),
        ],
        "practical_info": [
            ("Datum", "Fronleichnamsfest – Sechs Wochen nach Ostern", "📅"),
            ("Anfahrt", "Von Graz ca. 100 km nordwärts nach Murau", "🚗"),
            ("Beste Beobachtung", "Marktplatz früh Platz suchen", "🏕️"),
            ("Tracht", "Willkommen in alpiner Tracht oder Alltagskleidung", "👕"),
            ("Verpflegung", "Traditionelle steirische Speisen in Gasthöfen", "🍽️"),
            ("Unterkunft", "Gasthöfe und Pensionen in Murau und Umgebung", "🏨"),
        ],
        "cta_text": "Besuchen Sie den Murauer Samson-Umzug und erleben Sie alpine Krafttradition!",
        "seo_title": "Murauer Samsonumzug – Riesenfigur und Fronleichnam — LassTreffen.at",
        "seo_description": "Murauer Samsonumzug: 4-Meter-Holzfigur, Fronleichnam-Prozession, grüne Zweige und Kraft-Tradition in Murau, Steiermark.",
        "keywords": ["Samson", "Murau", "Steiermark", "Fronleichnam", "Holzfigur", "Alpine Tradition"],
    },
    {
        "num": 39,
        "name": "Wörgler Christkindleinzug",
        "slug": "39-woergler-christkindleinzug",
        "region": "Bezirk Kufstein",
        "bundesland": "Tirol",
        "date": "24. Dezember (Heiligabend)",
        "location": "Wörgl, Tirol",
        "reading_time": "10 Min.",
        "category": "Brauchtum & Tradition",
        "subtitle": "Das Christkind wird durch die Stadt getragen – Liebreiz und Weihnachtszauber",
        "intro": "Der Wörgler Christkindleinzug ist eine liebliche, sanfte Weihnachtstradition, bei der eine Figur des Christkindes in einer festlichen Prozession durch die Stadt Wörgl getragen wird. Ein Kind in weißem, goldbesticktem Gewand verkörpert das Christkind, sitzend in einer kunstvollen Wiege oder Krippe, umgeben von Lichtern und Blumen. Diese Darstellung des Christkindes als himmlisches, schönes Wesen – nicht leidender, sterbender Säugling, sondern Licht und Hoffnung – prägt die lokale Weihnachtskultur und zieht Tausende zu dieser zarten Feier.",
        "key_facts": [
            ("Zentral", "Christkind-Figur in Wiege oder Krippe"),
            ("Verkörperung", "Kind in weißem Gewand mit Flügeln oder Gloriole"),
            ("Lichtquellen", "Unzählige Kerzen und Lichter schmücken die Prozession"),
            ("Musik", "Stille, kontemplative Weihnachtsmusik"),
            ("Teilnehmerzahl", "Hunderte von Gläubigen, Musikern, Engeln"),
            ("Kulturelle Funktion", "Trost, Hoffnung, spirituelle Reinigung vor Weihnacht"),
        ],
        "stats": [
            ("400+", "Jahre Tradition"),
            ("1.000+", "Kinder und Erwachsene in Engel-Kostümen"),
            ("5.000+", "Zuschauer und Teilnehmer"),
        ],
        "hero_image": "https://images.unsplash.com/photo-1470770903676-69b98201ea1c?w=1800",
        "fullbleed_image": "https://images.unsplash.com/photo-1529333166437-7750a6dd5a70?w=1800",
        "history_title": "Das Christkind als Hoffnungsbotschaft",
        "history_text": "Der Wörgler Christkindleinzug hat seine Wurzeln in der christlichen Tradition des Christkind-Glaubens, die besonders in der deutschsprachigen Welt verbreitet ist. Im Gegensatz zu anderen Kulturen, in denen der Weihnachtsmann oder Father Christmas dominant ist, wird in Österreich das Christkind selbst als Schenker der Weihnachtsgaben verstanden – eine theologische und poetische Darstellung der Inkarnation und des göttlichen Lichts.\n\nDie Prozession-Tradition entstand wahrscheinlich im Mittelalter, als Weihnachtsspiele in Kirchen aufgeführt wurden. Mit der Zeit wurde diese Theatralisierung populärer und Dörfer inszenieren ihre eigenen Christkindl-Prozessionen. Im Wörgl entwickelte sich eine besondere Version, die das Christkind nicht in Krippe-Szene, sondern in einer mobilen Wiege zeigt, getragen in einer Prozession mit Hunderten von Lichtern und Engeln. Diese bewegliche Theaterform schuf eine intensive emotionale Erfahrung.",
        "history_timeline": [
            ("Mittelalter", "Christkind-Spiele in Kirchen"),
            ("16.–17. Jahrhundert", "Prozession-Traditionen entwickeln sich"),
            ("18.–19. Jahrhundert", "Wörgler Christkindl-Prozession wird elaboriert"),
            ("20. Jahrhundert", "Blüte und Verbreitung in Tirol"),
            ("Heute", "Wichtigster Weihnachtsevent in Wörgl"),
        ],
        "fullbleed_caption": "Das Christkind in goldbesticktem Gewand wird in einer lichterfüllten Prozession getragen",
        "traditions_title": "Die Kostüme der Engel und das Christkind",
        "traditions_text": "Der Wörgler Christkindl-Zug ist visuell eine Symphonie aus Weiß, Gold und warmem Licht. Das Christkind selbst trägt ein langes, glänzendes weißes Kleid oder Gewand, oft bestickt mit Gold- und Silberfäden. Häufig trägt es auch Flügel oder eine Gloriole – die Darstellung ist himmlisch und schwebend, nicht erdgebunden.\n\nHunderte von Begleitern treten in Engel-Kostümen an – lange weiße Roben, Flügel aus Federn oder Stoff, Blumenkränze im Haar. Kinder und Erwachsene alike tragen Kerzen und Lichter. Die Musikbegleitung ist klassisch und sanft – Weihnachtslieder, Choräle, auf Orgel und Saiteninstumenten gespielt. Der Gesamteindruck ist einer Himmelsvision: Hell, Hoffnung gebend, heilig.",
        "interlude_quote": "‚Das Christkind leuchtet wie ein Stern in der Weihnachtsnacht – Hoffnung und Liebe in Menschengestalt.'",
        "program_title": "Programm & Höhepunkte",
        "program": [
            ("16:00 Uhr", "Vorbereitung der Prozession", "Christkind wird angekleidet, Engel sammeln sich"),
            ("17:00 Uhr", "Gottesdienst in der Wörgler Kirche", "Weihnachtsfeier mit Kirchengesang"),
            ("18:00 Uhr", "Christkindl-Prozession startet", "Mit Lichtern und Engels-Cortège"),
            ("19:00 Uhr", "Höhepunkt auf dem Marktplatz", "Das Christkind sitzet in stiller Anbetung"),
            ("20:00 Uhr", "Stille Andacht und Familienfeier", "Weihnachtslieder gemeinsam singen"),
        ],
        "gallery": [
            ("Nahaufnahme des Christkindes in goldbesticktem Gewand", "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800"),
            ("Hunderte von Engeln mit Kerzen in Prozession", "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800"),
            ("Lichtermeeres in der dunklen Weihnachtsnacht", "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800"),
        ],
        "practical_info": [
            ("Datum", "24. Dezember, Heiligabend (Beginn ca. 17–18 Uhr)", "📅"),
            ("Anfahrt", "Mit Bahn oder Auto nach Wörgl (50 Min ab Innsbruck)", "🚗"),
            ("Warm anziehen", "Dicke Mantel, Mütze, Handschuhe erforderlich", "🧥"),
            ("Kerzen", "Unbeschädigte Kerzen für Teilnahme willkommen", "🕯️"),
            ("Stille bewahren", "Kontemplative Atmosphäre – bitte keine lauten Gespräche", "🤐"),
            ("Fotografie", "Erlaubt, aber respektvolle Diskretion", "📸"),
        ],
        "cta_text": "Erleben Sie die himmlische Schönheit des Wörgler Christkindl-Zuges!",
        "seo_title": "Wörgler Christkindleinzug – Lichter und Hoffnung zu Heiligabend — LassTreffen.at",
        "seo_description": "Wörgler Christkindleinzug: Das Christkind in goldbesticktem Gewand, Engel-Prozession, tausend Lichter, stille Andacht zu Weihnacht.",
        "keywords": ["Christkindl", "Wörgl", "Heiligabend", "Tirol", "Weihnacht", "Prozession"],
    },
    {
        "num": 40,
        "name": "Kärntner Kirchtag",
        "slug": "40-kaerntner-kirchtag",
        "region": "Ganz Kärnten",
        "bundesland": "Kärnten",
        "date": "Sommer (variabel nach Ort)",
        "location": "Verschiedene Dörfer in Kärnten",
        "reading_time": "10 Min.",
        "category": "Brauchtum & Tradition",
        "subtitle": "Kirchenfest-Kultur mit Musik, Tanz und Gemeinschaftssinn",
        "intro": "Der Kärntner Kirchtag ist weniger ein einzelnes Fest als eine Serie von lokalen Kirchweih-Festen, die über den ganzen Sommer verteilt in Hunderten von Kärntner Dörfern stattfinden. Jedes Dorf feiert die Weihe seiner Pfarrkirche mit großer Festlichkeit: Musikkapellen spielen traditionelle Polkas und Volkstänze, regionale Speisen werden serviert, Trachten werden angelegt, und die ganze Gemeinde versammelt sich zu Gottesdienst, Festmahl und Tanz. Diese dezentrale, dorf-weise Feierkultur ist besonders authentisch und zeigt die ständige Kraft lokaler Gemeinschaften in Kärnten.",
        "key_facts": [
            ("Format", "Dezentrales Netzwerk von Kirchtags-Festen"),
            ("Anzahl", "100+ Kärntner Dörfer mit eigenen Kirchtags-Festen"),
            ("Zeitspanne", "Mai bis Oktober (Peak Juni–August)"),
            ("Kernelemente", "Gottesdienst, Musikkapelle, Trachten, Festessen, Tanz"),
            ("Regionalspezifik", "Jedes Dorf hat seine eigenen Traditionen"),
            ("Kulturelle Bedeutung", "Herz der Kärntner Dorf- und Trachtenkultur"),
        ],
        "stats": [
            ("500+", "Jahre Tradition"),
            ("100+", "Dörfer mit Kirchtags-Festen pro Saison"),
            ("50.000+", "Gesamtteilnehmer über den Sommer"),
        ],
        "hero_image": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1800",
        "fullbleed_image": "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1800",
        "history_title": "Von der Kirchweih-Feier zum Dorf-Fest",
        "history_text": "Die Kärntner Kirchtag-Tradition reicht bis ins Mittelalter zurück, als Kirchweih-Feste zentrale Gemeinschaftsereignisse waren. In Kärnten – einer Region mit stark ausgeprägter Dorf- und Trachtenkultur – entwickelten sich diese Kirchenfeste zu Institutionen von großer Bedeutung. Jedes Dorf hatte seinen eigenen Kirchweih-Termin, oft zeitlich mit Erntefesten oder lokalen Ereignissen verbunden.\n\nMit der Zeit wurden die Kirchtags-Feste immer mehr zu Zentren der sozialen Interaktion: Junge Menschen trafen sich, es gab Tänze und Musik, regionale Speisen wurden serviert. Die Kirchtags-Kultur wurde zum Rückgrat der lokalen Identität. Im 19. Jahrhundert entstanden spezialisierte Musikkapellen, die nur zu Kirchtags-Festen spielten. Im 20. Jahrhundert, trotz Säkularisierung und Modernisierung, blieben die Kärntner Kirchtags-Feste lebending und wurden als Bestandteil lokaler Volkskultur gepflegt.",
        "history_timeline": [
            ("Mittelalter", "Kirchweih-Feste als Gemeinschaftsereignisse"),
            ("16.–18. Jahrhundert", "Elaboration zu lokalen Festen mit Musik und Tanz"),
            ("19. Jahrhundert", "Entstehung spezialisierter Musikkapellen"),
            ("20. Jahrhundert", "Blüte trotz Modernisierungsdrucks"),
            ("Heute", "Renaissance und Bewahrung als immaterielles Kulturerbe"),
        ],
        "fullbleed_caption": "Musikkapelle und Trachtengruppen bei Kärntner Kirchtag-Feier",
        "traditions_title": "Das Kirchtags-Fest: Ablauf und Bedeutung",
        "traditions_text": "Ein typisches Kärntner Kirchtags-Fest folgt einem bewährten Muster, das über Jahrhunderte verfeinert wurde. Am Morgen gibt es einen festlichen Gottesdienst mit Kirchengesang und Segen. Nach dem Gottesdienst versammelt sich die Gemeinde zum gemeinsamen Festmahl, oft in Gasthöfen oder auf Festplätzen. Das Essen ist traditionell kärntnerisch: Kasnocken, Erdäpfelpuffer, Erdäpfelsuppe, Knackwurst, Schnitzel, Topfentorte. Bier und Wein fließen reichlich.\n\nDanach spielen Musikkapellen auf: Polkas, Mazurkas, Walzer und Jodler. Menschen in Tracht – Frauen in bunten Röcken mit Schürzen, Männer in Lederhose – tanzen und schreiten auf. Dies ist kein kommerzielles Volksfest, sondern ein echtes Dorf-Ereignis, bei dem sich der ganze Ort wiedertrifft, Neuigkeiten austauscht, alte Bekannte begrüßt und die Gemeinschaft erneuert.",
        "interlude_quote": "‚Der Kirchtag ist das Herz des Kärntner Dorfes – an diesem Tag pulsiert das Leben der Gemeinschaft.'",
        "program_title": "Programm & Höhepunkte",
        "program": [
            ("10:00 Uhr", "Festgottesdienst in der Dorfkirche", "Mit Kirchenchor und Orgelmusik"),
            ("11:30 Uhr", "Umzug zu Festplatz oder Gasthof", "Mit Musikkapelle an der Spitze"),
            ("12:00 Uhr", "Festmahl beginnt", "Traditionelle kärntnerische Speisen"),
            ("15:00 Uhr", "Musikkapelle-Konzert auf der Bühne", "Polkas, Walzer, Jodler"),
            ("17:00 Uhr", "Tanz auf dem Festplatz bis Abend", "Mit lebender Musik"),
        ],
        "gallery": [
            ("Musikkapelle in Tracht beim Konzert", "https://images.unsplash.com/photo-1433086966358-54859d0ed716?w=800"),
            ("Tänzer in traditionellen Kärntner Trachten", "https://images.unsplash.com/photo-1470770903676-69b98201ea1c?w=800"),
            ("Festplatz voll mit feierndem Volk und Festzelt", "https://images.unsplash.com/photo-1482192505345-5655af888cc4?w=800"),
        ],
        "practical_info": [
            ("Welches Dorf?", "Kalender der Kärntner Kirchtags-Feste online prüfen", "📅"),
            ("Beste Zeit", "Juni–August für die meisten Feste", "☀️"),
            ("Tracht erwünscht", "Nicht erforderlich, aber willkommen", "👕"),
            ("Verpflegung", "Traditionelle kärntnerische Gasthöfe im Dorf", "🍽️"),
            ("Übernachtung", "Gasthöfe und Pensionen überall in Kärnten", "🏨"),
            ("Musik", "Beste Kuratorien sind ländliche Musikkapellen aus Generation", "🎵"),
        ],
        "cta_text": "Erleben Sie Kärntner Dorf-Kultur und Gemeinschaftssinn beim Kirchtag!",
        "seo_title": "Kärntner Kirchtag – Sommer-Feste in Dörfern Kärntens — LassTreffen.at",
        "seo_description": "Kärntner Kirchtag: Kirchweih-Feste mit Musikkapelle, Trachten, Kasnocken und Gemeinde-Tänzen in 100+ Kärntner Dörfern über den Sommer.",
        "keywords": ["Kirchtag", "Kärnten", "Kirchweih", "Trachten", "Volksfest", "Dorfkultur"],
    },
]
