import type { NextConfig } from 'next';

const nextConfig: NextConfig = {
  images: {
    remotePatterns: [
      { protocol: 'https', hostname: 'images.unsplash.com' },
      { protocol: 'https', hostname: 'lh3.googleusercontent.com' },
      { protocol: 'https', hostname: '**.supabase.co' },
      { protocol: 'https', hostname: '**.burgenland.info' },
      { protocol: 'https', hostname: '**.eventim.at' },
      { protocol: 'https', hostname: '**.oeticket.com' },
      { protocol: 'https', hostname: '**.meinbezirk.at' },
      { protocol: 'https', hostname: '**.events.at' },
      { protocol: 'https', hostname: '**.feverup.com' },
      { protocol: 'https', hostname: '**.stadthalle.com' },
      { protocol: 'https', hostname: '**.praterwien.com' },
      { protocol: 'https', hostname: '**.partytimer.at' },
      { protocol: 'https', hostname: '**.wien.info' },
      { protocol: 'https', hostname: '**.grelleforelle.com' },
      { protocol: 'https', hostname: '**.flex.at' },
      { protocol: 'https', hostname: '**.pratersauna.tv' },
      { protocol: 'https', hostname: '**.praterdome.at' },
      { protocol: 'https', hostname: '**.volksgarten.at' },
      { protocol: 'https', hostname: '**.fluc.at' },
      { protocol: 'https', hostname: '**.daswerk.org' },
      { protocol: 'https', hostname: '**.sassvienna.com' },
      { protocol: 'https', hostname: '**.camera-club.at' },
      { protocol: 'https', hostname: '**.u4.at' },
      { protocol: 'https', hostname: '**.falter.at' },
      { protocol: 'https', hostname: '**.neusiedlersee.com' },
      { protocol: 'https', hostname: '**.ticketmaster.com' },
      { protocol: 'https', hostname: '**.ticketmaster.at' },
      { protocol: 'https', hostname: '**.kaernten.live' },
      { protocol: 'https', hostname: '**.veranstaltungskalender.net' },
      { protocol: 'https', hostname: '**.ganz-wien.at' },
      { protocol: 'https', hostname: '**.posthof.at' },
      { protocol: 'https', hostname: '**.kultur.graz.at' },
      { protocol: 'https', hostname: '**.popculture.at' },
      { protocol: 'https', hostname: '**.rockhouse.at' },
      { protocol: 'https', hostname: '**.linztermine.at' },
      { protocol: 'https', hostname: '**.burgenland.at' },
      { protocol: 'https', hostname: '**.burgenland.info' },
      { protocol: 'https', hostname: '**.soelden.com' },
      { protocol: 'https', hostname: '**.oetztal.com' },
      { protocol: 'https', hostname: '**.ischgl.com' },
      { protocol: 'https', hostname: '**.saalbach.com' },
      { protocol: 'https', hostname: '**.mayrhofen.at' },
      { protocol: 'https', hostname: '**.zellamsee-kaprun.com' },
      { protocol: 'https', hostname: '**.stubaital.at' },
      { protocol: 'https', hostname: '**.bodensee-vorarlberg.com' },
      { protocol: 'https', hostname: '**.events.tt' },
      { protocol: 'https', hostname: '**.vorarlberg.travel' },
      { protocol: 'https', hostname: '**.esterhazy.at' },
      // Generic GEM2GO Gemeinden (municipality sites have unpredictable domains)
      { protocol: 'https', hostname: '**.gv.at' },
      { protocol: 'http', hostname: '**.gv.at' },
    ],
  },
  // better-sqlite3 only used by scraper scripts, not by API routes
  serverExternalPackages: ['better-sqlite3'],
};

export default nextConfig;
