import type { ListedEvent } from './link-events';

export interface DraftInput {
  orgName: string | null;
  domain: string;
  bundesland: string | null;
  events: ListedEvent[];
}

/** Appended to every draft body — §107/DSGVO opt-out + sender identity.
 *  Not generated by the model so it's guaranteed present + consistent. */
export const COMPLIANCE_FOOTER =
  '\n\n—\n' +
  'Falls kein Interesse besteht, genügt eine kurze Antwort — dann melde ich mich nicht wieder.\n' +
  'lasstreffen.at — Veranstaltungen in ganz Österreich · Impressum: https://lasstreffen.at/impressum';

/**
 * Builds the prompt for a REACH-/COOPERATION outreach mail. Ziel ist NICHT,
 * dass der Empfänger seine Events bei uns postet (machen wir selbst), sondern
 * eine Kooperation, die lasstreffen.at Reichweite bringt und dem Empfänger
 * einen kostenlosen Nutzen für sein Publikum liefert.
 */
export function buildDraftPrompt(input: DraftInput): string {
  const recipient = input.orgName ?? input.domain;
  const hasEvents = input.events.length > 0;
  // Social Proof: Aufrufzahlen nur nennen, wenn sie beeindrucken (>= 20 in
  // 30 Tagen) — "3 Aufrufe" wäre ein Anti-Argument. Der Draft-Winkel bleibt
  // Reichweiten-Kooperation (PR #66), die Zahl stärkt nur den Einstieg.
  const fmtEvent = (e: DraftInput['events'][number]) =>
    e.views != null && e.views >= 20
      ? `${e.title} (${e.views} Aufrufe bei uns in den letzten 30 Tagen)`
      : e.title;
  const eventLine = hasEvents
    ? `Vertrauens-Einstieg (NICHT als Bitte): Wir featuren bereits Veranstaltungen aus eurem Umfeld auf lasstreffen.at, z.B. ${input.events.slice(0, 2).map(fmtEvent).join(', ')}.`
    : '';

  return [
    'Du schreibst eine kurze, persönliche KOOPERATIONS-Mail auf Deutsch (Du/Ihr-Form, österreichischer Ton, freundlich, nicht werblich) im Namen von lasstreffen.at — einer kostenlosen Plattform, die ALLE Veranstaltungen einer Region auf einer Karte bündelt.',
    `Empfänger: ${recipient} (${input.domain})${input.bundesland ? `, ${input.bundesland}` : ''}.`,
    'ZIEL: eine Kooperation, die lasstreffen.at REICHWEITE bringt und dem Empfänger einen echten Nutzen für seine Gäste/Besucher/Community gibt. Schlage EINEN konkreten, für genau diesen Empfänger plausiblen Weg vor (wähle selbst anhand von Name/Art des Empfängers):',
    '- Flyer / Aushang / QR-Code bei ihnen vor Ort (z.B. Tourismusbüro, Hotel-Rezeption, Eingang, Gemeindeamt)\n- ein Link zu lasstreffen.at auf ihrer Website (z.B. unter „Was ist los?" / Freizeit-Tipps)\n- eine Erwähnung im Newsletter / in ihren Kanälen / eine gegenseitige Empfehlung',
    'NUTZEN FÜR DEN EMPFÄNGER (klar machen): seine Gäste/Besucher finden mit einem Klick ALLE Events der Region — das macht den Empfänger hilfreicher und kostet ihn nichts.',
    'WICHTIG: Bitte NICHT darum, dass sie ihre eigenen Veranstaltungen bei uns posten oder listen — das machen wir bereits selbst. Es geht ausschließlich um Sichtbarkeit/Reichweite für lasstreffen.at im Tausch gegen einen kostenlosen Service für ihr Publikum.',
    eventLine,
    'Anforderungen: höchstens ~90 Wörter, EIN klarer Vorschlag/Call-to-action, ehrlich, kein Druck, keine Floskeln, keine erfundenen Fakten. Schreibe KEINE Signatur und KEIN Impressum (wird separat angehängt).',
    'Antworte ausschließlich als JSON: {"subject": "...", "body": "..."}.',
  ].filter(Boolean).join('\n\n');
}
