import type { ListedEvent } from './link-events';

export interface DraftInput {
  orgName: string | null;
  domain: string;
  bundesland: string | null;
  events: ListedEvent[];
}

/** Appended to every draft body — §107/DSGVO opt-out + sender identity.
 *  Not generated by the model so it's guaranteed present + consistent. */
export const COMPLIANCE_FOOTER =
  '\n\n—\n' +
  'Falls kein Interesse besteht, genügt eine kurze Antwort — dann melde ich mich nicht wieder.\n' +
  'lasstreffen.at — Veranstaltungen in ganz Österreich · Impressum: https://lasstreffen.at/impressum';

export function buildDraftPrompt(input: DraftInput): string {
  const recipient = input.orgName ?? input.domain;
  const hasEvents = input.events.length > 0;
  const eventLines = input.events.map((e) => `- ${e.title} (${e.url})`).join('\n');

  const angle = hasEvents
    ? `Aufhänger: Wir listen bereits diese Veranstaltung(en) von euch auf lasstreffen.at:\n${eventLines}\n` +
      'Bitte freundlich fragen, ob ihr von eurer Website auf eure Event-Seite bei uns zurückverlinken möchtet (gegenseitiger Nutzen: mehr Reichweite, mehr Besucher).'
    : 'Aufhänger: lasstreffen.at ist eine kostenlose, regionale Event-Plattform für ganz Österreich, eure Veranstaltungen passen perfekt. ' +
      'Bitte freundlich fragen, ob ihr eure Termine bei uns listen lassen und/oder verlinken möchtet.';

  return [
    'Du schreibst eine kurze, persönliche Outreach-E-Mail auf Deutsch (Du/Ihr-Form, österreichischer Ton, freundlich, NICHT werblich oder spammy) im Namen von lasstreffen.at.',
    `Empfänger: ${recipient} (${input.domain})${input.bundesland ? `, ${input.bundesland}` : ''}.`,
    angle,
    'Anforderungen: höchstens ~90 Wörter, EIN klarer Call-to-action, ehrlich, keine Floskeln, keine erfundenen Fakten, kein Druck. Schreibe KEINE Signatur und KEIN Impressum (wird separat angehängt).',
    'Antworte ausschließlich als JSON: {"subject": "...", "body": "..."}.',
  ].join('\n\n');
}
