/**
 * Generic municipality event scraper.
 * Works with any municipality website that has an event page with
 * standard German date formats (DD.MM.YYYY) and event listings.
 *
 * Uses data/gemeinden-event-pages.json (generated by probe-gemeinden.ts)
 * to know which municipalities have event pages and their URLs.
 *
 * Parsing strategy:
 * 1. WordPress event plugins (wp-event-manager, the-events-calendar, etc.)
 * 2. Typo3 event extensions
 * 3. Generic HTML: find date patterns + nearby text blocks as events
 */

import { BaseScraper } from './BaseScraper';
import type { ScrapedEvent } from '@/types/events';
import * as cheerio from 'cheerio';
import { readFileSync, existsSync } from 'fs';
import { join } from 'path';
import { detectNextPage, detectMonthNavigation, MAX_PAGES_PER_SITE } from './pagination';
import { extractGem2goDetail } from './gem2go-detail';

interface GemeindeEventPage {
  gemeinde: {
    name: string;
    website: string;
    plz: string;
    bezirk: string;
    bundesland: string;
    lat: number;
    lng: number;
  };
  eventPageUrl: string;
  path: string;
  dateCount: number;
  eventKeywords: number;
  htmlSize: number;
}

export class GenericGemeindeScraper extends BaseScraper {
  name = 'gemeinden-generic';
  private delay = 1000; // 1s between municipalities
  private timeoutMs = 8000;

  private MONTH_MAP: Record<string, string> = {
    'jänner': '01', 'januar': '01', 'jan': '01',
    'februar': '02', 'feb': '02',
    'märz': '03', 'mär': '03', 'mar': '03',
    'april': '04', 'apr': '04',
    'mai': '05',
    'juni': '06', 'jun': '06',
    'juli': '07', 'jul': '07',
    'august': '08', 'aug': '08',
    'september': '09', 'sep': '09',
    'oktober': '10', 'okt': '10',
    'november': '11', 'nov': '11',
    'dezember': '12', 'dez': '12',
  };

  async scrape(): Promise<ScrapedEvent[]> {
    const dataPath = join(process.cwd(), 'data', 'gemeinden-event-pages.json');
    if (!existsSync(dataPath)) {
      console.log('No gemeinden-event-pages.json found. Run probe-gemeinden.ts first.');
      return [];
    }

    const pages: GemeindeEventPage[] = JSON.parse(readFileSync(dataPath, 'utf8'));
    console.log(`  Loading ${pages.length} municipality event pages...`);

    const allEvents: ScrapedEvent[] = [];
    let processed = 0;
    let totalFound = 0;

    for (const page of pages) {
      processed++;
      try {
        const events = await this.scrapeGemeinde(page);
        if (events.length > 0) {
          allEvents.push(...events);
          totalFound += events.length;
          console.log(`  ✓ [${processed}/${pages.length}] ${page.gemeinde.name}: ${events.length} events`);
        }
      } catch (e) {
        // Skip silently
      }

      if (processed % 50 === 0 && totalFound === 0) {
        console.log(`  [${processed}/${pages.length}] ... ${allEvents.length} events total`);
      }

      await new Promise(r => setTimeout(r, this.delay));
    }

    console.log(`  Total: ${allEvents.length} events from ${pages.length} municipalities`);
    return allEvents;
  }

  private async scrapeGemeinde(page: GemeindeEventPage): Promise<ScrapedEvent[]> {
    const html = await this.fetchPageSafe(page.eventPageUrl);
    if (!html) return [];

    const g = page.gemeinde;
    const bundesland = this.normalizeBundesland(g.bundesland);

    // Parse first page
    let allEvents = this.parsePage(html, page);

    // ── Pagination: follow next pages ──
    if (allEvents.length > 0) {
      let currentHtml = html;
      let currentUrl = page.eventPageUrl;
      const visitedUrls = new Set<string>([currentUrl]);

      for (let p = 1; p < MAX_PAGES_PER_SITE; p++) {
        const { nextUrl } = detectNextPage(currentHtml, currentUrl);
        if (!nextUrl || visitedUrls.has(nextUrl)) break;
        visitedUrls.add(nextUrl);

        const nextHtml = await this.fetchPageSafe(nextUrl);
        if (!nextHtml) break;

        const nextEvents = this.parsePage(nextHtml, { ...page, eventPageUrl: nextUrl });
        if (nextEvents.length === 0) break;

        allEvents.push(...nextEvents);
        currentHtml = nextHtml;
        currentUrl = nextUrl;
        await new Promise(r => setTimeout(r, 500)); // rate limit between pages
      }

      // ── Month navigation: try upcoming months ──
      if (allEvents.length > 0 && allEvents.length < 5) {
        // Few events found — might be a month-view calendar, try next months
        const monthUrls = detectMonthNavigation(html, page.eventPageUrl);
        for (const mu of monthUrls) {
          if (visitedUrls.has(mu.url)) continue;
          visitedUrls.add(mu.url);

          const mHtml = await this.fetchPageSafe(mu.url);
          if (!mHtml) continue;

          const mEvents = this.parsePage(mHtml, { ...page, eventPageUrl: mu.url });
          allEvents.push(...mEvents);
          await new Promise(r => setTimeout(r, 500));
        }
      }
    }

    // Detail-page enrichment: fetch each event's source_url and pull
    // description/address/image/price out via the universal extractor.
    // Listing parsers above tend to capture only title + date + small teaser;
    // the detail page usually has the full event. Same approach as Gem2GoScraper.
    if (this.enableDetailEnrichment) {
      await this.enrichEventsFromDetailPages(allEvents, page.eventPageUrl);
    }

    // Enrich with gemeinde metadata
    return allEvents.map(e => ({
      ...e,
      bundesland,
      latitude: e.latitude || g.lat,
      longitude: e.longitude || g.lng,
      postal_code: e.postal_code || g.plz,
      district: e.district || g.bezirk,
    }));
  }

  /** Detail-fetch toggle. ON by default — listing-level data is usually too thin.
   *  Renamed from `enrichFromDetail` to avoid collision with the protected
   *  BaseScraper.enrichFromDetail() method added 2026-05-21. */
  private readonly enableDetailEnrichment = true;
  /** Delay between detail-page fetches within the same gemeinde (ms). */
  private readonly detailDelayMs = 250;
  /** Per-detail-page fetch timeout. */
  private readonly detailTimeoutMs = 8000;

  /**
   * For each event with a distinct source_url, fetch the detail page and
   * merge the universal extractor's findings. Detail values win for structural
   * fields (address, postal_code, location_name, image_url) — listing parsers
   * often concatenate sub-spans without separators. Description merges by
   * "longer wins". Errors swallowed per-event.
   */
  private async enrichEventsFromDetailPages(events: ScrapedEvent[], listingUrl: string): Promise<void> {
    for (const e of events) {
      const url = e.source_url;
      if (!url || url === listingUrl) continue;
      try {
        const html = await this.fetchPageSafe(url);
        if (!html) continue;
        const det = extractGem2goDetail(html);

        if (det.address) e.address = det.address;
        if (det.postal_code) e.postal_code = det.postal_code;
        if (det.location_name && (!e.location_name || e.location_name.length < det.location_name.length)) {
          e.location_name = det.location_name;
        }
        if (det.image_url) e.image_url = det.image_url;
        if (!e.description || (det.description && e.description.length < det.description.length)) {
          if (det.description) e.description = det.description;
        }
        if (!e.price_text && det.price_text) e.price_text = det.price_text;
        if (e.price_min === undefined && det.price_min !== undefined) e.price_min = det.price_min;
        if (e.price_max === undefined && det.price_max !== undefined) e.price_max = det.price_max;
        if (!e.organizer && det.organizer) e.organizer = det.organizer;
      } catch {
        // swallow per-event errors
      }
      await new Promise(r => setTimeout(r, this.detailDelayMs));
    }
  }

  /** Parse a single page with all strategies */
  private parsePage(html: string, page: GemeindeEventPage): ScrapedEvent[] {
    const $ = cheerio.load(html);
    let events = this.parseWordPressEvents($, page);
    if (events.length === 0) events = this.parseTypo3Events($, page);
    if (events.length === 0) events = this.parseGenericEvents($, page);
    return events;
  }

  // ─── WordPress Event Plugins ────────────────────────────────────────

  private parseWordPressEvents($: cheerio.CheerioAPI, page: GemeindeEventPage): ScrapedEvent[] {
    const events: ScrapedEvent[] = [];
    const g = page.gemeinde;

    // WP Event Manager
    $('div.event_listing, article.type-event_listing, .wpem-event-listing').each((_, el) => {
      const $el = $(el);
      const title = $el.find('.wpem-heading, .event_listing-title, h3, h2').first().text().trim();
      const dateText = $el.find('.event-date, .wpem-event-date, time').first().text().trim();
      const location = $el.find('.event-location, .wpem-event-location').first().text().trim();
      const link = $el.find('a').first().attr('href');
      const desc = $el.find('.event-description, .wpem-event-description, p').first().text().trim();

      if (!title) return;
      const date = this.parseDate(dateText);

      events.push({
        source_id: `gemeinden-generic-${g.plz}-${this.slugify(title)}`,
        source_name: this.name,
        source_url: link ? new URL(link, page.eventPageUrl).href : page.eventPageUrl,
        title,
        description: desc || undefined,
        start_date: date || new Date().toISOString().split('T')[0],
        location_name: location || g.name,
        category: this.guessCategory(title + ' ' + desc),
      });
    });

    // The Events Calendar (Tribe)
    if (events.length === 0) {
      $('.tribe-events-list .type-tribe_events, .tribe-common-g-row').each((_, el) => {
        const $el = $(el);
        const title = $el.find('.tribe-events-list-event-title, .tribe-event-title, h2, h3').first().text().trim();
        const dateText = $el.find('.tribe-events-schedule, .tribe-event-date-start, time, abbr').first().text().trim();
        const link = $el.find('a').first().attr('href');

        if (!title) return;
        const date = this.parseDate(dateText);

        events.push({
          source_id: `gemeinden-generic-${g.plz}-${this.slugify(title)}`,
          source_name: this.name,
          source_url: link ? new URL(link, page.eventPageUrl).href : page.eventPageUrl,
          title,
          start_date: date || new Date().toISOString().split('T')[0],
          location_name: g.name,
          category: this.guessCategory(title),
        });
      });
    }

    return events;
  }

  // ─── Typo3 Event Extensions ─────────────────────────────────────────

  private parseTypo3Events($: cheerio.CheerioAPI, page: GemeindeEventPage): ScrapedEvent[] {
    const events: ScrapedEvent[] = [];
    const g = page.gemeinde;

    // Typo3 wt_eventman, cal, etc.
    $('.event-list-item, .tx-wteventman .event, .tx-cal-event, article.event, .news-list-item').each((_, el) => {
      const $el = $(el);
      const title = $el.find('h2, h3, .event-title, .news-title, a').first().text().trim();
      const dateText = $el.find('.event-date, .date, time, .news-date').first().text().trim();
      const link = $el.find('a').first().attr('href');
      const desc = $el.find('.event-teaser, .event-description, p, .news-teaser').first().text().trim();

      if (!title || title.length < 5) return;
      const date = this.parseDate(dateText);
      if (!date) return; // Must have a valid date for Typo3

      events.push({
        source_id: `gemeinden-generic-${g.plz}-${this.slugify(title)}`,
        source_name: this.name,
        source_url: link ? new URL(link, page.eventPageUrl).href : page.eventPageUrl,
        title,
        description: desc || undefined,
        start_date: date,
        location_name: g.name,
        category: this.guessCategory(title + ' ' + (desc || '')),
      });
    });

    return events;
  }

  // ─── Generic HTML Parser ────────────────────────────────────────────

  private parseGenericEvents($: cheerio.CheerioAPI, page: GemeindeEventPage): ScrapedEvent[] {
    const events: ScrapedEvent[] = [];
    const g = page.gemeinde;
    const seen = new Set<string>();

    // Strategy: Find all elements containing a date pattern DD.MM.YYYY
    // Then extract the nearest heading/text as the event title
    const body = $.html();

    // Find date patterns with surrounding context
    const dateRegex = /(\d{1,2})\.(\d{1,2})\.(20\d{2})/g;
    let match;

    // First try: look for list items, table rows, or divs that contain dates
    $('li, tr, div, article, section').each((_, el) => {
      const $el = $(el);
      const text = $el.text();
      const dateMatch = text.match(/(\d{1,2})\.(\d{1,2})\.(20\d{2})/);
      if (!dateMatch) return;

      // Skip if this is a huge container (not specific enough)
      if (text.length > 1000) return;
      // Skip if too small
      if (text.length < 10) return;

      const day = dateMatch[1].padStart(2, '0');
      const month = dateMatch[2].padStart(2, '0');
      const year = dateMatch[3];
      const dateStr = `${year}-${month}-${day}`;

      // Skip past dates
      if (new Date(dateStr) < new Date('2025-01-01')) return;

      // Extract title: try heading first, then first text node, then full text
      let title = $el.find('h2, h3, h4, a, strong, b').first().text().trim();
      if (!title || title.length < 5) {
        // Use the text but remove the date
        title = text.replace(/\d{1,2}\.\d{1,2}\.20\d{2}/g, '').trim();
        // Take first meaningful line
        const lines = title.split(/\n/).map(l => l.trim()).filter(l => l.length > 3);
        title = lines[0] || title;
      }

      // Clean up title
      title = title.replace(/\s+/g, ' ').trim();
      if (title.length < 5 || title.length > 200) return;

      const key = `${dateStr}-${title.substring(0, 30)}`;
      if (seen.has(key)) return;
      seen.add(key);

      // Try to find a link
      const link = $el.find('a').first().attr('href');

      // Try to extract time
      const timeMatch = text.match(/(\d{1,2})[:.:](\d{2})\s*(?:Uhr|h)?/);
      const startDate = timeMatch
        ? `${dateStr}T${timeMatch[1].padStart(2, '0')}:${timeMatch[2]}`
        : dateStr;

      events.push({
        source_id: `gemeinden-generic-${g.plz}-${this.slugify(title)}-${dateStr}`,
        source_name: this.name,
        source_url: link ? new URL(link, page.eventPageUrl).href : page.eventPageUrl,
        title,
        start_date: startDate,
        location_name: g.name,
        category: this.guessCategory(title),
      });
    });

    return events;
  }

  // ─── Helpers ────────────────────────────────────────────────────────

  private async fetchPageSafe(url: string): Promise<string | null> {
    try {
      const r = await fetch(url, {
        redirect: 'follow',
        signal: AbortSignal.timeout(this.timeoutMs),
        headers: {
          'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
          'Accept': 'text/html',
          'Accept-Language': 'de-AT,de;q=0.9',
        },
      });
      if (!r.ok) return null;
      return await r.text();
    } catch {
      return null;
    }
  }

  private parseDate(text: string): string | null {
    if (!text) return null;

    // Try DD.MM.YYYY
    const numMatch = text.match(/(\d{1,2})\.(\d{1,2})\.(20\d{2})/);
    if (numMatch) {
      return `${numMatch[3]}-${numMatch[2].padStart(2, '0')}-${numMatch[1].padStart(2, '0')}`;
    }

    // Try "DD. Monat YYYY" (German month names)
    const wordMatch = text.match(/(\d{1,2})\.?\s*(\w+)\s+(20\d{2})/);
    if (wordMatch) {
      const month = this.MONTH_MAP[wordMatch[2].toLowerCase()];
      if (month) {
        return `${wordMatch[3]}-${month}-${wordMatch[1].padStart(2, '0')}`;
      }
    }

    return null;
  }

  private normalizeBundesland(bl: string): string {
    return bl.toLowerCase()
      .replace('ö', 'oe')
      .replace('ä', 'ae')
      .replace('ü', 'ue');
  }

  private slugify(text: string): string {
    return text.toLowerCase()
      .replace(/[äÄ]/g, 'ae').replace(/[öÖ]/g, 'oe').replace(/[üÜ]/g, 'ue').replace(/ß/g, 'ss')
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '')
      .substring(0, 60);
  }

  private guessCategory(text: string): string {
    const lower = text.toLowerCase();
    if (/konzert|musik|band|chor|orchester|jazz|rock|pop|unplugged/.test(lower)) return 'Musik';
    if (/sport|turnier|lauf|marathon|fußball|tennis|wanderung|radtour/.test(lower)) return 'Sport';
    if (/markt|flohmarkt|bauernmarkt|weihnachtsmarkt|ostermarkt/.test(lower)) return 'Märkte';
    if (/kultur|theater|kabarett|lesung|ausstellung|museum|vernissage/.test(lower)) return 'Kultur';
    if (/kinder|familie|basteln|spielen|feriencamp/.test(lower)) return 'Familie';
    if (/wein|kulinarik|verkostung|genuss|heuriger|brunch/.test(lower)) return 'Wein & Kulinarik';
    if (/wanderung|natur|garten|wald|berg|alm/.test(lower)) return 'Natur';
    if (/kirche|messe|gottesdienst|wallfahrt|firmung|kommunion/.test(lower)) return 'Sonstiges';
    return 'Sonstiges';
  }
}
