/**
 * Generic municipality event scraper.
 * Works with any municipality website that has an event page with
 * standard German date formats (DD.MM.YYYY) and event listings.
 *
 * Uses data/gemeinden-event-pages.json (generated by probe-gemeinden.ts)
 * to know which municipalities have event pages and their URLs.
 *
 * Parsing strategy:
 * 1. WordPress event plugins (wp-event-manager, the-events-calendar, etc.)
 * 2. Typo3 event extensions
 * 3. Generic HTML: find date patterns + nearby text blocks as events
 */

import { BaseScraper } from './BaseScraper';
import type { ScrapedEvent } from '@/types/events';
import * as cheerio from 'cheerio';
import { readFileSync, existsSync } from 'fs';
import { join } from 'path';
import { detectNextPage, detectMonthNavigation, MAX_PAGES_PER_SITE } from './pagination';
import { extractGem2goDetail } from './gem2go-detail';
import { isUsableDetailHref } from './gemeinde-event-discovery';
import { applyGemeindeContext } from './gemeinde-context';
import { withStammdaten, type GemeindeStammdaten } from './gemeinden/stammdaten';
import { firstText, isTitleCandidate } from './event-title';

// Die Datei führt nur die Identität der Gemeinde; PLZ, Bezirk und
// Mittelpunkt ergänzt withStammdaten() aus der Stammdatei.
interface GemeindeEventPageRaw {
  gemeinde: { name: string; website: string; bundesland: string; idKey: string; region?: boolean };
  eventPageUrl: string;
  path: string;
  dateCount: number;
  eventKeywords: number;
  htmlSize: number;
}

const DATE_RE = /(\d{1,2})\.(\d{1,2})\.(20\d{2})/g;

/** Alle Datumsangaben D.M.YYYY im Text als YYYY-MM-DD, in Fundreihenfolge. */
function findDates(text: string): string[] {
  return [...text.matchAll(DATE_RE)].map(
    m => `${m[3]}-${m[2].padStart(2, '0')}-${m[1].padStart(2, '0')}`,
  );
}

/**
 * Uhrzeit (HH:MM) aus einem Listen-Eintrag. Datumsangaben werden vorher
 * entfernt: sonst liest "14.10.2026" sich als 14:10 (Prod-Befund
 * 2026-10-06: die Minute war bei fast allen Events der Monat). Ein Punkt
 * als Trenner zählt nur mit folgendem "Uhr" ("19.30 Uhr"), der Doppelpunkt
 * immer. Stunden/Minuten außerhalb des Tages gelten als keine Uhrzeit.
 */
export function extractTimeOfDay(text: string): string | null {
  // Datumsfragmente auch ohne Jahr ("9.11.") und mit Jahr entfernen.
  const withoutDates = text.replace(/\d{1,2}\.\d{1,2}\.(?:\d{2,4})?/g, ' ');
  const re = /(?<![\d:])(\d{1,2})(?::(\d{2})(?!\d)|\.(\d{2})(?=\s*Uhr))/g;
  for (const m of withoutDates.matchAll(re)) {
    const h = Number(m[1]);
    const min = Number(m[2] ?? m[3]);
    if (h <= 23 && min <= 59) return `${String(h).padStart(2, '0')}:${String(min).padStart(2, '0')}`;
  }
  return null;
}

/** Linktexte, die kein Event benennen ("mehr Informationen" o. ä.). */
const GENERIC_LINK_TEXT = /^(mehr( informationen| infos?| erfahren| lesen)?|weiter(lesen)?|details?|zur veranstaltung|read more)\W*$/i;

interface GemeindeEventPage {
  gemeinde: GemeindeStammdaten & { website: string; region?: boolean };
  eventPageUrl: string;
  path: string;
  dateCount: number;
  eventKeywords: number;
  htmlSize: number;
}

export class GenericGemeindeScraper extends BaseScraper {
  name = 'gemeinden-generic';
  private delay = 1000; // 1s between municipalities
  private timeoutMs = 8000;

  private MONTH_MAP: Record<string, string> = {
    'jänner': '01', 'januar': '01', 'jan': '01',
    'februar': '02', 'feb': '02',
    'märz': '03', 'mär': '03', 'mar': '03',
    'april': '04', 'apr': '04',
    'mai': '05',
    'juni': '06', 'jun': '06',
    'juli': '07', 'jul': '07',
    'august': '08', 'aug': '08',
    'september': '09', 'sep': '09',
    'oktober': '10', 'okt': '10',
    'november': '11', 'nov': '11',
    'dezember': '12', 'dez': '12',
  };

  async scrape(): Promise<ScrapedEvent[]> {
    const dataPath = join(process.cwd(), 'data', 'gemeinden-event-pages.json');
    if (!existsSync(dataPath)) {
      console.log('No gemeinden-event-pages.json found. Run probe-gemeinden.ts first.');
      return [];
    }

    const rawPages: GemeindeEventPageRaw[] = JSON.parse(readFileSync(dataPath, 'utf8'));
    const pages: GemeindeEventPage[] = rawPages.flatMap(p => {
      const [g] = withStammdaten([p.gemeinde]);
      return g ? [{ ...p, gemeinde: g }] : [];
    });
    console.log(`  Loading ${pages.length} municipality event pages...`);

    const allEvents: ScrapedEvent[] = [];
    let processed = 0;
    let totalFound = 0;

    // 923 Seiten × ~15 s ≈ 225 min. Soft-Budget + Tagesrotation wie bei
    // gem2go: bei Abbruch geht das Teilergebnis in den Sync statt (wie
    // vor 2026-07-14) komplett am harten Timeout zu verfallen.
    const deadline = this.softDeadline();

    for (const page of this.rotateDaily(pages)) {
      if (Date.now() > deadline) {
        console.log(`  Soft-Budget erreicht nach ${processed}/${pages.length} — liefere ${allEvents.length} Events als Teilergebnis`);
        break;
      }
      processed++;
      try {
        const events = await this.scrapeGemeinde(page);
        if (events.length > 0) {
          allEvents.push(...events);
          totalFound += events.length;
          console.log(`  ✓ [${processed}/${pages.length}] ${page.gemeinde.name}: ${events.length} events`);
        }
      } catch (e) {
        // Skip silently
      }

      if (processed % 50 === 0 && totalFound === 0) {
        console.log(`  [${processed}/${pages.length}] ... ${allEvents.length} events total`);
      }

      await new Promise(r => setTimeout(r, this.delay));
    }

    console.log(`  Total: ${allEvents.length} events from ${pages.length} municipalities`);
    return allEvents;
  }

  private async scrapeGemeinde(page: GemeindeEventPage): Promise<ScrapedEvent[]> {
    const html = await this.fetchPageSafe(page.eventPageUrl);
    if (!html) return [];

    const g = page.gemeinde;
    const bundesland = this.normalizeBundesland(g.bundesland);

    // Parse first page
    let allEvents = this.parsePage(html, page);

    // ── Pagination: follow next pages ──
    if (allEvents.length > 0) {
      let currentHtml = html;
      let currentUrl = page.eventPageUrl;
      const visitedUrls = new Set<string>([currentUrl]);

      for (let p = 1; p < MAX_PAGES_PER_SITE; p++) {
        const { nextUrl } = detectNextPage(currentHtml, currentUrl);
        if (!nextUrl || visitedUrls.has(nextUrl)) break;
        visitedUrls.add(nextUrl);

        const nextHtml = await this.fetchPageSafe(nextUrl);
        if (!nextHtml) break;

        const nextEvents = this.parsePage(nextHtml, { ...page, eventPageUrl: nextUrl });
        if (nextEvents.length === 0) break;

        allEvents.push(...nextEvents);
        currentHtml = nextHtml;
        currentUrl = nextUrl;
        await new Promise(r => setTimeout(r, 500)); // rate limit between pages
      }

      // ── Month navigation: try upcoming months ──
      if (allEvents.length > 0 && allEvents.length < 5) {
        // Few events found — might be a month-view calendar, try next months
        const monthUrls = detectMonthNavigation(html, page.eventPageUrl);
        for (const mu of monthUrls) {
          if (visitedUrls.has(mu.url)) continue;
          visitedUrls.add(mu.url);

          const mHtml = await this.fetchPageSafe(mu.url);
          if (!mHtml) continue;

          const mEvents = this.parsePage(mHtml, { ...page, eventPageUrl: mu.url });
          allEvents.push(...mEvents);
          await new Promise(r => setTimeout(r, 500));
        }
      }
    }

    // Detail-page enrichment: fetch each event's source_url and pull
    // description/address/image/price out via the universal extractor.
    // Listing parsers above tend to capture only title + date + small teaser;
    // the detail page usually has the full event. Same approach as Gem2GoScraper.
    if (this.enableDetailEnrichment) {
      await this.enrichEventsFromDetailPages(allEvents, page.eventPageUrl);
    }

    // fn-25 B3: Gemeinde als Kontext (city + PLZ), Mittelpunkt nur als
    // gekennzeichnete Gebietsangabe, kein Gemeindename als Veranstaltungsort.
    const ctx = { name: g.name, plz: g.plz, lat: g.lat, lng: g.lng, bundesland, bezirk: g.bezirk, region: g.region };
    return allEvents.map(e => applyGemeindeContext({ ...e, bundesland }, ctx));
  }

  /** Detail-fetch toggle. ON by default — listing-level data is usually too thin.
   *  Renamed from `enrichFromDetail` to avoid collision with the protected
   *  BaseScraper.enrichFromDetail() method added 2026-05-21. */
  private readonly enableDetailEnrichment = true;
  /** Delay between detail-page fetches within the same gemeinde (ms). */
  private readonly detailDelayMs = 250;
  /** Per-detail-page fetch timeout. */
  private readonly detailTimeoutMs = 8000;

  /**
   * For each event with a distinct source_url, fetch the detail page and
   * merge the universal extractor's findings. Detail values win for structural
   * fields (address, postal_code, location_name, image_url) — listing parsers
   * often concatenate sub-spans without separators. Description merges by
   * "longer wins". Errors swallowed per-event.
   */
  private async enrichEventsFromDetailPages(events: ScrapedEvent[], listingUrl: string): Promise<void> {
    for (const e of events) {
      const url = e.source_url;
      if (!url || url === listingUrl) continue;
      try {
        const html = await this.fetchPageSafe(url);
        if (!html) continue;
        const det = extractGem2goDetail(html);

        if (det.address) e.address = det.address;
        // Seite mit Event-Inhalt ohne Adresse: eine gespeicherte stammt aus der
        // Fußzeile (Gemeindeamt), der Schreibpfad soll sie entfernen.
        else if (!e.address && (det.description || det.location_name)) e.address_rejected = 'page_boilerplate';
        if (det.postal_code) e.postal_code = det.postal_code;
        if (det.location_name && (!e.location_name || e.location_name.length < det.location_name.length)) {
          e.location_name = det.location_name;
        }
        if (det.image_url) e.image_url = det.image_url;
        if (!e.description || (det.description && e.description.length < det.description.length)) {
          if (det.description) e.description = det.description;
        }
        if (!e.price_text && det.price_text) e.price_text = det.price_text;
        if (e.price_min === undefined && det.price_min !== undefined) e.price_min = det.price_min;
        if (e.price_max === undefined && det.price_max !== undefined) e.price_max = det.price_max;
        // "frei" nur neben einem Betrag: ein früher gespeichertes "Eintritt frei" fällt.
        if (det.price_unclear && !e.price_text) e.price_rejected = 'unclear_free';
        if (!e.organizer && det.organizer) e.organizer = det.organizer;
      } catch {
        // swallow per-event errors
      }
      await new Promise(r => setTimeout(r, this.detailDelayMs));
    }
  }

  /** Parse a single page with all strategies */
  private parsePage(html: string, page: GemeindeEventPage): ScrapedEvent[] {
    const $ = cheerio.load(html);
    let events = this.parseWordPressEvents($, page);
    if (events.length === 0) events = this.parseTypo3Events($, page);
    if (events.length === 0) events = this.parseGenericEvents($, page);
    return events;
  }

  // ─── WordPress Event Plugins ────────────────────────────────────────

  private parseWordPressEvents($: cheerio.CheerioAPI, page: GemeindeEventPage): ScrapedEvent[] {
    const events: ScrapedEvent[] = [];
    const g = page.gemeinde;

    // WP Event Manager
    $('div.event_listing, article.type-event_listing, .wpem-event-listing').each((_, el) => {
      const $el = $(el);
      const titles = $el.find('.wpem-heading, .event_listing-title, h3, h2');
      const title = firstText(titles, isTitleCandidate);
      const dateText = $el.find('.event-date, .wpem-event-date, time').first().text().trim();
      const location = $el.find('.event-location, .wpem-event-location').first().text().trim();
      const link = $el.find('a').first().attr('href');
      const desc = $el.find('.event-description, .wpem-event-description, p').first().text().trim();

      if (!title) return;
      const date = this.parseDate(dateText);
      const id = (t: string) => `gemeinden-generic-${g.idKey}-${this.slugify(t)}`;

      events.push({
        source_id: id(title),
        ...this.previousId(firstText(titles, () => true), title, id),
        source_name: this.name,
        source_url: link ? new URL(link, page.eventPageUrl).href : page.eventPageUrl,
        title,
        description: desc || undefined,
        start_date: date || new Date().toISOString().split('T')[0],
        location_name: location || g.name,
        category: this.guessCategory(title + ' ' + desc),
      });
    });

    // The Events Calendar (Tribe)
    if (events.length === 0) {
      $('.tribe-events-list .type-tribe_events, .tribe-common-g-row').each((_, el) => {
        const $el = $(el);
        const titles = $el.find('.tribe-events-list-event-title, .tribe-event-title, h2, h3');
        const title = firstText(titles, isTitleCandidate);
        const dateText = $el.find('.tribe-events-schedule, .tribe-event-date-start, time, abbr').first().text().trim();
        const link = $el.find('a').first().attr('href');

        if (!title) return;
        const date = this.parseDate(dateText);
        const id = (t: string) => `gemeinden-generic-${g.idKey}-${this.slugify(t)}`;

        events.push({
          source_id: id(title),
          ...this.previousId(firstText(titles, () => true), title, id),
          source_name: this.name,
          source_url: link ? new URL(link, page.eventPageUrl).href : page.eventPageUrl,
          title,
          start_date: date || new Date().toISOString().split('T')[0],
          location_name: g.name,
          category: this.guessCategory(title),
        });
      });
    }

    return events;
  }

  // ─── Typo3 Event Extensions ─────────────────────────────────────────

  private parseTypo3Events($: cheerio.CheerioAPI, page: GemeindeEventPage): ScrapedEvent[] {
    const events: ScrapedEvent[] = [];
    const g = page.gemeinde;

    // Typo3 wt_eventman, cal, etc.
    $('.event-list-item, .tx-wteventman .event, .tx-cal-event, article.event, .news-list-item').each((_, el) => {
      const $el = $(el);
      // Erstes Element, das ein Event benennt: der Datums-Link vor der
      // Überschrift (tx_news-Liste, allerheiligen-wildon.at) ist keins.
      const titles = $el.find('h2, h3, .event-title, .news-title, a');
      const title = firstText(titles, isTitleCandidate);
      const dateText = $el.find('.event-date, .date, time, .news-date').first().text().trim();
      const link = $el.find('a').first().attr('href');
      const desc = $el.find('.event-teaser, .event-description, p, .news-teaser').first().text().trim();

      if (!title || title.length < 5) return;
      const date = this.parseDate(dateText);
      if (!date) return; // Must have a valid date for Typo3
      const id = (t: string) => `gemeinden-generic-${g.idKey}-${this.slugify(t)}`;

      events.push({
        source_id: id(title),
        ...this.previousId(firstText(titles, () => true), title, id),
        source_name: this.name,
        source_url: link ? new URL(link, page.eventPageUrl).href : page.eventPageUrl,
        title,
        description: desc || undefined,
        start_date: date,
        location_name: g.name,
        category: this.guessCategory(title + ' ' + (desc || '')),
      });
    });

    return events;
  }

  // ─── Generic HTML Parser ────────────────────────────────────────────

  private parseGenericEvents($: cheerio.CheerioAPI, page: GemeindeEventPage): ScrapedEvent[] {
    const events: ScrapedEvent[] = [];
    const g = page.gemeinde;
    const seen = new Set<string>();

    // Strategy: Find all elements containing a date pattern DD.MM.YYYY
    // Then extract the nearest heading/text as the event title
    const BLOCK = 'li, tr, div, article, section';
    const blockDates = (node: any): string[] | null => {
      const text = $(node).text();
      if (text.length > 1000 || text.length < 10) return null;
      const dates = findDates(text);
      return dates.length > 0 ? dates : null;
    };
    const sameDateSet = (a: string[], b: string[]) => {
      const sa = new Set(a), sb = new Set(b);
      return sa.size === sb.size && [...sa].every(d => sb.has(d));
    };

    // First try: look for list items, table rows, or divs that contain dates
    $(BLOCK).each((_, el) => {
      const $el = $(el);
      const text = $el.text();
      const dates = blockDates(el);
      if (!dates) return;

      // Ein Event = der äußerste Block mit genau diesen Daten (die Kachel).
      // Die inneren Blöcke derselben Kachel (Datums-Badge, Wochentag,
      // Ortszeile) lieferten sonst eigene Events mit Titeln wie "Mittwoch",
      // "Gemeindesaal" oder "Datum der VeranstaltungMi," (Prod 2026-10-06).
      const parentBlock = $el.parent().closest(BLOCK);
      if (parentBlock.length) {
        const parentDates = blockDates(parentBlock[0]);
        if (parentDates && sameDateSet(parentDates, dates)) return;
      }
      // Umgekehrt ist ein Block mit mehreren Kacheln (eigene Datums-Blöcke
      // mit verschiedenen Detail-Links) nur die Liste, kein Event. Spalten
      // EINER Kachel (Bild + Text) verlinken dasselbe Ziel.
      const cardLinks = new Set<string>();
      $el.find(BLOCK).each((_, n) => {
        if ($(n).parent().closest(BLOCK)[0] !== el) return;
        if (findDates($(n).text()).length === 0) return;
        const href = this.firstContentAnchorHref($(n));
        if (href) cardLinks.add(href);
      });
      if (cardLinks.size >= 2) return;

      const dateStr = dates[0];

      // Skip past dates
      if (new Date(dateStr) < new Date('2025-01-01')) return;

      let title = this.blockTitle($el, text, isTitleCandidate);
      let $card: cheerio.Cheerio<any> = $el;
      if (!title) {
        // Kachel länger als ein Block (tulln.at: >1000 Zeichen) oder
        // Datumszeile neben dem Titel (strass-steiermark.gv.at): der Titel
        // steht im umschließenden Element, das genau dieselben Daten nennt.
        // Ein Element mit weiteren Daten ist die Liste oder eine Kachel mit
        // "Von: … Bis: …", dort ist die einzelne Zeile kein Event. Ohne
        // Überschrift zählt ein Link nur, wenn das Element ein einziges
        // Ziel verlinkt: der Seitenkopf verlinkt viele und lieferte sonst
        // "Aktuelles" (gralla.at).
        let $up = $el.parent().closest(BLOCK);
        for (let level = 0; level < 3 && $up.length; level++) {
          const upText = $up.text();
          if (upText.length > 4000 || !sameDateSet(findDates(upText), dates)) break;
          title = (firstText($up.find('h2, h3, h4, h5, h6'), isTitleCandidate)
            || (this.linkTargets($up).size === 1 ? this.firstContentAnchorText($up, isTitleCandidate) : ''))
            .replace(/\s+/g, ' ').trim();
          if (title) { $card = $up; break; }
          $up = $up.parent().closest(BLOCK);
        }
      }
      if (title.length < 5 || title.length > 200) return;

      const key = `${dateStr}-${title.substring(0, 30)}`;
      if (seen.has(key)) return;
      seen.add(key);

      // Try to find a link (mailto:/tel: waeren keine Detailseite)
      const link = this.firstContentAnchorHref($el) ?? this.firstContentAnchorHref($card);

      // Try to extract time
      const time = extractTimeOfDay(text);
      const startDate = time ? `${dateStr}T${time}` : dateStr;
      const id = (t: string) => `gemeinden-generic-${g.idKey}-${this.slugify(t)}-${dateStr}`;

      events.push({
        source_id: id(title),
        ...this.previousId(this.blockTitle($el, text, () => true), title, id),
        source_name: this.name,
        source_url: link ? new URL(link, page.eventPageUrl).href : page.eventPageUrl,
        title,
        start_date: startDate,
        location_name: g.name,
        category: this.guessCategory(title),
      });
    });

    return events;
  }

  // ─── Helpers ────────────────────────────────────────────────────────

  /**
   * Titel eines Datums-Blocks: Überschrift, sonst Titel-Element, Link,
   * Fettdruck, sonst die erste Textzeile ohne Datum; leer, wenn er kein
   * Event benennt. Überschrift, Titel-Element und Link nehmen das erste
   * Element, das `accept` annimmt (der Titel steht oft neben einem
   * Datums-Element derselben Art), Fettdruck und Textzeile nur das erste:
   * sonst würde aus "12." die Uhrzeit mit Ort ("09:30 Uhr, Kolm Saigurn").
   * Mit `() => true` ist es die Titelwahl vor 2026-10, die Datums-
   * Überschriften ("09.10.2026" vor dem Titel, herzogenburg.at) und
   * Datums-Links ("Fr Okt 09", ybbs.gv.at) als Titel nahm.
   */
  private blockTitle($el: cheerio.Cheerio<any>, text: string, accept: (t: string) => boolean): string {
    let title = this.cardTitle($el, accept);
    // Überschrift oder Link der Kachel ist nur ein Datum: dann benennt auch
    // Fettdruck oder Fließtext kein Event (völkermarkt.gv.at: Überschrift
    // "10. Oktober …", erste Textzeile "BEITRAG VOM").
    if (!title && this.cardTitle($el, () => true)) return '';
    title ||= $el.find('strong, b').first().text().trim();
    if (!title || title.length < 5) {
      // Use the text but remove the date, take first meaningful line
      title = text.replace(/\d{1,2}\.\d{1,2}\.20\d{2}/g, '').trim();
      const lines = title.split(/\n/).map(l => l.trim()).filter(l => l.length > 3);
      title = lines[0] || title;
    }
    title = title.replace(/\s+/g, ' ').trim();
    return accept(title) ? title : '';
  }

  /**
   * Überschrift, Titel-Element oder Link-Text einer Kachel.
   * Anchors sind absichtlich NACH den Headings und ohne mailto:/tel:
   * — `find()` liefert Dokumentreihenfolge, nicht Selektorreihenfolge,
   * sonst gewinnt der Kontakt-Link eines Vereinsblocks gegen die
   * Ueberschrift und die Mailadresse wird zum Titel.
   */
  private cardTitle($el: cheerio.Cheerio<any>, accept: (t: string) => boolean): string {
    return firstText($el.find('h2, h3, h4, h5, h6'), accept)
      || this.titleElementText($el, accept)
      || this.firstContentAnchorText($el, accept);
  }

  /** Alte ID einer Zeile, deren Titel der Parser früher anders las: der
   *  Sync schlüsselt sie um (source-id-migration.ts), Zeilen-ID und Slug
   *  bleiben erhalten. */
  private previousId(
    legacyTitle: string,
    title: string,
    id: (t: string) => string,
  ): { previous_source_id?: string } {
    const legacy = legacyTitle.replace(/\s+/g, ' ').trim();
    if (!legacy || id(legacy) === id(title)) return {};
    return { previous_source_id: id(legacy) };
  }

  /** Text des innersten Elements mit "title"/"header" in der Klasse
   *  (z. B. gem2go-Karten: `.card-title > .bemHeader`), ohne Datum. */
  private titleElementText($el: cheerio.Cheerio<any>, accept: (t: string) => boolean): string {
    const sel = '[class*="title" i], [class*="header" i]';
    const nodes = $el.find(sel);
    for (let i = 0; i < nodes.length; i++) {
      if (nodes.eq(i).find(sel).length > 0) continue;
      const text = nodes.eq(i).text().replace(/\s+/g, ' ').trim();
      if (text.length >= 5 && findDates(text).length === 0 && accept(text)) return text;
    }
    return '';
  }

  /** Text des ersten Anchors, der kein Kontakt-Link (mailto:/tel:/…) ist.
   *  Anchors ganz ohne href bleiben zulaessig — die sind reine Wrapper.
   *  Generische Linktexte ("mehr Informationen") und Anchors, die die
   *  ganze Kachel samt Datum umschließen, benennen kein Event. */
  private firstContentAnchorText($el: cheerio.Cheerio<any>, accept: (t: string) => boolean): string {
    const anchors = $el.find('a');
    for (let i = 0; i < anchors.length; i++) {
      const a = anchors.eq(i);
      const href = a.attr('href');
      if (href && !isUsableDetailHref(href)) continue;
      const text = a.text().trim();
      if (GENERIC_LINK_TEXT.test(text) || findDates(text).length > 0) continue;
      if (text && accept(text)) return text;
    }
    return '';
  }

  /** Alle Detail-Ziele (kein mailto:/tel:) der Anchors im Element. */
  private linkTargets($el: cheerio.Cheerio<any>): Set<string> {
    const targets = new Set<string>();
    const anchors = $el.find('a');
    for (let i = 0; i < anchors.length; i++) {
      const href = anchors.eq(i).attr('href');
      if (isUsableDetailHref(href)) targets.add(href!);
    }
    return targets;
  }

  /** Href des ersten Anchors, der auf eine Detailseite zeigt (kein mailto:/tel:). */
  private firstContentAnchorHref($el: cheerio.Cheerio<any>): string | undefined {
    const anchors = $el.find('a');
    for (let i = 0; i < anchors.length; i++) {
      const href = anchors.eq(i).attr('href');
      if (isUsableDetailHref(href)) return href;
    }
    return undefined;
  }

  private async fetchPageSafe(url: string): Promise<string | null> {
    try {
      const r = await fetch(url, {
        redirect: 'follow',
        signal: AbortSignal.timeout(this.timeoutMs),
        headers: {
          'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
          'Accept': 'text/html',
          'Accept-Language': 'de-AT,de;q=0.9',
        },
      });
      if (!r.ok) return null;
      return await r.text();
    } catch {
      return null;
    }
  }

  private parseDate(text: string): string | null {
    if (!text) return null;

    // Try DD.MM.YYYY
    const numMatch = text.match(/(\d{1,2})\.(\d{1,2})\.(20\d{2})/);
    if (numMatch) {
      return `${numMatch[3]}-${numMatch[2].padStart(2, '0')}-${numMatch[1].padStart(2, '0')}`;
    }

    // Try "DD. Monat YYYY" (German month names)
    const wordMatch = text.match(/(\d{1,2})\.?\s*(\w+)\s+(20\d{2})/);
    if (wordMatch) {
      const month = this.MONTH_MAP[wordMatch[2].toLowerCase()];
      if (month) {
        return `${wordMatch[3]}-${month}-${wordMatch[1].padStart(2, '0')}`;
      }
    }

    return null;
  }

  private normalizeBundesland(bl: string): string {
    return bl.toLowerCase()
      .replace('ö', 'oe')
      .replace('ä', 'ae')
      .replace('ü', 'ue');
  }

  private slugify(text: string): string {
    return text.toLowerCase()
      .replace(/[äÄ]/g, 'ae').replace(/[öÖ]/g, 'oe').replace(/[üÜ]/g, 'ue').replace(/ß/g, 'ss')
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '')
      .substring(0, 60);
  }

  private guessCategory(text: string): string {
    const lower = text.toLowerCase();
    if (/konzert|musik|band|chor|orchester|jazz|rock|pop|unplugged/.test(lower)) return 'Musik';
    if (/sport|turnier|lauf|marathon|fußball|tennis|wanderung|radtour/.test(lower)) return 'Sport';
    if (/markt|flohmarkt|bauernmarkt|weihnachtsmarkt|ostermarkt/.test(lower)) return 'Märkte';
    if (/kultur|theater|kabarett|lesung|ausstellung|museum|vernissage/.test(lower)) return 'Kultur';
    if (/kinder|familie|basteln|spielen|feriencamp/.test(lower)) return 'Familie';
    if (/wein|kulinarik|verkostung|genuss|heuriger|brunch/.test(lower)) return 'Wein & Kulinarik';
    if (/wanderung|natur|garten|wald|berg|alm/.test(lower)) return 'Natur';
    if (/kirche|messe|gottesdienst|wallfahrt|firmung|kommunion/.test(lower)) return 'Sonstiges';
    return 'Sonstiges';
  }
}
