import type { MetadataRoute } from 'next';

/**
 * robots.txt for lasstreffen.at.
 *
 * Disallowed paths fall into three buckets:
 * - `/api/`, `/admin/`, `/auth/` — never meant to be indexed.
 * - Authenticated user UI (`/feed`, `/messages`, `/saved`, `/groups`,
 *   `/notifications`, `/memories`, `/friends`, `/profile`, `/settings`,
 *   `/artists`, `/spotify-matches`, `/events/create`, `/calendar`) — these
 *   are all auth-gated and either redirect or render empty to bots. Bing's
 *   Site-Scan was flagging them as "H1 missing / thin content" because it
 *   indexed the logged-out shell.
 * - Low-quality / draft / duplicate events are noindexed via meta robots
 *   tags directly in `src/app/events/[slug]/page.tsx`.
 *
 * The sitemap is generated by `src/app/sitemap.xml/route.ts` and only
 * contains events with `publish_status='published'` and quality_score ≥ 40.
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: '*',
      allow: '/',
      disallow: [
        '/api/',
        '/admin/',
        '/auth/',
        '/profile/',
        '/settings/',
        '/feed/',
        '/messages/',
        '/saved/',
        '/notifications/',
        '/groups/',
        '/memories/',
        '/friends/',
        '/calendar/',
        '/artists/',
        '/spotify-matches/',
        '/events/create',
      ],
    },
    sitemap: 'https://lasstreffen.at/sitemap.xml',
  };
}
