import type { MetadataRoute } from 'next';

/**
 * robots.txt for lasstreffen.at.
 *
 * Two concerns:
 *
 *  1. **Indexing policy** — what parts of the site are public vs auth-gated.
 *     Disallowed paths fall into three buckets:
 *     - `/api/`, `/admin/`, `/auth/` — never meant to be indexed.
 *     - Authenticated user UI (`/feed`, `/messages`, `/saved`, `/groups`,
 *       `/notifications`, `/memories`, `/friends`, `/profile`, `/settings`,
 *       `/artists`, `/spotify-matches`, `/events/create`, `/calendar`) —
 *       these are all auth-gated and either redirect (server-side, since
 *       the auth-gate refactor) or render empty to bots. Bing's Site-Scan
 *       was flagging them as "H1 missing / thin content" because it
 *       indexed the logged-out shell before the server-side gate landed.
 *     - Low-quality / draft / duplicate events are noindexed via meta
 *       robots tags directly in `src/app/events/[slug]/page.tsx`.
 *
 *  2. **AI-crawler policy** — explicit allow for GEO (Generative Engine
 *     Optimization). The wildcard `User-agent: *` rule would already cover
 *     these bots, but listing them by name documents the editorial intent
 *     and survives future changes to the wildcard policy. AI agents that
 *     fetch pages to answer queries (ChatGPT Browse, Perplexity, Claude
 *     Browse, Google AI Overviews) are first-class citizens here — the
 *     goal of Phase 7 is precisely to be cited in their answers, so
 *     blocking them would be self-sabotage.
 *
 * The sitemap is generated by `src/app/sitemap.xml/route.ts` and only
 * contains events with `publish_status='published'` and quality_score ≥ 40.
 */
export default function robots(): MetadataRoute.Robots {
  // Single source of truth for the auth-gated / admin paths.
  const authGatedAndAdminDisallow = [
    '/api/',
    '/admin/',
    '/auth/',
    '/profile/',
    '/settings/',
    '/feed/',
    '/messages/',
    '/saved/',
    '/notifications/',
    '/groups/',
    '/memories/',
    '/friends/',
    '/calendar/',
    '/artists/',
    '/spotify-matches/',
    '/events/create',
  ];

  // AI-agent user-agents we want to explicitly acknowledge. All currently
  // have "allow everything that's not auth-gated" — mirrors the wildcard
  // policy. Sources:
  //   - OpenAI GPTBot: https://platform.openai.com/docs/gptbot
  //   - ChatGPT-User: fetches pages on behalf of a ChatGPT Browse request
  //   - OAI-SearchBot: OpenAI's search-oriented crawler
  //   - Anthropic ClaudeBot + anthropic-ai: Claude training + citation
  //   - Claude-Web: live Browse on behalf of a Claude user request
  //   - PerplexityBot + Perplexity-User: https://docs.perplexity.ai/guides/bots
  //   - Google-Extended: gates Gemini + AI Overviews (different from
  //     Googlebot which handles classic search indexing)
  //   - CCBot: Common Crawl — used as training data by many LLMs
  //   - Applebot-Extended: gates Apple Intelligence training
  //   - Bytespider: ByteDance, powers TikTok + Doubao AI
  //   - Amazonbot, cohere-ai, Meta-ExternalAgent, DuckAssistBot, Diffbot
  const aiCrawlers = [
    'GPTBot',
    'ChatGPT-User',
    'OAI-SearchBot',
    'ClaudeBot',
    'Claude-Web',
    'anthropic-ai',
    'PerplexityBot',
    'Perplexity-User',
    'Google-Extended',
    'Applebot-Extended',
    'CCBot',
    'Bytespider',
    'Amazonbot',
    'cohere-ai',
    'Diffbot',
    'Meta-ExternalAgent',
    'DuckAssistBot',
  ];

  return {
    rules: [
      // Default wildcard rule — applies to anything we don't list explicitly
      {
        userAgent: '*',
        allow: '/',
        disallow: authGatedAndAdminDisallow,
      },
      // Explicit AI-crawler allowances. Each bot gets the same indexing
      // policy as the wildcard, but listing them by name is a clear
      // "yes, please come and cite us" signal.
      ...aiCrawlers.map((ua) => ({
        userAgent: ua,
        allow: '/',
        disallow: authGatedAndAdminDisallow,
      })),
    ],
    sitemap: 'https://lasstreffen.at/sitemap.xml',
  };
}
