-- ============================================================================
-- Migration: pgvector + embeddings for semantic-search
--
-- Enables natural-language queries like "ich bin student und will heute
-- abend billig saufen gehen" → vector match against event embeddings
-- combined with hard filters (date, price_tier, audience).
--
-- Embeddings are generated by scripts/build-embeddings.ts using OpenAI's
-- text-embedding-3-small (1536 dimensions, $0.02/1M tokens ≈ $0.50 for
-- all 42k events one-time). Re-embedded only when content changes.
-- ============================================================================

-- Raise timeout for the ivfflat index build on a table with ~50k rows.
set statement_timeout = '10min';

-- 1. pgvector extension — Supabase already supports this, just enable
create extension if not exists vector;

-- 2. New column on events
-- 1536 = text-embedding-3-small dim. text-embedding-3-large is 3072.
-- If we ever switch model, re-run build-embeddings.ts with the new dim.
alter table events
  add column if not exists embedding vector(1536);

alter table events
  add column if not exists embedding_hash text;
-- ^^ SHA-256 of the source text used to produce the embedding. Lets the
-- build-embeddings script skip rows whose content hasn't changed,
-- saving API calls on re-runs.

-- 3. ivfflat index for fast cosine-similarity search.
--
-- ivfflat partitions vectors into N "lists" (Voronoi cells). Rule of
-- thumb: lists ≈ rows / 1000 for up to ~1M rows. We have ~50k events →
-- 50 lists. Trade-off: more lists = faster recall, but slower build and
-- slower inserts.
--
-- probes=10 at query time gives ~95%+ recall — good default.
create index if not exists idx_events_embedding_cosine
  on events
  using ivfflat (embedding vector_cosine_ops)
  with (lists = 50);

-- 4. RPC wrapper for typed, parameterized vector search.
-- Client passes: query_embedding, limit, min similarity, optional filters.
-- Returns rows sorted by descending similarity.
create or replace function search_events_semantic(
  query_embedding vector(1536),
  match_limit int default 20,
  min_similarity real default 0.0,
  filter_after_date timestamptz default null,
  filter_max_price_tier text default null    -- pass 'günstig' to include gratis+günstig
)
returns table (
  id uuid,
  title text,
  similarity real
)
language sql
stable
as $$
  select
    e.id,
    e.title,
    (1 - (e.embedding <=> query_embedding))::real as similarity
  from events e
  where e.embedding is not null
    and (filter_after_date is null or e.start_date >= filter_after_date)
    and (
      filter_max_price_tier is null
      or (filter_max_price_tier = 'gratis' and e.price_tier in ('gratis'))
      or (filter_max_price_tier = 'günstig' and e.price_tier in ('gratis','günstig'))
      or (filter_max_price_tier = 'mittel' and e.price_tier in ('gratis','günstig','mittel'))
    )
    and (1 - (e.embedding <=> query_embedding)) >= min_similarity
  order by e.embedding <=> query_embedding
  limit match_limit;
$$;

-- 5. Sanity check — print how many events are ready to be searched
do $$
declare
  total int;
  with_emb int;
begin
  select count(*) into total from events;
  select count(*) into with_emb from events where embedding is not null;
  raise notice 'Events total: %  with embedding: %  (% pending)', total, with_emb, total - with_emb;
end $$;
