import { gunzipSync } from 'node:zlib';
import type { EventimSeries, EventimFeed } from './types';

const DEFAULT_URL = 'https://pft.eventim.com/serve/214-hemfto';

/**
 * Download + decompress the Eventim PFT feed. Returns the event series array.
 * The feed is a single gzipped JSON `{ eventserie: [...] }` (~57 MB raw),
 * regenerated by Eventim every 1–6 h. HTTP Basic Auth.
 *
 * NOTE: loads the whole feed into memory. Fine for a Node CLI run; if used on
 * a memory-constrained serverless function, swap for a streaming gunzip+parse
 * (tracked in Slice 5 / cron).
 */
export async function downloadEventimFeed(opts?: {
  url?: string;
  user?: string;
  pass?: string;
}): Promise<EventimSeries[]> {
  const url = opts?.url ?? process.env.EVENTIM_FEED_URL ?? DEFAULT_URL;
  const user = opts?.user ?? process.env.EVENTIM_FEED_USER;
  const pass = opts?.pass ?? process.env.EVENTIM_FEED_PASS;
  if (!user || !pass) {
    throw new Error('Eventim feed credentials missing (EVENTIM_FEED_USER / EVENTIM_FEED_PASS).');
  }

  const auth = Buffer.from(`${user}:${pass}`).toString('base64');
  const res = await fetch(url, { headers: { Authorization: `Basic ${auth}` } });
  if (!res.ok) throw new Error(`Eventim feed HTTP ${res.status} ${res.statusText}`);

  const gz = Buffer.from(await res.arrayBuffer());
  const json = JSON.parse(gunzipSync(gz).toString('utf8')) as EventimFeed;
  return json.eventserie ?? [];
}
